salt/control-node/init.sls

This key is needed for jenkins automation context.

FEATURE: Add authorized key for control-node

---

modules/libvirt/base/main.tf
modules/libvirt/host/main.tf

improve the support to sles-12-sp2

update main.tf with sles12sp2

---

modules/libvirt/base/main.tf
salt/client/repos.sls
salt/sles/repos.d/SLE-12-SP2-x86_64-Pool.repo
salt/sles/repos.d/SLE-12-SP2-x86_64-Update.repo
salt/sles/repos.sls

This adds support for sles and client tools repos for sles12 sp2

Add sles12sp2 tools repo and sles repos 

---

modules/libvirt/base/main.tf

External access requires suse.com access.

Fix: use suse.com address instead of .de

---

TROUBLESHOOTING.md

Instructions on how to run terraform from an arbitrary directory without getting an error. Feel free to edit for brevity and style.

Instructions on how to run terraform from an arbitrary directory

---

modules/libvirt/control_node/main.tf
modules/libvirt/control_node/variables.tf

Augment default memory for control node

---

main.tf.openstack.example
modules/libvirt/base/main.tf
modules/libvirt/client/main.tf
modules/libvirt/host/main.tf
modules/libvirt/minion/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/openstack/host/main.tf
modules/openstack/host/variables.tf

This PR adds the new features to terraform [as per issue 73](https://github.com/moio/sumaform/issues/73):
- conditionals
- interpolated dictionaries
- dependencies on modules

Remove hacks by using Terraform 0.8 features

---

salt/controller/init.sls

.. text and fonts are missing.

FIX: Without this pkg, screenshot are not full..

---

salt/default/repos.sls

in all version of centos7 (head, etc)

BUGFIX: the repo should be there in all version..

---

README_ADVANCED.md
TROUBLESHOOTING.md
main.tf.aws.example
main.tf.libvirt.example
modules/aws/host/variables.tf
modules/aws/minionswarm/main.tf
modules/libvirt/client/variables.tf
modules/libvirt/grafana/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/minionswarm/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
salt/default/repos.sls
salt/suse_manager_proxy/init.sls
salt/suse_manager_proxy/repos.sls
salt/suse_manager_server/init.sls
salt/suse_manager_server/repos.sls
salt/suse_manager_server/rhn.sls

This should be clearer for end users, at the moment and in future, as discussed with Eric.
@Bischoff can you please try this out? An explanation of the versions' meaning would also be nice in the README, if you have time to write one.

Change version naming scheme

---

README_ADVANCED.md

* latest naming conventions for versions
* more information about versions
* moved to top

Updated and reworked information about versions

---

salt/suse_manager_proxy/init.sls
salt/suse_manager_server/init.sls

Add 3.1-nightly for server packages

add 3.1-nightly for server packages

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/README.md
modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf

fix issue  https://github.com/moio/sumaform/issues/26.

Create Image on demand

---

main.tf.libvirt-testsuite.example
modules/libvirt/base/main.tf

And Use sles12sp1 for testsuite example(since controller use this)

BUGFIX: Append Prefix for disk creation

---

README_ADVANCED.md
modules/libvirt/client/main.tf
modules/libvirt/client/variables.tf
modules/libvirt/host/main.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
salt/default/init.sls
salt/default/repos.d/SLE-11-SP3-x86_64-Test-Update.repo
salt/default/repos.d/SLE-11-SP4-x86_64-Test-Update.repo
salt/default/repos.d/SLE-12-SP1-x86_64-Test-Update.repo
salt/default/repos.d/SLE-12-SP2-x86_64-Test-Update.repo
salt/default/repos.d/SLE-12-x86_64-Test-Update.repo
salt/default/repos.sls
salt/default/updatesalt.sls
salt/mirror/mirror.lftp

This pr tests adds a new variable "test_sle_updates": which adds sle updates in maintenance and patches the sle vms that get this variable.  they will be rebooted by a feature in the testsuite.

Test sle updates

---

README_ADVANCED.md

cosmetical

---

main.tf.libvirt-testsuite.example

We need a 1:1 production, so people learn right prefixes names

Reflect production prefix names

---

README_ADVANCED.md
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
salt/mirror/mirror.lftp
salt/suse_manager_server/filebeat.sls
salt/suse_manager_server/filebeat.yml
salt/suse_manager_server/init.sls
salt/suse_manager_server/repos.d/filebeat.repo
salt/suse_manager_server/repos.sls

This pull requests introduces the `filebeat` setting to forward Server logs to logstash

Filebeat - allow log forwarding

---

salt/controller/init.sls

branches for the testsuite inside codebase.

Remove this gem, since this got integrated on all

---

.ci-travis/minion
.ci-travis/salt-server-validation
.travis.yml

See https://docs.travis-ci.com/user/reference/trusty/#Routing-to-Trusty

Test: run Travis in containers instead of VMs

---

README.md

Add travis status

---

README_ADVANCED.md
modules/aws/host/main.tf
modules/aws/host/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
salt/suse_manager_server/initial_content.sls
salt/suse_manager_server/wait_for_reposync.py

Ever wanted to have some channels and products pre-reposynced in your SUSE Manager Server?
Now you can :smile:

Add option to reposync channels at deploy time

---

.ci-travis/salt-ctl-validation
main.tf.libvirt-testsuite.example
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
salt/controller/bashrc

* Added possibility to configure proxy on controller
* Added variable $PROXY on controller

Support for proxy on controller

---

salt/controller/bashrc

Counterintuitive syntax to test absence of grain

---

main.tf.libvirt-testsuite.example

@moio @mbologna  thx in advance

Update to sles12sp3 example

---

README.md
main.tf.aws.example
modules/aws/evil_minions/main.tf
modules/aws/host/main.tf
modules/aws/minionswarm/main.tf
modules/aws/mirror/main.tf
modules/aws/network/main.tf
modules/libvirt/base/main.tf
modules/libvirt/host/main.tf
modules/libvirt/mirror/main.tf

Also moves tools to the systemsmanagement:sumaform namespace in OBS.

Upgrade Terraform to v0.10.7

---

modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
salt/controller/init.sls
salt/controller/run-testsuite.sh

This is needed when we want to clone from private repo

Add netrc for cloning with git_credentials

---

salt/controller/init.sls

Workaround saltstack issue with shallowclone

---

modules/libvirt/base/variables.tf
modules/libvirt/client/variables.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/variables.tf
salt/default/repos.d/Devel_Galaxy_Manager_3.1_SLE-Manager-Tools-15-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_Head_SLE-Manager-Tools-15-x86_64.repo
salt/default/repos.d/SLE-15-x86_64-Pool.repo
salt/default/repos.d/SLE-15-x86_64-Test-Update.repo
salt/default/repos.d/SLE-15-x86_64-Update.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Pool.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Update.repo
salt/default/repos.sls
salt/mirror/minima.yaml

Initial support for SLE15
- declare image
- define repositories (as soon as they are available in euklid we need to change some URLs)
I was able to setup a traditional client and a minion.

Support for SLE15

---

modules/libvirt/base/variables.tf
modules/libvirt/client/variables.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/variables.tf
salt/default/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Pool.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Update.repo

- renamed the image like requested by @MalloZup 
- updated the image to beta 4
- fixed a typo in future URL
I am still waiting for release managers to release the Tools Channel under the final URL. This will
hopefully happen when Beta 4 gets released.

SLES15 Beta4

---

salt/suse_manager_server/repos.sls

Revert "Remove client tools repos from srv after deployment"

---

README.md
main.tf.openstack.example
modules/openstack/README.md
modules/openstack/base/main.tf
modules/openstack/base/variables.tf
modules/openstack/client/main.tf
modules/openstack/client/variables.tf
modules/openstack/controller/main.tf
modules/openstack/controller/variables.tf
modules/openstack/evil_minions/main.tf
modules/openstack/evil_minions/variables.tf
modules/openstack/grafana/main.tf
modules/openstack/grafana/variables.tf
modules/openstack/host/main.tf
modules/openstack/host/variables.tf
modules/openstack/minion/main.tf
modules/openstack/minion/variables.tf
modules/openstack/minionswarm/main.tf
modules/openstack/minionswarm/variables.tf
modules/openstack/mirror/main.tf
modules/openstack/mirror/variables.tf
modules/openstack/postgres/main.tf
modules/openstack/postgres/variables.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager/variables.tf
modules/openstack/suse_manager_proxy/main.tf
modules/openstack/suse_manager_proxy/variables.tf
salt/mirror/init.sls

This re-adds OpenStack as a backend, aligned with the libvirt one.

New OpenStack backend

---

README_ADVANCED.md
main.tf.openstack.example
modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/host/main.tf
modules/openstack/base/main.tf
modules/openstack/base/variables.tf
modules/openstack/host/main.tf

Add support for sharing resources

---

salt/controller/repos.d/Devel_Galaxy_cucumber_testsuite.repo

fix mirror cucumber_repo

---

salt/grafana/init.sls

for better integration with other jobs

Prefer job scraping instead of global one

---

main.tf.libvirt-testsuite.example
modules/libvirt/controller/main.tf
modules/openstack/controller/main.tf
salt/controller/init.sls
salt/controller/repos.d/Devel_Galaxy_cucumber_testsuite.repo
salt/controller/repos.d/SLE-12-SP3-SDK-x86_64-Pool.repo
salt/controller/repos.sls
salt/mirror/minima.yaml

Move controller to opensuse_leap423

---

salt/controller/bashrc
salt/controller/init.sls

keep phantomjs and adapt  chromium for 31/head branch

enable chromium and preserve phantomjs for 30 compatibility

---

salt/client/testsuite.sls

merged https://github.com/SUSE/spacewalk/pull/3813

remove unused pkg

---

salt/controller/run-testsuite.sh

this can be merged as prepraration for this https://github.com/SUSE/spacewalk/pull/3846

Parallel cucumber as an option

---

modules/aws/evil_minions/main.tf
modules/aws/host/main.tf
modules/aws/minionswarm/main.tf
modules/aws/mirror/main.tf
modules/libvirt/host/main.tf
modules/openstack/host/main.tf

Fail Terraform when Salt fails

---

salt/suse_manager_server/master-custom.conf
salt/suse_manager_server/salt_master.sls

Apply salt/master.d/custom.conf always and decide in the template to add auto_accept or not.

move the grain check for auto_accept in the template file

---

salt/minion/repos.d/SLE-Module-Containers-SLE-15-x86_64-Pool.repo
salt/minion/repos.d/SLE-Module-Containers-SLE-15-x86_64-Update.repo
salt/minion/testsuite.sls

add sle15 minion docker support

---

README_ADVANCED.md
modules/libvirt/locust/main.tf
modules/libvirt/locust/variables.tf
modules/libvirt/pts/main.tf
modules/openstack/locust/main.tf
modules/openstack/locust/variables.tf
modules/openstack/pts/main.tf
salt/locust/init.sls

Adds optional support for master/slave Locust configuration and updates the PTS to make use of it.

Distributed Locust

---

modules/libvirt/base/variables.tf
modules/libvirt/client/variables.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/variables.tf
modules/openstack/base/variables.tf
modules/openstack/client/variables.tf
modules/openstack/host/variables.tf
modules/openstack/minion/variables.tf

move to sles15rc4

---

salt/suse_manager_proxy/config-answers.txt

Now proxy can be of version 3.2.

Accept 3.2 as proxy version

---

main.tf.libvirt-testsuite.example

as couple of people got bit by this.

Document the need for updating hostname in server_configuration whencustom name_prefix is used

---

salt/default/testsuite.sls

Fix on top of PR #341 - dependencies make it hard to factorize states, better not try to be too clever

[WIP] Fix: factorizing refresh states does not work

---

TROUBLESHOOTING.md

Troubleshooting for working with more than one workspace

Troubleshooting for working with more than one workspace

---

modules/libvirt/base/variables.tf
modules/openstack/base/variables.tf
packer/http/ks_sles-es7.cfg
packer/scripts/base-es.sh
packer/scripts/cloud.sh
packer/sles-es7openstack.json

git clone https://src.fedoraproject.org/rpms/cloud-init.git

add cloud script to sles7.4 and enable img for both backend

---

modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/openstack/base/main.tf
modules/openstack/base/variables.tf

Independent declaration of images

---

salt/mirror/minima.yaml

The minima.yaml was outdated and did not contain the latest master changes

fixed minima config

---

modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf

Forgot 3.2-nightly definition for SUSE Manager Proxy

add missing 3.2-nightly definition for proxy

---

salt/first_deployment_highstate.sh

ignore errors on first state call but exit when highstate failed

---

salt/mirror/minima.yaml
salt/repos/repos.d/Leap-SUSE-Manager-Proxy-Head-x86_64-Pool.repo
salt/repos/repos.d/SUSE-Manager-Head-x86_64-Pool.repo
salt/repos/repos.d/SUSE-Manager-Proxy-Head-x86_64-Pool.repo

Related to https://build.suse.de/request/show/169619

Bump HEAD to version 4.0

---

salt/repos/repos.d/SUSE-Manager-Proxy-3.2-x86_64-Update.repo
salt/repos/suse_manager_proxy.sls

Note: I did not find how to add it to minima.yaml. Maybe it's not needed. Could you please check?

Adding 3.2 proxy updates repo

---

salt/repos/repos.d/SUSE-Manager-3.2-x86_64-Update.repo
salt/repos/suse_manager_server.sls

This PR finished the work for 3.2 update repositories now we have them after GA.

Add 3.2 server update repositories

---

salt/controller/bashrc

After discussion with @mcalmer

Rename NOTWITHFROMDIR to MIRROR when we use a mirror

---

salt/minion/testsuite.sls

Temporarily move kiwi-desc-saltboot package to main.tf

---

packer/scripts/base.sh

Comment out `TYPE=Ethernet` in `/etc/sysconfig/network-scripts/ifcfg-ethX`

Remove Ethernet type from ifcfg-ethX as we might use virtio

---

packer/centos7.json
packer/scripts/base-es.sh
packer/scripts/base.sh
packer/sles-es7.json

Just aligning code between versions

Cleanup packer code

---

modules/libvirt/controller/main.tf
modules/openstack/controller/main.tf

We have problems with out URLs... I will do bug reports.

Kiwi does not work if branch name is omitted

---

modules/libvirt/base/main.tf
modules/openstack/base/main.tf

Using new CentOS 7 image

---

main.tf.libvirt-testsuite.example
main.tf.openstack-testsuite.example

Added example how to use git_profiles_repo

---

salt/default/hostname.sls
salt/repos/default.sls

major OS release number tests that do not depend on version of Salt

---

salt/mirror/minima.yaml
salt/repos/repos.d/Devel_Galaxy_Manager_Head.repo
salt/repos/repos.d/Leap-SUSE-Manager-Proxy-Head-x86_64-Pool.repo
salt/repos/repos.d/SUSE-Manager-Head-x86_64-Pool.repo
salt/repos/repos.d/SUSE-Manager-Proxy-Head-x86_64-Pool.repo
salt/repos/repos.d/Uyuni-Master-x86_64-Pool.repo
salt/repos/repos.d/Uyuni-Proxy-Master-x86_64-Pool.repo
salt/repos/repos.d/systemsmanagement_Uyuni_Master.repo
salt/repos/suse_manager_proxy.sls
salt/repos/suse_manager_server.sls
salt/suse_manager_proxy/init.sls
salt/suse_manager_server/init.sls

This also required using patterns from systemsmanagement:Uyuni:Master

Use Uyuni repositories for openSUSE Leap

---

salt/repos/default.sls
salt/repos/repos.d/Devel_Galaxy_Manager_3.1_RES-Manager-Tools-7-x86_64.repo
salt/repos/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo

Julio explained to me that 3.1-nightly is supposed to use 3.2-nightly tools

Reverting last two commits

---

modules/libvirt/base/main.tf

Wait for network to be created, if any.

Added dependency to additional network

---

salt/grafana/init.sls
salt/mirror/init.sls

Upgrade to Grafana 5.2.2

---

modules/libvirt/host/main.tf

not a full revert of cloudinit, but enough to determine whether this would resolve the problem.

Commenting out because of the infinite loop waiting for cloudinit_disk

---

modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/pxe_boot/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/openstack/base/main.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager_proxy/main.tf
salt/mirror/minima.yaml
salt/repos/default.sls
salt/repos/repos.d/SLE-12-SP4-x86_64-Pool.repo
salt/repos/repos.d/SLE-12-SP4-x86_64-Test-Update.repo
salt/repos/repos.d/SLE-12-SP4-x86_64-Update.repo
salt/repos/repos.d/SUSE-Manager-3.2-x86_64-Pool.repo
salt/repos/repos.d/filebeat.repo
salt/repos/repos.d/systemsmanagement-sumaform-tools.repo
salt/suse_manager_server/apparmor.d/usr.bin.cobblerd

This PR adds the repos for SLE 12 SP4.

Introducing SLE 12 SP4

---

salt/suse_manager_server/tomcat.sls

Apply hack for bsc1119213 only for SLE

---

main.tf.libvirt-testsuite.example
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/openstack/controller/main.tf
modules/openstack/controller/variables.tf
salt/controller/bashrc
salt/repos/default.sls

Adds the necessary bits to be able to use an Ubuntu minion with the test suite.

Support for Ubuntu minions in the test suite

---

salt/suse_manager_server/download_ubuntu_repo.sh
salt/suse_manager_server/testsuite.sls

Mirrors the Ubuntu repo needed for the testsuite.

Mirror test Ubuntu repo on the server

---

salt/default/avahi.sls

Fixes the `require` statements in `avahi.sls`

Fix avahi state requisites

---

firewalld_public.xml
salt/suse_manager_server/firewall.sls

On SLE 15, SuSEfirewall2 has been replaced by firewalld, handle this case in the salt state.

Fix firewall setup for SLE 15

---

main.tf.libvirt-testsuite.example
main.tf.openstack-testsuite.example

Not having this vital information can waste a lot of your time :)
Since I do not have permissions, I forked the repo for this trivial PR.

fix documentation URL for github credentials

---

salt/suse_manager_server/testsuite.sls

wget was included in a bunch of package installation.
Add new dependency name

fix package dependency

---

modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf

Not sure why it does not exist, but it should be possible to give the controller more power.

add vcpu option for the controller

---

salt/minion/testsuite.sls

[WIP] Feat: remove update-notifier-common for Ubuntu

---

salt/minion/testsuite.sls
salt/repos/testsuite.sls

Disable apt-daily.timer in Ubuntu minions for testsuite

---

salt/repos/testsuite.sls

We'll work in an experimental branch, it would avoid "polluting" master...
We'll do a valid PR once we have a working solution.

Reverting changes to daily apt services for now

---

modules/libvirt/pxe_boot/variables.tf

Fixes: https://github.com/SUSE/spacewalk/issues/6634
@Bischoff Is this what we need?

Start PXE boot with 1GB

---

modules/libvirt/base/main.tf

```
ebischoff@ix64ph1078:~> virsh net-list
Nom                  État      Démarrage automatique Persistent
----------------------------------------------------------
ebi2-private         actif      no            yes            <-- before
ebi5-private         actif      yes           yes            <-- after
```

Let additional network restart at host reboot

---

modules/libvirt/client/variables.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/variables.tf
modules/openstack/base/variables.tf
modules/openstack/client/variables.tf
modules/openstack/host/variables.tf
modules/openstack/minion/variables.tf

Mostly cosmetic changes to advertise sles12sp4's existence.
It's not advertised yet in the main.tf templates (maybe it should).

Make SLES 12 SP4 a first class citizen

---

salt/suse_manager_server/postgres-exporter
salt/suse_manager_server/prometheus.sls

Requires that https://build.opensuse.org/request/show/697856 is accepted first.

Fix monitoring package and service file names

---

salt/repos/repos.d/SLE-15-SP1-x86_64-Pool.repo
salt/repos/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Update.repo
salt/repos/repos.d/SLE-Module-Python2-SLE-15-SP1-x86_64-Pool.repo
salt/repos/repos.d/SLE-Module-Server-Applications-SLE-15-SP1-x86_64-Pool.repo
salt/repos/repos.d/SLE-Module-Web-Scripting-SLE-15-SP1-x86_64-Pool.repo

A few minor repositories fixes for SLE 15 and SLE 15 SP1

Repo fixes

---

modules/libvirt/pts/main.tf
modules/openstack/pts/main.tf
salt/suse_manager_server/pts/run-pts.py

Fix the PTS:
- Onboard original minion before onboarding the evil-minions

Onboard original minion before onboarding the evil-minions

---

salt/mirror/minima.yaml
salt/suse_manager_server/taskomatic.sls

Tiny fixes:
* Add sumaform tools for SLES 15SP1 to minima config
* Fix taskomatic debug options after tanuki drop

Misc fixes

---

salt/suse_manager_server/taskomatic.sls

Fix static IP mistakenly introduced by PR #538.

taskomatic: fix remaining IP

---

modules/libvirt/mirror/main.tf
modules/openstack/mirror/main.tf
salt/mirror/init.sls
salt/mirror/refresh_scc_data.py

Update the mirror image to Leap 15.0. But may be we want it 15.1 now?

Leap 151 mirror

---

salt/mirror/init.sls
salt/mirror/minima.yaml

Update minima to 0.8 to be able to sync the ubuntu tools.

Synchronize the Ubuntu Manager tools

---

modules/libvirt/host/main.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/virthost/main.tf

rename `xsl` variable to `xslt` as requested by @moio.

Xsl rename

---

salt/controller/bashrc

change variable name

---

modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/openstack/controller/main.tf
modules/openstack/controller/variables.tf
salt/client/testsuite.sls
salt/controller/bashrc
salt/repos/default.sls

This PR adds variables for clients needed by QAM.

Support for QAM clients

---

salt/repos/default.sls
salt/repos/repos.d/systemsmanagement_Uyuni_Master_CentOS7-Uyuni-Client-Tools.repo
salt/repos/repos.d/systemsmanagement_Uyuni_Stable_CentOS7-Uyuni-Client-Tools.repo

Latest PR added Uyuni development tools for openSUSE, this one does the same for CentOS 7.

Uyuni: provide a development tools repository for RH

---

salt/repos/default.sls

Product name corrected

---

salt/repos/default.sls

Missing default value for grains.get('product')

---

salt/repos/minion.sls

Testsuite stable minion fix

---

salt/repos/minion.sls

Minion: only add the container module for SLES

---

salt/repos/testsuite.sls

Revert something that is okay in master, but not in this branch.

Reverting abusive backport

---

salt/suse_manager_server/testsuite.sls

Follow-up of previous PR, where I changed `Pool`, but forgot `Updates`.

Don't use mirrors for updates either

---

salt/repos/repos.d/Test-Packages_Pool.list
salt/repos/repos.d/Test-Packages_Pool.repo
salt/suse_manager_server/testsuite.sls

Changing fake repos once again to work around problem with mirrors

Changed fake repo names again to work around problems with mirrors

---

salt/mirror/minima.yaml
salt/repos/testsuite.sls
salt/suse_manager_server/testsuite.sls

Forward port of latest changes in the stable branch.

New location for fake packages + corresponding key

---

README_ADVANCED.md

Cherry pick of latest Silvio's commit
Ping @srbarrios @mcalmer: we can't maintain this other "mirror" branch forever. What about merging it too into master?

README_ADVANCED: document auto_accept

---

modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/minionssh/main.tf
salt/mirror/mirror.sh
salt/repos/default.sls
salt/suse_manager_server/download_ubuntu_repo.sh

Mirror also images. They apear under the same path as the original.

Mirror and testsuite assorted fixes

---

README_ADVANCED.md
modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/controller/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/virthost/variables.tf
salt/mirror/minima.yaml
salt/repos/suse_manager_proxy.sls
salt/repos/suse_manager_server.sls
salt/repos/tools.sls
salt/suse_manager_proxy/init.sls

- Base Head on 4.1
- Add suport for SLE15SP2
- Preadd support for future 4.1 stable
Fixes https://github.com/SUSE/spacewalk/issues/10009

Base Head on 4.1, add suport for SLE15SP2

---

modules/libvirt/controller/main.tf
salt/controller/init.sls

Revert openSUSE 15.1 controller

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

- Refactor of the available hosts with the option to define additional repositories for each host.
- Remove variable proxy and use available hosts instead

0.12.additional repos for each server

---

modules/cucumber_testsuite/main.tf

Adds a setting to change the image per host (on hosts for which it makes sense to configure an image)

Add per-host image setting

---

modules/cucumber_testsuite/main.tf

change the way image variable in cucumber test suite is defined.

0.12.image var refractory

---

salt/mirror/minima.yaml

Fix the minima config for 15 SP2 repos.

Fix mirror for 15SP2

---

salt/repos/virthost.sls

Add SLE 15 SP2 Server Application repositories on virtual hosts.

Add 15SP2 Server Application repositories for virthost

---

modules/cucumber_testsuite/variables.tf

Add **SLES15SP2** image for the cucumber_testsuite module.

Add SLES15SP2 image for cucumber_testsuite

---

salt/controller/init.sls

Upgrade the cucumber html reporter to 5.1.0, which includes an improvement I made to filter passed features https://github.com/gkushang/cucumber-html-reporter/pull/198

Upgrade the cucumber html reporter to 5.1.0

---

README_TESTING.md

This PR adds documentation for existing and new test suite options.

Documentation for more test suite options

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
modules/libvirt/controller/variables.tf

Bridge code for new variables in new wrapper

Missing glue in the new test suite module

---

modules/libvirt/controller/main.tf
salt/controller/bashrc

Missing grains

---

README_TESTING.md

This PR adds doc for http proxy option.

More test suite advanced options

---

modules/cucumber_testsuite/main.tf

Ebischoff arbitrary images and names

---

salt/mirror/minima.yaml

Add repositories need by the test suite to minima configuration file.

Mirror: add repos needed by testsuite

---

salt/controller/init.sls

I would like to change the CSS of the report, which I doubt it will be approved in the official repo but it will help us to have better visibility in a real report with our kind of server log outputs.

Adding a style change in the reporter

---

README_TESTING.md

- README_TESTING.md: Rewrite a sentence to avoid repeating **once** word.
It's read just 2 lines above that we cannot repeat the core features; I think we don't need to say it again here.

- README_TESTING.md: Rewrite a sentence

---

README.md
backend_modules/ssh/README.md
backend_modules/ssh/base/main.tf
backend_modules/ssh/base/variables.tf
backend_modules/ssh/base/versions.tf
backend_modules/ssh/host/main.tf
backend_modules/ssh/host/variables.tf
backend_modules/ssh/host/versions.tf
backend_modules/ssh/volume/main.tf
backend_modules/ssh/volume/variables.tf
backend_modules/ssh/volume/versions.tf
main.tf.ssh.example
salt/first_deployment_highstate.sh
salt/highstate.sh

Add ssh backend support for provisioning existing servers
https://github.com/SUSE/spacewalk/issues/10489

ssh backend support (provision)

---

README_ADVANCED.md

Update README_ADVANCED.md examples with terraform 0.12 syntax

update README_ADVANCED.md example with 0.12 syntax

---

salt/mirror/minima.yaml

Add the nvidia repositories for SLE15SP1 and SP2

nvidia repositories for SLE15SP1 and SP2

---

salt/default/avahi.sls

Fixed salt sate for apparmor

---

backend_modules/libvirt/host/main.tf

Allow remote SPICE connections (fixes #706)

---

README_TESTING.md

It updates the README_TESTING.md instruction as the current one will not work.

Update instruction to run single Cucumber feature

---

backend_modules/null/base/variables.tf
modules/base/variables.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/server/main.tf
modules/virthost/variables.tf

Change the rest of mentions to sles15sp2 to sles15spo

---

modules/controller/main.tf
modules/controller/variables.tf

Adds variables in the controller for centos 8 and ubuntu 20.04 minion and ssh minion

Add new variables for centos 8 and ubuntu 20.04 in the controller

---

salt/mirror/minima.yaml

Add the Desktop Apps product and repos to the mirror. Required by the devel tools product.

Add the Desktop Apps product and repos to the mirror

---

salt/mirror/init.sls

https://github.com/uyuni-project/minima/commit/0841e32739f725f11c44d4402d98d0518b32bc5f
https://github.com/uyuni-project/minima/commit/15b81ffc90e562f1c2ae55fc4500c70670a6b426

Update minima with bugfixes

---

modules/proxy/main.tf
modules/server/main.tf
salt/mirror/minima.yaml

Change Uyuni Stable to Leap 15.2

Change Uyuni Stable to Leap 15.2

---

salt/mirror/minima.yaml

This PR enable minima to sync "SLE-Module-Containers15" modules for SLE15SP2

minima: sync "SLE-Module-Containers15" modules for SLE15SP2

---

backend_modules/libvirt/host/user_data.yaml

add missing repo to get qemu guest agent on SLES 15 SP1 official image

---

backend_modules/aws/README.md

Add a missing preposition at:
- backend_modules/aws/README.md

Add missing preposition

---

salt/controller/init.sls

Minor upgrade of https://www.npmjs.com/package/cucumber-html-reporter
This includes a proposal from @lkotek plus a small visual change.
- https://github.com/gkushang/cucumber-html-reporter/commit/6b6e75aa0b0fc8bbdcd817f6ed30d20f4cd728ca
- https://github.com/gkushang/cucumber-html-reporter/commit/789e8447f7a347fad1493376be2958e4b0db8c3a

Upgrade cucumber html reporter

---

salt/controller/init.sls

Work around problems with github clone

---

salt/controller/init.sls

Address last case for the github clone problem.

Copy in all cases

---

salt/controller/init.sls

This PR tries a `git clone` first, and if that fails, switches to `curl`

Fallback mechanism

---

salt/controller/init.sls

This PR removes the fallback mechanism we had during a while.

Problem with git clone seems gone for good

---

backend_modules/libvirt/host/user_data.yaml

This PR aligns SLES 15 SP0 and SLES 15 SP2 in terms of repositories

WIP: Server applications module is needed for QEMU guest agent

---

README_ADVANCED.md
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
modules/base/variables.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/server/main.tf
modules/virthost/variables.tf
salt/mirror/init.sls
salt/mirror/minima.yaml
salt/repos/default.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/repos/tools.sls
salt/repos/virthost.sls

Add support for SUSE Manager 4.2 (HEAD) and SLES15SP3

Add support for SUSE Manager 4.2 (HEAD) and SLES15SP3

---

salt/mirror/minima.yaml
salt/repos/proxy.sls
salt/repos/server.sls

Fix a previous commit: ensure 4.1 branch uses SLE 15 SP2.

4.1 uses SLE 15 SP2

---

README.md

Signed-off-by: Ricardo Marques <rimarques@suse.com>
This PR adds the `Tumbleweed` repo to the list of repos in the README.

Add Tumbleweed to the list of repos in README

---

salt/mirror/minima.yaml

PR adds SLE**D**15SP2 product to minima mirror.
Do not merge before https://github.com/SUSE/spacewalk/pull/13327, please.
https://github.com/SUSE/spacewalk/issues/13284

Add SLED15SP2 product to minima mirror

---

backend_modules/libvirt/base/main.tf

Title says it all. Otherwise the deployment fails.

SLE15SP3 Alpha4 image not available anymore, changing to Beta

---

TROUBLESHOOTING.md

Some tips when troubleshooting Avahi from my local to a deployed VM.

Extra checks when configuring Avahi

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

PR adds set of clients necessary for retail in case of QAM.
This **must** be merged before https://github.com/SUSE/susemanager-ci/pull/172.

Adding QAM clients necessary for retail

---

backend_modules/libvirt/base/main.tf

Update sles15sp3o image URL

---

backend_modules/libvirt/base/main.tf

Update image for centos 8 to latest.

Update image for centos 8

---

backend_modules/libvirt/base/main.tf

Update sles15sp1o image with valid url, it was changed apparently.

Update sles15sp1o image with valid url

---

backend_modules/libvirt/host/user_data.yaml

Add workaround for sles15o image to make the image able to deploy

Add workaround for sles15o image

---

salt/controller/init.sls

This code removes the creation of a file by sumaform that is not later used by the test suite.
(see issue SUSE/spacewalk#3464)

Removing dead code

---

backend_modules/libvirt/host/user_data.yaml

Remove gpg key hack for sles 15.
Also changes repo name to force correct repository order.

remove gpg key hack and change repo name because or order

---

backend_modules/aws/host/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/libvirt/host/user_data.yaml
salt/client/testsuite.sls
salt/default/avahi.sls
salt/default/minimal.sls
salt/proxy/init.sls
salt/repos/additional.sls
salt/repos/default.sls
salt/repos/init.sls
salt/repos/minion.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/repos/testsuite.sls
salt/repos/tools.sls
salt/repos/virthost.sls
salt/virthost/init.sls

Cosmetical: currently, we have `WORKAROUND`, `Workaround`, `workaround`, `work around`, and `HACK`.
Use `WORKAROUND` in all caps:
- make it more noticeable
- align with test suite
- make grepping easier
Also standardize `bsc#` and `github#` shortcuts. Sometimes it was not indicated which github repository it was all about.

Shout about workarounds ;-)

---

salt/server/init.sls

Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

Add workaround state to server states

---

backend_modules/libvirt/base/main.tf

It updates again sles15sp3o image URL.
- backend_modules/libvirt/base/main.tf (sles15sp3o):
Update URL.

Update again sles15sp3o image URL

---

README_ADVANCED.md
backend_modules/null/base/variables.tf
backend_modules/null/host/variables.tf
modules/base/variables.tf
modules/client/variables.tf
modules/cucumber_testsuite/variables.tf
modules/host/variables.tf
modules/minion/variables.tf
modules/pxe_boot/variables.tf
modules/sshminion/variables.tf

This PR:
* adds SLES12 SP5 image
* does various updates to image lists

Added sles12sp5 image

---

backend_modules/libvirt/base/main.tf

Update sles15sp3o image: `SLE-15-SP3-JeOS-PublicBeta` --> `SLE-15-SP3-JeOS-PublicRC`.

Update sles15sp3o image

---

README_TESTING.md
modules/cucumber_testsuite/main.tf

add the possibility to specify additional packages which should be installed during setup time.

support additional_packages in cucumber_testsuite module

---

salt/client/testsuite.sls

See #834.
1) we should not hide product bugs with sumaform hacks - I prefer it to fail in the test suite, we create a bug, developers fix the bug, etc.
2) the hack did not work anymore anyway :smile_cat: .

Remove hack for sumaform issue #834

---

salt/mirror/minima.yaml
salt/repos/proxy.sls
salt/repos/server.sls

Server devel repo 15.3

---

backend_modules/azure/host/user_data.yaml

Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

update azure to 15.3

---

salt/default/grub.sls
salt/default/init.sls

better version of #888 - Work around initrd issue in sle11sp4
still not perfect though, and should be done at image creation time, really

HACK: work around initrd issue in sle11sp4

---

modules/controller/main.tf
modules/controller/variables.tf

Add 12sp5 buildhost and terminal in the controller

Add 12sp5 buildhost and terminal

---

salt/repos/default.sls

Fix os_ltss_repo for SLES11-SP4

Fix os_ltss_repo for SLES11-SP4

---

backend_modules/libvirt/base/main.tf

Update sles15sp3o image to GM

---

salt/repos/default.sls

Fixes https://github.com/uyuni-project/sumaform/issues/909

Remove moving target for 15.3

---

modules/virthost/variables.tf

Add  workaround for failures downloading opensuse153o

Add workaround for download of opensuse153o

---

README_TESTING.md

more doc about how to run scenarios

Basic cucumber knowledge

---

backend_modules/aws/host/user_data.yaml

Fix variable issue for aws

---

salt/server/testsuite.sls

Fix format issue, using double quotes, in debian updates

Fix format issue, using double quotes, in debian updates

---

salt/virthost/init.sls

Add missing tuned and irqbalance packages to virthost

---

salt/server/testsuite.sls

Add a statement only require repo on versions it exists

Add a statement only require repo on versions it exists

---

backend_modules/libvirt/host/user_data.yaml

When changing the image for PRs to a custom one, we also need to change
the user data

Fix user data for pr image

---

backend_modules/libvirt/host/user_data.yaml

Fix user data syntax

---

salt/mirror/etc/minima.yaml

This PR adds our new "Basesystem Overlay" testing repositories to the `minima.yaml` file in order to sync those new repos in our mirrors.

Add "Basesystem Overlay" testing repo to minima: 4.1, 4.2 and Head

---

backend_modules/aws/base/main.tf

Add sles15sp3o AMI to AWS

---

backend_modules/libvirt/host/main.tf

Fix issue with terraform deployment cause by change in `output configuration`

REmove ip addrs from backend/libvirt/host/main output

---

.gitignore
backend_modules/aws/base/versions.tf
backend_modules/aws/host/versions.tf
backend_modules/aws/network/versions.tf
backend_modules/azure/base/versions.tf
backend_modules/azure/host/versions.tf
backend_modules/azure/network/versions.tf
backend_modules/libvirt/base/versions.tf
backend_modules/libvirt/host/versions.tf
backend_modules/null/base/versions.tf
backend_modules/null/host/versions.tf
backend_modules/ssh/base/versions.tf
backend_modules/ssh/host/versions.tf
modules/base/versions.tf
modules/client/versions.tf
modules/controller/versions.tf
modules/cucumber_testsuite/versions.tf
modules/grafana/versions.tf
modules/host/versions.tf
modules/locust/versions.tf
modules/minion/versions.tf
modules/mirror/versions.tf
modules/proxy/versions.tf
modules/pxe_boot/versions.tf
modules/server/versions.tf
modules/sshminion/versions.tf
modules/virthost/versions.tf

Add support for the usage of terraform 1.0.10

support for terraform 1.0.10

---

backend_modules/libvirt/host/user_data.yaml

Install "venv-salt-minion" in all images for Uyuni Master

---

backend_modules/libvirt/host/user_data.yaml

Use proper syntax for logic in user_data.yaml

---

backend_modules/libvirt/host/main.tf
backend_modules/null/base/variables.tf

Pass "product_version" to user_data template

---

backend_modules/libvirt/host/main.tf
backend_modules/null/base/variables.tf
modules/base/main.tf

Extra fixes for "product_version" to "user_data" template

---

backend_modules/libvirt/host/main.tf
backend_modules/null/base/variables.tf
backend_modules/null/host/main.tf
backend_modules/null/host/variables.tf
modules/base/main.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

Make 'install_salt_bundle' parameter to be a host attribute

---

backend_modules/libvirt/host/main.tf
salt/post_provisioning_cleanup.sh

Add "post_provisioning_cleanup" stage to cleanup Salt packages when using Bundle

---

README_ADVANCED.md
modules/registry/main.tf
modules/registry/variables.tf
modules/registry/versions.tf
salt/registry/init.sls
salt/top.sls

It adds an utility VM to run a container registry.

Add a container registry utility module

---

salt/server/testsuite.sls

Add comment about temporary workaround

---

salt/default/grub.sls

Only a change in comments
See also uyuni-project/uyuni#4519

SLE 11 SP4 hack needs to be made permanent :-(

---

backend_modules/libvirt/host/user_data.yaml

On Debian 11, take into account the `install_salt_bundle` option

Take into account option install_salt_bundle

---

backend_modules/libvirt/base/main.tf
salt/mirror/etc/mirror-images.conf

Mirror SLE-15-SP4-JeOS-Beta2
Related PR https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/472/diffs

Mirror SLE-15-SP4-JeOS-Beta2

---

salt/repos/default.sls

Fix 43beta os movingtarget repo

Fix 43-beta os movingtarget repo

---

backend_modules/libvirt/base/main.tf
salt/mirror/etc/mirror-images.conf

Use SLE15SP4 Beta3 images, as Beta2 images are gone

Use SLE15SP4 Beta3 images, as Beta2 images are gone

---

salt/server/master-custom.conf
salt/server/salt_master.sls

put everything into debug log mode

debug logging for master and api

---

TROUBLESHOOTING.md

This will add a new troubleshooting entry to resolve problems with the Terraform dependency lock file.

[docs] Add troubleshooting entry

---

CONTRIBUTING.md
README_ADVANCED.md
backend_modules/libvirt/base/main.tf
salt/mirror/etc/mirror-images.conf
salt/server/testsuite.sls

Use new project names as things were moved from `moio` to `uyuni-project`

images and other projects were moved from moio to uyuni-project

---

README_TESTING.md

Add notes about Salt Bundle in README_TESTING

---

salt/controller/init.sls

Adds the postgresql package to the controller for the database tests being added to the testsuite

QA: Add postgresql package to controller for DB tests

---

salt/controller/init.sls

Adds the postgresql-devel package instead of just postgresql

QA: Add postgresql-devel package to controller

---

modules/proxy/main.tf
modules/proxy/variables.tf
salt/proxy/init.sls
salt/repos/proxy.sls

install needed packages for containerized proxy

initial install for containerized proxy

---

salt/repos/proxy.sls

Correct issue related to ca repository when deploying Proxy prepared for containers.

correct usage of ca_repo for proxy container

---

backend_modules/azure/base/main.tf
backend_modules/azure/host/user_data.yaml
salt/scc/proxy.sls
salt/scc/server.sls

Add support to ubuntu, redhat, centos and Suse images
Update user_data to be able to install salt on this images. 
For SCC support, add a clean. It was failing with SLES15SPX images.

[AZURE] Update image references and user data related to this images

---

salt/proxy/init.sls

follow-up PR of: https://github.com/uyuni-project/sumaform/pull/1099
Define http in the download URL.

define http method for tool repository

---

salt/proxy/init.sls

follow-up of https://github.com/uyuni-project/sumaform/pull/1100
Correct syntax
Remove requires, which was forcing a circular dependency because of the repository name.

Proxy repo recursive

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml

see https://github.com/SUSE/spacewalk/issues/17984

add opensuse154-ci-pr

---

modules/proxy/main.tf
modules/server/main.tf

title says all.
implements: https://github.com/SUSE/spacewalk/issues/17543

update base image for leap 15.4 in uyuni pr deployment

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml

Add support for oracle linux 8
implements: https://github.com/SUSE/spacewalk/issues/18065

add support for oracle linux 8

---

backend_modules/libvirt/base/main.tf

Update image path for sles15sp4 on libvirt

Update sles15sp4 image for libvirt

---

modules/proxy/main.tf
modules/server/main.tf
salt/mirror/etc/minima.yaml

Deploy uyuni with leap 15.4 for stable versions
Implements: https://github.com/SUSE/spacewalk/issues/17543
follow-up of: https://github.com/uyuni-project/sumaform/pull/1104

uyuni release with leap 15.4

---

salt/mirror/etc/minima.yaml
salt/repos/default.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/repos/virthost.sls

Remove moving target now that 15sp4 is out, it's causing issues in BV

Remove moving target now that 15sp4 is out

---

modules/cucumber_testsuite/main.tf

This will update the images in the cucumber_testsuite module

Update cucumber_testsuite module images

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

This will
- add SLE Micro 5.2 support

Add SLE Micro 5.2

---

backend_modules/null/base/variables.tf
modules/cucumber_testsuite/variables.tf

Add Rocky 8 to default and cucumber module image list.

Add Rocky 8 to image list

---

backend_modules/null/base/variables.tf
modules/cucumber_testsuite/variables.tf

title says it all
follow-up of: https://github.com/uyuni-project/sumaform/issues/1146

remove eol images from default download list

---

backend_modules/aws/network/main.tf

Fix variable to create additional public subnet and route

Create additionnal subnet and route only if RDS is deployed

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/network_config.yaml
backend_modules/libvirt/host/user_data.yaml
salt/mirror/etc/minima.yaml
salt/mirror/etc/mirror-images.conf

The title says it all.
Implementation of: https://github.com/SUSE/spacewalk/issues/18280

Add support for ubuntu 2204

---

salt/repos/default.sls

Solves deployment problems on rocky8 with head product.
FIX:: https://github.com/SUSE/spacewalk/issues/18784

correct deployment for rocky linux 8 on non uyuni environment

---

modules/controller/variables.tf

fix: Add Ubuntu 22.04 controller variables

---

README_TESTING.md
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc

New variable in main.tf:
```
custom_download_endpoint = "ftp://minima-mirror.mgr.suse.de:445"
```

New variable to set up custom download endpoint

---

README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc

Makes custom endpoint both optional and customizable from the main.tf file.
Unlike previous PR, this one was tested :blush: .

New variable to set up custom download endpoint (2)

---

backend_modules/aws/host/main.tf

optimize aws instance types

---

backend_modules/aws/host/main.tf
salt/default/init.sls
salt/default/sshd.sls
salt/repos/disable_local.sls
salt/repos/init.sls

Workaround terraform error

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
main.tf.uyuni.example
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/mirror/etc/apt-mirror.list
salt/mirror/etc/minima.yaml

It seems we still missing some code pieces to support Ubuntu 22.04, this PR also fix some typo introduced in an older PR.

Adding missing support for Ubuntu 22.04

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

switch from 15.3 to 15.4 for openSUSE ARM minion

Use openSUSE 15.4 for ARM

---

backend_modules/aws/README.md
backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/azure/base/main.tf
backend_modules/null/host/variables.tf
modules/build_host/variables.tf
modules/client/variables.tf
modules/controller/main.tf
modules/minion/variables.tf
modules/mirror/variables.tf
modules/pxe_boot/variables.tf
modules/sshminion/variables.tf
modules/virthost/variables.tf

Seems opensuse152o was removed from AWS. Try to remove the image and use something different

Aws without os152

---

salt/proxy/init.sls

Removing unnecessary dependencies for pod proxy

Removing unnecessary dependencies for pod proxy

---

salt/proxy/init.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/server/testsuite.sls

Containerized proxy services installed in 4.3 and Uyuni PR tests

Containerized proxy services installed in 4.3-nightly and Uyuni PR tests

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf

Remove old amis
Update ubuntu owner

Remove old amis, update ubuntu 2204 ami

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf

add rocky 8 ami

---

salt/repos/proxy.sls
salt/repos/server.sls

Upgrade head default repository from 4.3 to 4.4

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

Add configuration for openSUSE 15.4 ARM SSH minion

Add configuration for openSUSE 15.4 ARM SSH minion

---

salt/proxy/init.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/server/testsuite.sls

Containerized proxy services installed in 4.3-*, uyuni-* and head test environments

Containerized proxy services installed in 4.3-*, uyuni-* and head test environments

---

backend_modules/libvirt/host/user_data.yaml

Permit root login on Rocky 9

---

salt/proxy/init.sls
salt/repos/proxy.sls

Add packages for containerized proxy on 4.3 and uyuni proxies

Container proxy in 43 and prtests

---

salt/default/locale.sls

Fix of previous PR
I mixed os_family and osfullname

My bad, Rocky has os_family RedHat

---

modules/controller/main.tf
modules/controller/variables.tf

Add Alma and Oracle to controller options

Add Alma and Oracle to controller options

---

salt/scc/proxy.sls

To support proxy containerization, we need the module container activated on proxy.

Scc module container proxy 43

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml

Add debian 11 support to AWS deployment

Add debian 11 support to AWS deployment

---

backend_modules/aws/base/ami.tf

Only current images changed. The very old once are still only listed under the old owner ID:

SUSE AMIs in AWS changed the owner to the marketplace account

---

salt/first_deployment_highstate.sh

Another changes similar to https://github.com/uyuni-project/sumaform/pull/1249 , but this one OpenSUSE (hopefully with this new macro we can cover most of the future scenario)

fix OpenSUSE Leap Micro 5.3 and OpenSUSE microOS provisioner

---

modules/controller/variables.tf
modules/cucumber_testsuite/variables.tf

I forgot to add a default parameter in https://github.com/uyuni-project/sumaform/pull/1229.

Fixup for nested VMs (#1229)

---

salt/virthost/init.sls

Revert virthost change regarding `hvm_disk_image`

---

salt/virthost/init.sls

Avahi and mDNS cause trouble in our CI.

Remove avahi from nested VM

---

salt/server/testsuite.sls

Reverts uyuni-project/sumaform#1283
Elements are missing so this can work. Reverting in the meantime.

Revert "QE: Enable testing_overlay repo for prs CI"

---

salt/mirror/etc/minimum_repositories_testsuite.yaml

Add res repository to repo list for AWS test suite

Add res 8 client tool repo to mirror list

---

backend_modules/libvirt/host/user_data.yaml

Circumvent the new upstream changes of the rmt script until it will be fixed.
See https://github.com/SUSE/rmt/issues/994
Split out of https://github.com/uyuni-project/sumaform/pull/1287

Fixes for the RMT script

---

salt/default/minimal.sls
salt/default/time.sls
salt/repos/init.sls
salt/repos/testsuite.sls

This will fix several issues that occur during the deployment of SLE Micro 5.x.
Split out of https://github.com/uyuni-project/sumaform/pull/1287

Fixes for transactional systems

---

salt/server/testsuite.sls

Make 4.2 testsuite to use Salt Bundle everywhere

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/default.sls

Just use default priority for tools repos.
Only "tools_additional_repo" uses priotiry 98

use default repo priority for tools_pool and tools_updates repo

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/default.sls

If there was a point to explicitely give 99 priority in the cloud-init part, please just ignore this PR.
Otherwise I find it cleaner like this.

99 is default priority, don't specify it

---

backend_modules/libvirt/host/user_data.yaml
modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

Add openSUSE 15.5 for Build Validation (only ARM architecture)

Add openSUSE 15.5

---

backend_modules/libvirt/base/main.tf

They renamed JeOS to Minimal

---

modules/cucumber_testsuite/main.tf

Revert using counts for everything non-server in cucumber module

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

Avoid containerized_server variable / module conflict

---

modules/server_containerized/main.tf

This module is a copy/paste of the server module and some variables are not yet implemented, some could also be dropped, work in-progress.

TODO for server_containerized module

---

modules/cucumber_testsuite/main.tf
modules/server/main.tf
modules/server/variables.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server/rhn.sls
salt/server_containerized/rhn.sls

Create a specific variable to disable auto generate boostrap repo

Create a grains variable to disable auto generate bootstrap repo

---

backend_modules/libvirt/base/main.tf

Leap 15.4 JeOS image was renamed to Minimal-VM

---

modules/virthost/variables.tf

we need to rename the default image values as well.
In addition to https://github.com/uyuni-project/sumaform/pull/1360

rename default image as well

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml

Add openSUSE Leap 15.5 PR image

---

salt/server/taskomatic.sls
salt/server/tomcat.sls

enable remote debugging without specifying address

enable remote debugging without specifying address

---

salt/server_containerized/testsuite.sls

Fix dangling `uyunictl_symlink` requisites after the switch to uyuni-tools RPM.

Fix uyunictl_symlink requisites

---

salt/server_containerized/testsuite.sls

Container: handle salt-ssh older in testing overlay than in image

---

salt/server/taskomatic.sls
salt/server/tomcat.sls

Fix indentation in log4j2.xml

---

salt/server_containerized/install_uyuniadm.sls

Make uyuniadm more verbose to help debugging

---

modules/controller/main.tf

Update controller to Leap 15.5

Update controller to leap 15.5

---

salt/server_containerized/install_uyuniadm.sls

`-v` is going to get removed from `uyuniadm` in favor of `--logLevel` which is already in.

Change -v to --logLevel=debug on uyuniadm

---

salt/server_containerized/testsuite.sls

Change -v to --logLevel=debug on uyunictl

---

salt/server_containerized/uyuniadm.yaml

container: use debug parameter in uyuniadm config

---

salt/server_containerized/install_uyuniadm.sls
salt/server_containerized/uyuniadm.yaml

Adapt to https://github.com/uyuni-project/uyuni-tools/pull/53

Subcommands

---

salt/server/spacewalk-search.sls
salt/server/tomcat.sls
salt/server_containerized/uyuniadm.yaml

* Really enable the search server to listen for JDWP on port 8002 (requries https://github.com/uyuni-project/uyuni/pull/7587).
* Change tomcat port to 8003 to be consistent with containers setup.

Fix JDWP setup

---

salt/server_containerized/install_common.sls
salt/server_containerized/testsuite.sls

Fix uyuni-tools requires issues

---

salt/server_containerized/uyuniadm.yaml

Required for PR https://github.com/uyuni-project/uyuni-tools/pull/58

Adapt uyuniadm config to new SSL option naming

---

backend_modules/libvirt/host/user_data.yaml

let debian 12 deploy in 4.3.9 build validation

Debian 12 fixes

---

salt/mirror/etc/minima.yaml

Adjust minima mirror definition for Leap 15.5 and server container

---

backend_modules/libvirt/host/user_data.yaml

Follow-up to #1406 and #1409. Switch Debian 12 client tools repo from Master to Stable.

Switch to Debian 12 client tools Stable repo

---

backend_modules/libvirt/base/main.tf

This PR updates the location of SLES 15 SP5 qcow2 image.

Final image for SLE 15 SP5

---

salt/controller/bashrc

Specify the service package of the paygo instances to facilitate the testing.

Specify paygo instance sle service package to facilitate the testing

---

salt/controller/bashrc

Change paygo variable in controller

---

backend_modules/feilong/base/versions.tf
backend_modules/feilong/host/main.tf
backend_modules/feilong/host/versions.tf

This PR takes into account the new `vswitch =` setting.

Added support for s390 virtual switches

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml

sles15sp1 ami doesn't exist anymore.
Also remove not supported image from user_data

Remove obsolete images sles15sp1

---

modules/proxy/main.tf
modules/server/main.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf

use OpenSUSE 15.5 for uyuni master, released and prs

use OpenSUSE 15.5 for uyuni master, released and prs

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
modules/controller/main.tf
modules/controller/variables.tf

PAYGo instance names have been changed. Update those names in controller variables.

Modify new paygo instance name to controller

---

backend_modules/null/host/variables.tf
modules/server/variables.tf
salt/repos/default.sls

Fixes https://github.com/SUSE/spacewalk/issues/23139
This PR adds default  tools repositories for SLE Micro 5.X

QE: Add default Uyuni tools repositories for slemicro5

---

salt/repos/server_containerized.sls

Otherwise, we get an error when trying to install packages from that repo.

Add gpgkey for ContainerUtils build service repo

---

salt/repos/server_containerized.sls

wait 2 seconds, like in salt/virthost/init.sls

fix reboot command

---

backend_modules/aws/README.md
backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
modules/build_host/variables.tf
modules/client/variables.tf
modules/controller/main.tf
modules/cucumber_testsuite/variables.tf
modules/jenkins/variables.tf
modules/minion/variables.tf
modules/mirror/variables.tf
modules/pxe_boot/variables.tf
modules/registry/main.tf
modules/salt_testenv/variables.tf
modules/sshminion/variables.tf
modules/virthost/variables.tf
salt/controller/init.sls

openSUSE 15.4 was removed from AWS already
Start to replace it with 15.5

Change opensuse154o to 155

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

Update to latest SP for s390 - I had forgotten the sumaform part

Now using SLE 15 SP5 images

---

backend_modules/feilong/base/versions.tf
backend_modules/feilong/host/versions.tf

Forgot to bump version number.

Fixed provider version

---

salt/server_containerized/testsuite.sls

Fix galaxy_key_copy state for Head container

---

modules/server_containerized/main.tf
salt/default/init.sls

add sle micro 5.5 to head
https://github.com/SUSE/spacewalk/issues/23081

Change default for head server containerized image

---

salt/repos/proxyHead.sls

fix proxy 5.0 media repo

---

README_ADVANCED.md
modules/cucumber_testsuite/main.tf
modules/server/main.tf
modules/server/variables.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server/init.sls
salt/server/large_deployment.sls
salt/server/large_deployment_tune_tomcat.xslt
salt/server/testsuite.sls
salt/server_containerized/init.sls
salt/server_containerized/large_deployment.sls
salt/server_containerized/large_deployment_tune_tomcat.xslt
salt/server_containerized/testsuite.sls

This PR hopefully solves SUSE/spacewalk#23207
It conforms to https://documentation.suse.com/suma/4.3/en/suse-manager/specialized-guides/large-deployments/tuning.html#_environmental_variables

Tune for large deployments

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/user_data.yaml
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/repos/server_containerized.sls
salt/repos/server_containerizedUyuni.sls
salt/server_containerized/initial_content.sls
salt/server_containerized/install_common.sls
salt/server_containerized/install_mgradm.sls
salt/server_containerized/install_podman.sls
salt/server_containerized/mgradm.yaml
salt/server_containerized/testsuite.sls

Head fixes

---

backend_modules/libvirt/host/main.tf
backend_modules/null/host/main.tf
backend_modules/null/host/variables.tf
modules/host/main.tf
modules/server/main.tf
modules/server/variables.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf

Create a variable to be able to increase the main disk size

Create a variable for the main disk size

---

backend_modules/libvirt/host/user_data.yaml

Fix cloud init slemicro55 suma43

---

backend_modules/libvirt/host/user_data.yaml

This PR makes sure we add `test_repo_rpm_pool` only in the containerized server case

More SLE Micro 5.5 fixes

---

backend_modules/libvirt/host/user_data.yaml

Fix `slemicro55o` conditional in cloud-init.

Fix `slemicro55o` conditional in cloud-init

---

salt/mirror/etc/minima.yaml
salt/repos/default.sls

Add ltss repo for 15sp4 in default repos and in the minima file
Also a small change for making the arch more abstract. I am only changing this for the repos I am concerned now, I don't want to make a massive change.

Add ltss repo for 15sp4

---

salt/server_containerized/initial_content.sls
salt/server_containerized/mgradm.yaml

First user fix

---

backend_modules/feilong/base/versions.tf
backend_modules/feilong/host/versions.tf

Bump Feilong version

---

salt/proxy_containerized/init.sls

Remove ca certificates installaiton

Remove ca certificates installaiton

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/proxy_containerized/main.tf
modules/proxy_containerized/variables.tf
modules/server_containerized/main.tf

Make it possible to configure the disk size in the cucumber_testsuite module

handle main_disk_size for cucumber_testsuite module

---

backend_modules/libvirt/README.md

Update links to SLE docs in libvirt README

---

modules/cucumber_testsuite/main.tf

Try to fix default for main disk size

main disk default is 200

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/main.tf
modules/server_containerized/main.tf
salt/server_containerized/initial_content.sls
salt/server_containerized/install_common.sls
salt/server_containerized/install_k3s.sls
salt/server_containerized/install_mgradm.sls
salt/server_containerized/install_podman.sls
salt/server_containerized/testsuite.sls

In order to support leap micro we need combustion support in the libvirt provider. This requires this pull request:
https://github.com/dmacvicar/terraform-provider-libvirt/pull/1068

Add support for Leap Micro and combustion

---

modules/controller/main.tf

Fixed this error:
Error: failed to render : <template_file>:31,7-24: Unknown variable; There is no variable named "container_runtime".

Align the default value for container_runtime

---

backend_modules/libvirt/host/combustion

Fixes the packages installation for combustion.

Fix dollar escapes in combustion template

---

modules/cucumber_testsuite/main.tf

Support containerized proxy as part of private network

Support containerized proxy as part of private network

---

modules/proxy_containerized/main.tf

Support containerized proxy in private network

Support containerized proxy in private network

---

backend_modules/libvirt/host/combustion

Revert changes on combustion about installing salt bundle

Revert changes on combustion about installing salt bundle

---

backend_modules/libvirt/base/main.tf

Updated the link for the VM image

QE: Change VM link according to new path

---

modules/server/main.tf

Add variable forgotten in commit 73875bf7e .

Fix main disk size

---

modules/cucumber_testsuite/main.tf

Get cucumber_testsuite to actually use container_tag

---

salt/server/additional_disk.sls

Try to make postgres the primary group for the postgres user

make postgres the primary group for the postgres user

---

salt/default/network.sls

Detect the connection name when using NetworkManager

detect the correct NetworkManager connection name

---

backend_modules/libvirt/host/combustion

Partial revert of my expect PR.

Leap Micro does not seem to have expect package

---

backend_modules/libvirt/host/combustion

See title, but add the leap micros to install it.

Add expect and the leap repos on leap micro machines

---

salt/server/large_deployment.sls
salt/server_containerized/large_deployment.sls

Adjusting some values for our Build Validation setup.
In order to perform all bootstraps and smoke tests in parallel.

Large deployment: Tweak the values

---

salt/server_containerized/mgradm.yaml

Adjust change from https://github.com/uyuni-project/uyuni-tools/pull/324

Change mgradm mirrorPath option to mirror

---

README_ADVANCED.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/server/main.tf
modules/server/variables.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/controller/bashrc
salt/server/init.sls

This PR aims to improve how we handle actions related to beta channels, depending if we want them enabled or disabled.

Disable beta channels

---

salt/proxy_containerized/init.sls

configure registry instead of uyuni images location

configure registry instead of uyuni images location

---

salt/proxy_containerized/init.sls

configure registry using config.yaml.
This mean that `/etc/uyuni/config.yaml` should contains:
```
registry: REGISTRY_ADDRESS
````

configure registry using config.yaml

---

salt/proxy_containerized/init.sls

I made Michele do a typo :cry: . This PR fixes it.

Fixed syntax error in state

---

salt/proxy_containerized/init.sls

fix uyuni-tools conf filename

---

backend_modules/libvirt/base/main.tf
salt/mirror/etc/mirror-images.conf

Fix url for 15sp6 image, the previous is no longer valid. I suspect that the GM final url might change later but for now it's valid.

Fix url for 15sp6 image

---

backend_modules/libvirt/base/main.tf

Fix quotes from https://github.com/uyuni-project/sumaform/pull/1601/ sorry for the typo

Fix quotes

---

backend_modules/libvirt/base/main.tf

Fix url again for 15sp6. I have no idea what happened in the meantime, it's invalid now.

Fix url again for 15sp6 

---

modules/proxy_containerized/main.tf
modules/proxy_containerized/variables.tf
salt/proxy_containerized/init.sls

set proxy images tag

---

README_ADVANCED.md

Small change in the readme, about ISS on a server containerized.

Update ISS for server containerized in README_ADVANCED.md

---

backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/user_data.yaml

Password connection is correctly not allowed for opensuse156arm images.
Add the possibility to connect by ssh using root:password

Fix opensuse156 deployment

---

backend_modules/libvirt/host/combustion
salt/default/init.sls
salt/default/network.sls
salt/default/sshd.sls
salt/default/time.sls
salt/default/update.sls
salt/minion/init.sls
salt/minion/testsuite.sls
salt/repos/default.sls
salt/repos/init.sls
salt/repos/testsuite.sls

- Removing wrong basesystem repo
- using a unique repo for client-tools
- filter test packages only for server/proxy
- Fixing sshd.sls issue

Following PR for the integration of SL Micro 6.0

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf

Update rocky8 owner and add rocky9 to ami images.
Also remove sles15sp6 from the ami list ( the image is not available yet and block deployment)

Update rocky owner

---

salt/server_containerized/testsuite.sls

The testsuite install additional packages in the container. auto import all GPG keys of these repos

gpg keys auto import of repos inside of the container

---

modules/proxy_containerized/main.tf

This PR adds support for 5.0 released product

Add support for 5.0 released product

---

modules/proxy/main.tf
modules/proxy_containerized/main.tf

We will have both 5.0-released and 5.0-nightly.
piggyback: change whitespace in traditional proxy

Forgot this possibility

---

salt/minion/init.sls
salt/proxy/init.sls
salt/server/init.sls

Fixup of https://github.com/uyuni-project/sumaform/pull/1631

Fix duplicate Salt SLS IDs

---

salt/minion/init.sls
salt/proxy/init.sls
salt/server/init.sls

Reboot selected systems after the kernel change introduced with https://github.com/uyuni-project/sumaform/pull/1631.

Reboot systems after kernel change

---

backend_modules/libvirt/host/combustion

fix combustion file

---

backend_modules/libvirt/host/combustion

fix combustion

---

salt/repos/additional.sls

additional repos should not be installed with salt, because these are set up by combustion

fix additional repos for SLE Micro / openSUSE Micro

---

backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/user_data.yaml

add additional_repos variable to cloud-init

Add additional_repos to cloud-init

---

backend_modules/aws/base/iam_instance_profile.tf

Fix iam role setup
Follow up on https://github.com/uyuni-project/sumaform/pull/1647

fix iam role setup

---

backend_modules/feilong/host/main.tf
backend_modules/null/host/variables.tf

Add `product_version` for feilong Minions

Add `product_version` for feilong Minions

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/azure/base/main.tf
backend_modules/azure/host/user_data.yaml

Define opensuse156o image for AWS and Azure

Opensuse156o image

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml

drop sles15sp2o from AWS. Image cannot be found anymore

drop sles15sp2o from AWS 

---

salt/repos/proxy.sls

Same as https://github.com/uyuni-project/sumaform/pull/1667 for the proxy

check explicit for proxy_containerized

---

README_ADVANCED.md
modules/dhcp_dns/README.md

Document better the DHCP and DNS server.

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/proxy_containerized50.sls
salt/repos/server_containerized50.sls

Add repos where to get mgradm and mgrpxy

Container repositories for 5.0

---

modules/dhcp_dns/main.tf

Revert the trigger for null resource

Revert trigger for standalone provisioning

---

modules/dhcp_dns/README.md

Explain the problem with RSA keys

More potential problems explained

---

backend_modules/libvirt/host/combustion

Not specifying timeout leads to timeout of 45 seconds

---

backend_modules/libvirt/host/combustion
salt/default/network.sls

Defer DHCP on eth1 to fasten deployment

Defer DHCP on eth1 to fasten deployment

---

salt/controller/init.sls

Temporary workaround until we backport to 5.0
I chose to add a second case, rather than using a OR, so it becomes very visible, and will also be easier to remove later on. Also, it's more flexible.

Temporary workaround until we backport to 5.0

---

backend_modules/libvirt/host/user_data.yaml

Last changes in repos (images already done) to accomodate the fact that head is now 5.1.

Head is now on 5.1

---

salt/controller/init.sls

Reverts uyuni-project/sumaform#1701 until qe-develop branch is ported into Manager-5.0

Revert "Remove spacewalk 5.0 product from bundle 3.3 exclusion"

---

salt/mirror/etc/minima.yaml

This PR accomodates for the new syntax of the mirror as developed by @NamelessOne91 .
It also fixes the architecture of the Debian and Ubuntu tools to `amd64`.
**Note:** Honestly, I would simply remove this piece of code that allows to create a minima server "out of the box", but that no one uses, and that is probably full of errors.

New syntax for mirror

---

README_ADVANCED.md
backend_modules/aws/host/user_data.yaml
backend_modules/azure/base/main.tf
modules/mirror/variables.tf
salt/mirror/etc/apt-mirror.list
salt/mirror/etc/minima.yaml
salt/mirror/etc/minimum_repositories_testsuite.yaml
salt/salt_testenv/salt_bundle_package.sls

Various previously forgotten occurrences of Ubuntu 24.04: clouds, mirror, testenv.

More occurrences of Ubuntu 24.04

---

backend_modules/null/base/variables.tf

Add default variable to product_version at base level.

Add default value to product_version at base level.

---

salt/repos/clienttools.sls

Remove whitespace introduced by jinja

Remove whitespace introduced by jinja

---

salt/repos/clienttools.sls

Fighting Jinja syntax

---

salt/repos/clienttools.sls

Remove more whitespace added by jinja (by the comments)

Remove more whitespace added by jinja

---

modules/cucumber_testsuite/main.tf

Fix variable assignment for repository_disk_size and database_disk_size for server_containerized

Fix variable assignment for repository_disk_size and database_disk

---

salt/server_containerized/install_mgradm.sls

Add podman login state before using registry

Add podman login state before using registry

---

backend_modules/null/host/main.tf

Fix github actions for CI mirror local

Fix githubactions

---

modules/cucumber_testsuite/main.tf

Enable by default salt bundle as intended in ci project.

Enable salt bundle by default

---

modules/cucumber_testsuite/main.tf

Don't update OS during sumaform salt stages for CI.

Disable update os

---

salt/controller/run-testsuite

Add new "proxy" stage to `run-testsuite` script.

New "proxy" stage

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/azure/base/main.tf
backend_modules/azure/host/user_data.yaml
backend_modules/libvirt/host/network_config.yaml
backend_modules/null/base/variables.tf
salt/mirror/etc/mirror-images.conf

Add entries needed by AWS and Azure backends to deploy Ubuntu 24.04 based minions.

Add entries for Ubuntu 24.04 Cloud images

---

backend_modules/aws/host/user_data.yaml
backend_modules/azure/host/user_data.yaml
backend_modules/libvirt/host/user_data.yaml

* homogeneous whitespace in Jinja expressions
* use mirror consistently

Cosmetical changes + mirror consistency

---

backend_modules/libvirt/host/user_data.yaml

Partial revert of f34f9939b
Some repositories are not mirrored, I'm not sure why. I asked Marina whether they are even correct, but in the doubt, I revert some of the changes from  f34f9939b .

Partial revert of f34f9939b

---

backend_modules/libvirt/host/combustion
backend_modules/null/base/variables.tf
modules/controller/main.tf
modules/proxy_containerized/main.tf
modules/server_containerized/main.tf
salt/server_containerized/testsuite.sls

Add 5.1 released product version declaration.
Add 5.1 repository to combustion to install the correct uyuni tool.

Add support to 5.1 released

---

salt/server_containerized/large_deployment.sls

Due to the DB split, we can't access to this configuration file `/var/lib/pgsql/data/postgresql.conf` through the server container, using `mgrctl exec`, that gonna apply for Uyuni and Head.
So, we made a diversion of the salt states in order to use `podman exec uyuni-db`, which is the default name for the new DB container.

Fix large deployment postgresql

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/network_config.yaml
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
salt/default/ids.sls

Support Amazon Linux 2023 as a possible VM.
This PR does NOT add Amazon Linux 2023 to the controller for the Build Validation. That will be done in a separate PR.

Support Amazon Linux 2023

---

salt/controller/bashrc

Related to https://github.com/uyuni-project/uyuni/pull/10211/ proposal

New env.var. on controller that points to our build sources

---

salt/server_containerized/large_deployment.sls

Add 5.1 product version to the list of separate db.

Add 5.1 to the list of separate db

---

modules/server_containerized/main.tf
salt/server_containerized/initial_content.sls
salt/server_containerized/wait_for_mgr_sync.sh

With server_containerized the channels option is not working. This PR fix the first things

fix channels option for server_containerized

---

backend_modules/libvirt/base/main.tf

Final URL for SLE 15 SP7

---

salt/controller/init.sls

Adding deployment of health check for testing.
Related to: https://github.com/uyuni-project/uyuni/pull/10179
Minima PR  for infrastructure repo created (MR#1055)

Add health check deployment to controller for testing

---

salt/repos/client_tools.sls

Fix elX 5.1 nightly repository.

Fix elX tool repository.

---

salt/repos/os.sls
salt/repos/proxy_containerized51.sls
salt/repos/server_containerized51.sls

Update devel repositories for MLM 5.1 on sles15sp7.
Add missing repositories for sles15sp7.

Update devel repositories for MLM 5.1 on sles15sp7

---

salt/repos/proxy43.sls
salt/repos/server43.sls

Add LTS repositories for 4.3 proxy and server.

Add LTS update channel for 4.3

---

backend_modules/libvirt/host/combustion

Add missing mgrpxy-bash-completion

Add missing dependency for proxy

---

backend_modules/azure/host/user_data.yaml
salt/repos/testsuite.sls

Get uyuni.key on Tumbleweed minions
Related to https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/1088

Get uyuni.key on Tumbleweed minions

---

salt/repos/testsuite.sls

QE: Add test repo to Tumbleweed

---

salt/repos/os.sls

Fix LTSS path for sles15sp5
