packer/centos7.json
packer/http/ks_centos7.cfg
packer/http/ks_res7.cfg
packer/res7.json
packer/scripts/cleanup.sh

This makes it possible to build images of those OSs via packer. The resulting images are stripped of packages galore, but aren't minimal.

CentOS7 and RES7 build files for packer

---

modules/libvirt/base/main.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/variables.tf
packer/http/ks_centos7.cfg
salt/client/repos.sls

Add support for spinning up CentOS 7 images.
**WARNING**: due to package-mirror dependency on base/main.tf#configuration , your package-mirror will be **deleted** when applying this patch. Backup accordingly.

Add CentOS 7 image

---

salt/suse-manager/salt.sls

Salt is used by sumaform for provisioning, so `salt` package is always installed in every deployed machine but not the `salt-api` package.
This PR fixes the "HACK" to restart the `salt-api` in order to prevent errors during provisioning if `salt-api` doesn't exist.
Also prevent an error trying to run `systemctl restart salt-api` if running OS uses SysV.

Only restart 'salt-api' is salt-api is installed.

---

salt/package-mirror/init.sls

Since parted is not installed by default, we need to install it (otherwise we will have a problem when partitioning).

Add parted package

---

salt/suse-manager/tomcat.sls

The following line in the config file prevents Tomcat from applying the configuration.
```
TOMCAT_CFG_LOADED="1"
```
This PR modifies the state file to comment-out the specified line.

Fix tomcat 8 remote debug config

---

modules/libvirt/control_node/main.tf
modules/libvirt/control_node/variables.tf

Augmenting the control node's memory is one way to solve the problem of phantomJS crashes. More generally, this setting might reveal useful in other situations.

Add "memory" as a possible setting for the control node

---

salt/postgres/init.sls
salt/suse-manager/init.sls

`user` option is deprecated for `cmd.run`

Fix: use `runas` instead of `user` for `cmd.run`

---

README_ADVANCED.md
main.tf.aws.example
modules/aws/host/variables.tf
modules/libvirt/client/main.tf
modules/libvirt/client/variables.tf
modules/libvirt/control_node/main.tf
modules/libvirt/control_node/variables.tf
modules/libvirt/host/main.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/package_mirror/main.tf
modules/libvirt/package_mirror/variables.tf
modules/libvirt/postgres/main.tf
modules/libvirt/postgres/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
salt/default/init.sls
salt/default/pkgs.sls
salt/default/repos.sls
salt/package-mirror/mirror.sh
salt/suse-manager/repos.sls
salt/terraform-resource/init.sls

This allows to configure additional repositories to be used by simply defining them in main.tf as a variable.
(requires a newer version of terraform. Tested with version 0.8.6)
```
module "suma-headpg" {
source = "./modules/libvirt/suse_manager"
base_configuration = "${module.base.configuration}"
name = "suma-headpg"
version = "head"
memory = 4096
extra_repos = [ "http://download.domain.top/my/devel/repository" ]
// see modules/libvirt/suse_manager/variables.tf for possible values
}
```

configure extra repositories and extra packages via variable

---

salt/suse-manager/rhn.sls

This PR addresses the [issue#81](https://github.com/moio/sumaform/issues/81).
It adds the `incomplete_package_import = 1` if the `for_development_only' is 'True`.

Speed-up reposync (issue#81)

---

salt/minion/init.sls

There is a bug just recently where calling the highstate fails because of a conflicting id.  @mc fixed an issue in SUSE Manager where he used salt-minion in a state.  
>>> output here
rfsuma3pg:~ # salt rfminsles12sp1* state.highstate
rfminsles12sp1.tf.local:
Data failed to compile:
----------
Detected conflicting IDs, SLS IDs need to be globally unique.
include:
The conflicting ID is 'salt-minion' and is found in SLS 'base:minion' and SLS 'base:services.salt-minion'
ERROR: Minions returned with non-zero exit code
Renaming this from salt-minion to just minion makes the highstate apply successfully.

Fix id because it conflicts with something on suma

---

salt/control-node/run-testsuite.sh

We need to have the suma-server certificate in order to
visualize the button tristate on phantomjs.

BUGFIX: fix phantomjs issue with secure websocket

---

salt/control-node/init.sls

This gem packaged in our repo galaxy,
is usefull for find unused steps and analyze code of ruby.
Fix :https://github.com/SUSE/spacewalk-testsuite-base/issues/197

Add gem for codecoverage ruby

---

README_ADVANCED.md
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
salt/suse-manager/rhn.sls

The light alternative to package-mirror: configure the URL of an SMT server to get the packages from internal.

add smt variable to suse_manager to configure a from mirror

---

salt/control-node/run-testsuite.sh

This variable is implicit, we use always phantomjs and
do not support other browser support.

Remove browser variable.

---

salt/client/repos.sls
salt/client/testsuite.sls
salt/minion/testsuite.sls

* Functionality: add openscap packages to the minion as well.
* Cleanup: no more hack to pick repo in suse manager 3.0 for openscap packages.
* Cleanup: get rid of errors about missing packages on centos7.

Adding openscap packages to the minion as well.

---

salt/client/testsuite.sls

take care the we run with the latest libzypp.
A fix in apache prevents to use older libzypp.

enforce latest libzypp because of bsc#1030919

---

README_ADVANCED.md
salt/controller/bashrc
salt/controller/init.sls
salt/controller/run-testsuite.sh

This change moves environment setup to `.bashrc` for the test controller so that the individual cucumber features can be runnable from the command line as below:
```
cucumber features/my_feature.feature
```

Make Cucumber features runnable from the command line

---

salt/controller/init.sls

Owasp -> was never executed
Mozilla pkgs never used really

 Remove depracted pkgs for controller

---

salt/default/repos.sls

A Salt failure during provisioning can happen when using
`additional_repos`, e.g.:
```
protobuf = "http://download.opensuse.org/repositories/home:aplanas:midokura/SLE_12_SP2/"
```
zypper cause this problem, as it asks interactively if repo is trusted:
```
module.minion_improved.minion.libvirt_domain.domain (remote-exec): New repository or package signing key received:
module.minion_improved.minion.libvirt_domain.domain (remote-exec):   Repository:       'protobuf'
module.minion_improved.minion.libvirt_domain.domain (remote-exec):   Key Name:         home:aplanas OBS Project <home:aplanas@build.opensuse.org>
module.minion_improved.minion.libvirt_domain.domain (remote-exec):   Key Fingerprint:  98DB6E85 C50321EA D148EA36 4C078E5A 3A961CF7
module.minion_improved.minion.libvirt_domain.domain …
```

Fix: disable GPG check on 3rd-party repos

---

modules/libvirt/suse_manager_proxy/variables.tf
salt/default/repos.d/Devel_Galaxy_Manager_Head_SLE-Manager-Tools-11-x86_64.repo
salt/mirror/mirror.lftp

With 512 MB, oom-killer keeps killing squid or httpd processes

512 MB are not enough for a proxy + accomodating repository changes

---

modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
salt/default/repos.d/Devel_Galaxy_Manager_3.1_RES-Manager-Tools-7-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.1_SLE-Manager-Tools-11-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.1_SLE-Manager-Tools-12-x86_64.repo
salt/default/repos.sls
salt/mirror/mirror.lftp
salt/suse_manager_proxy/repos.d/Devel_Galaxy_Manager_3.1.repo
salt/suse_manager_proxy/repos.d/SUSE-Manager-Proxy-3.1-x86_64-Pool.repo
salt/suse_manager_proxy/repos.d/SUSE-Manager-Proxy-3.1-x86_64-Update.repo
salt/suse_manager_proxy/repos.sls
salt/suse_manager_server/repos.d/Devel_Galaxy_Manager_3.1.repo
salt/suse_manager_server/repos.d/SUSE-Manager-3.1-x86_64-Pool.repo
salt/suse_manager_server/repos.d/SUSE-Manager-3.1-x86_64-Update.repo
salt/suse_manager_server/repos.sls

Some version fixes, URL changes and introduce 3.1-nightly version since we have the 
needed Devel repos for it.
salt/default/repos.sls :
I re-ordered the Tools repos creation:
1. check for any "released" string in the grains. Also used when no version is specified
2. check for any "nightly" string in the grains.
3. check for "head"
For me this makes it easier to understand as the current ordering.

31 repositories

---

salt/suse_manager_server/rhn.sls

This PR fixes a bug introduced in `8726bc9`, where Jinja complains about a
missing else:
```
module.suma3pg.suse_manager.libvirt_domain.domain (remote-exec): local:
module.suma3pg.suse_manager.libvirt_domain.domain (remote-exec):     Data failed to compile:
module.suma3pg.suse_manager.libvirt_domain.domain (remote-exec): ----------
module.suma3pg.suse_manager.libvirt_domain.domain (remote-exec):     Rendering SLS 'base:suse_manager_server.rhn' failed: Jinja variable the inline if-expression on line 83 evaluated to false and no else section was defined.
```
This PR will add an empty else branch in order to pass compilation phase for
Jinja.

Fix: add empty else branch

---

salt/suse_manager_server/testsuite.sls

This PR installs `salt-ssh` CLI on the SUMA server (for testsuite only) since it's now required by `spacewalk-testsuite-base` to check rendered pillar data for ssh minions.

Installing "salt-ssh" cli on suma server (for testsuite only)

---

TROUBLESHOOTING.md
modules/aws/evil_minions/main.tf
modules/aws/host/main.tf
modules/aws/minionswarm/main.tf
modules/aws/mirror/main.tf
modules/libvirt/host/main.tf

This PR applies the new `terraform-post-resource` state at the end of a resource deployment for libvirt and aws modules in order to manage cleanup tasks:
- Remove all files from /srv/salt/
- Remove Salt package from traditional clients
I'm using `at` to trigger the cleanups because otherwise Salt would fail during `terraform-post-resource` execution as jinja template and salt itself would disappear at execution time.

Change salt 'file_root' for sumaform to /opt/sumaform/srv/salt

---

modules/libvirt/base/main.tf

Should address #74, has been reproduced and tested by a colleague

Bugfix: avoid VMs to be created before base images are ready

---

README_ADVANCED.md
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
salt/suse_manager_server/init.sls

With the default configuration, whenever we bring up a SUMa machine,
`rhn.conf` is instructed to use root@`hostname -d` as the email sender.
Emails are then using `root@tf.local`, which may be discarded by the
recipient's SMTP server due to being a non-existent domain.
With this PR we can override email address to use as 'from' by
supplying the parameter: `suma_email_from`. E.g.:
```
module "sumamail2" {
source = "./modules/libvirt/suse_manager"
base_configuration = "${module.base.configuration}"
name = "sumamail2"
version = "head"
suma_email_from = "root@mbologna.openvpn.suse.de"
}
```

Feat: specify email address 'from' to use in SUMa

---

TROUBLESHOOTING.md

If you don't have YaST, edit /etc/sysconfig/SuSEfirewall2 to enable mdns

Name /etc/sysconfig/SuSEfirewall2 variables

---

salt/suse_manager_server/init.sls

Restore dependency to postgresql94 in 3.0-released version as a workaround fix.

Fix: restore pkg dependency to postgresql94

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/suse_manager/main.tf
salt/controller/init.sls

Based on the version of the server we are going to launch the testsuite
against, we decide automatically which branch of the testsuite to
checkout.
The association is done in the map defined in:
`modules/libvirt/controller/main.tf`
@MalloZup @Bischoff

Feat: autoselect testsuite branch

---

salt/mirror/mirror.lftp
salt/suse_manager_server/repos.d/SUSE-Manager-Head-x86_64-Pool.repo

I switched the version in Head to 3.2. These changes are needed to keep things working
@moio @MalloZup : I hope I did not forget anything. The new repos are currently building. Expect some trouble :-)

The Head Pool repo changed the version to 3.2

---

main.tf.libvirt-testsuite.example

Without this patch, resources are created independently (e.g. clients
are created without waiting for the server to be created).

Fix server hostname

---

salt/suse_manager_server/tomcat.sls

TOMCAT_CFG_LOADED is not present for older version `[2.1, 3.0]`.

TOMCAT_CFG_LOADED flag only for 3.1 version or later

---

main.tf.libvirt-testsuite.example
modules/libvirt/README.md
modules/libvirt/client/main.tf
modules/libvirt/client/variables.tf
modules/libvirt/host/main.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
salt/client/testsuite.sls
salt/default/init.sls
salt/minion/testsuite.sls
salt/suse_manager_server/testsuite.sls

If an host is marked as salt-ssh bootstrapped, we should use its vanilla option.
This needs testing.
@MalloZup @Bischoff

Fix: make salt-ssh hosts really vanilla hosts

---

salt/default/repos.sls

Fix installing galaxy.key on all systems, not just SUSE

Fix - install galaxy.key on all systems

---

salt/suse_manager_server/filebeat.yml

filebeat fails to start on suse manager server because filebeat.yml cannot be evaluated.
These environment variables only exists on a jenkins node. SUSE Manager server is not a jenkins node, only the sumaform control node is.

Filebeat: remove environment references

---

salt/suse_manager_server/filebeat.yml

The date expression is being added by logstash, filebeat cannot cope with that.
Also use the hostname as the index basename.

filebeat: drop date from index, use hostname

---

salt/client/testsuite.sls
salt/minion/testsuite.sls

Fix this:
An error was encountered while installing package(s): Zypper command
failure: Package 'aaa_base-extras' not found.

Testsuite: do not install unneeded packages

---

salt/suse_manager_server/testsuite.sls

Since the test got depracted, and added no value at all on the testsuite
wise decision is to remove it, sparing time and false failures.

Remove anaconda download

---

.travis.yml

Addresses:
```
$ GIMME_OUTPUT="$(gimme 1.9 | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
stat /home/travis/tmp: no such file or directory
```

Test: fix error in Travis

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/base/variables.tf
salt/default/repos.d/SLE-12-SP3-x86_64-Pool.repo
salt/default/repos.d/SLE-12-SP3-x86_64-Test-Update.repo
salt/default/repos.d/SLE-12-SP3-x86_64-Update.repo
salt/default/repos.sls
salt/mirror/mirror.lftp

This PR makes the SLE12SP3 image available on sumaform in order to be able to deploy and test SUSE Manager on SP3 systems. Also adds SLE12SP3 repositories to be synced by the package mirror.
The SLE12SP3 qcow2 image is already built on: https://build.suse.de/package/show/Devel:Galaxy:Terraform:Images/sles12sp3
This PR addresses https://github.com/SUSE/spacewalk/issues/1958

Make SLE12SP3 image available on sumaform

---

salt/default/ids.sls

This PR fixes a problem while resetting the 'machine-id' for the deployed machines. Currently, the machine id are not being reset properly so I ended up with duplicates machine-id for different systems running the same image after deployment.
According with the documentation at https://wiki.microfocus.com/index.php?title=SUSE_Manager/Register_Clones#Steps_for_registering_a_cloned_system_to_SUSE_Manager , the right way to reset the machine id is:
> 
> 5.1. On the SLES 11 and RH5/6 clients exhibiting the issue enter the following as root:
> 
>  rm /var/lib/dbus/machine-id
>  dbus-uuidgen --ensure
> 
> 5.2. On SLES 12, or RH7-based clients exhibiting the issue enter the following as root:
> 
>  rm /etc/machine-id
>  rm /var/lib/dbus/machine-id
>  dbus-uuidgen --ensure
> …

Bugfix: Reset 'machine-id' properly to prevent duplicates

---

main.tf.libvirt-testsuite.example
modules/aws/host/main.tf
modules/aws/host/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
salt/suse_manager_server/init.sls
salt/suse_manager_server/salt_master.sls

Enables `auto_accept` on all Salt masters by default.

Automatically accept minion keys by default

---

README_ADVANCED.md
modules/aws/host/main.tf
modules/aws/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf

This is another requirement for automated (performance) tests, as we want to onboard minions directly with the correct channel set, but useful in general.

Add option to specify an Activation Key for minions

---

salt/controller/init.sls

Anytime I setup a new controller, I find myself in need of `screen` tool to run the test suite with, so I can log out of the machine re-attach the terminal which the tests are running at a later time.
I'd be nice to have this tool available by default on the controller machine.

Add screen package to the controller machine

---

TROUBLESHOOTING.md

It happens sometime you want to refresh your images, so you want to `taint` them to get a new downloaded image.
The syntax is the same when tainting any other resource, but the name of the module and the number of the volume are slightly different. I think it can be useful to have it documented here to get it quickly done.

Taint an image resource

---

salt/mirror/mirror.lftp
salt/suse_manager_proxy/repos.d/Devel_Galaxy_Manager_Head.repo
salt/suse_manager_server/repos.d/Devel_Galaxy_Manager_Head.repo

Head does not build anymore for SP2. We need to use SP3 now.

Head should use packages build for SP3

---

salt/suse_manager_proxy/init.sls

This PR fixes the incompatibilities between testsuite and proxy (issues #122 and #204).
It does it by installing and running the bootstrap script in
`salt/suse_manager_proxy/init.sls` 
only when
`for_development_only` 
is true, just like it is already done in
`sumaform/salt/suse_manager_server/initial_content.sls` 
.
Same goes for CAs etc.

Install and run bootstrap script only in dev mode

---

salt/default/init.sls

state "timezone_setting" is failing because there is no localtime symlink. Try to call this state after the timezone package is installed
```
module.min-sles12sp3.minion.libvirt_domain.domain (remote-exec): ----------
module.min-sles12sp3.minion.libvirt_domain.domain (remote-exec):           ID: timezone_setting
module.min-sles12sp3.minion.libvirt_domain.domain (remote-exec):     Function: timezone.system
module.min-sles12sp3.minion.libvirt_domain.domain (remote-exec):         Name: Europe/Berlin
module.min-sles12sp3.minion.libvirt_domain.domain (remote-exec):       Result: False
module.min-sles12sp3.minion.libvirt_domain.domain (remote-exec):      Comment: Unable to compare desired timezone 'Europe/Berlin' to system timezone: Failed to read /etc/localtime to determine current timezone: …
```

set timezone after the timezone package is installed

---

salt/controller/bashrc

Do not generate "export PROXY=..." when the proxy grain does not exist.
Makes the value "None" generated by {{ grains.get('proxy') }} disappear.
We might want to do the same for the SSH minion and the CentOS minion in the future.

Make the PROXY environment variable optional

---

salt/default/hostname.sls
salt/default/set_hostname.py
salt/default/set_ip_in_etc_hosts.py

- uses the short name in `/etc/hostname` and FQDN in `/etc/HOSTNAME` as [per SUSE recommendation in bug 972463](https://bugzilla.suse.com/show_bug.cgi?id=972463#c25). Using the FQDN in `/etc/hostname` is not OK at least in SUSE systems because of a [downstream patch in systemd](https://github.com/openSUSE/systemd/commit/2ce06a5a49)
- retains a custom Python script in order to write to `/etc/hosts`
- this is needed to support cases in which a well-configured DNS server is not available, as avahi alone is not sufficient to have both `hostname` and `hostname -f` return correct values. That is true even when enabling the [--enable-search-domains](http://0pointer.de/lennart/projects/nss-mdns/) option in `nss-mdns` and adding the avahi domain to search domains in `resolv.conf`
- notr that we …

More hostname fixes

---

modules/libvirt/suse_manager_proxy/main.tf

SP3 is needed on the proxy HEAD:
```
Problem: nothing provides product(SLES) >= 12.3 needed by product:SUSE-Manager-Proxy-3.2-0.x86_64
```
And while I'm at it, I do the same for TEST.

SP3 default for server and proxy on TEST AND HEAD

---

main.tf.libvirt-testsuite.example

This PR shows the testsuite sample setup with new configuration parameters to access and pull the GitHub testsuite project repository since it's now moved inside a private SUSE GitHub repo and it requires *username* and *password*.

Add missing parameters to the testsuite controller sample

---

salt/suse_manager_proxy/repos.d/SUSE-Manager-Proxy-3.1-x86_64-Pool.repo

3.1 proxy was using a 3.0-based URL.
(New incarnation of https://github.com/moio/sumaform/pull/236 ).

Correct repository URL for 3.1 proxy

---

salt/controller/bashrc

Rationale: consistency with other variables, simplicity.
$TESTHOST is kept during the transition, a second commit will remove it completely.
See issue https://github.com/SUSE/spacewalk/issues/2459

Rename $TESTHOST to $SERVER

---

salt/suse_manager_server/testsuite.sls

This PR mocks the contents of installation files
Rationale:
* The test suite does not use the real contents of these files
* The downldoad might fail
* The download takes time

Mock autoinstallation files

---

salt/controller/repos.d/Devel_Galaxy_cucumber_testsuite.repo
salt/controller/repos.d/Devel_Galaxy_ruby_test.repo
salt/controller/repos.sls
salt/mirror/minima.yaml

this repository will contain only pkgs that are not rubygems

Add new repository for control-node

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/controller/variables.tf
salt/controller/bashrc

Like for the proxy, one should not need to create all nodes in order to run the testsuite.
This will allow for more lightwight deployments and test suite runs when debugging.
(The names "CENTOS" and "ceos" will probably change to "SLESES" and "sleses" once we get rid of CentOS in favor of SLES ES, but for now we keep consistent with the old naming.)

Make CentOS minion optional

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/controller/variables.tf
salt/controller/bashrc

Like for the proxy, one should not need to create all nodes in order to run the testsuite.
This will allow for more lightwight deployments and test suite runs when debugging.

[WIP] Make SSH minion optional

---

modules/libvirt/controller/main.tf
salt/controller/repos.d/SLE-12-SP1-SDK-x86_64-Pool.repo
salt/controller/repos.d/SLE-12-SP3-SDK-x86_64-Pool.repo
salt/controller/repos.sls
salt/mirror/minima.yaml

Move controller to sles12sp3
I think is better to use sles12sp3 at this point that leap42.3. 
Anyway sles12sp3 has ruby 2.1 has default, and we need ruby 2.2, so we need to find out ruby-devel repo

migrate from sles12sp1 to sles12sp3 controller

---

salt/suse_manager_server/repos.sls

Just 2 new modules in the standard repos.sls state in suse_manager_server that remove the client tools repositories. I deployed VM's with this state and no errors showed up, all the states were applied successfully, the repos were removed and the double ```zypper patch``` package conflict is not there.
Fixes issue #247

Remove client tools repos from srv after deployment

---

salt/suse_manager_server/repos.sls

This is tested with ```head, 3.0-released``` and ```3.1-released```. In head, the repos are not removed because of the [jinja issue](https://github.com/SUSE/spacewalk/issues/2947), on the others the repos are removed. Hopefully as soon as the jinja issue is solved, the repos will also be removed there. In any case, this PR will not break the jenkins build. Fixes #248 
I didn't test the SLE15 or SLE11 cases.

Remove the client tools repos for server

---

main.tf.libvirt-testsuite.example

The "version" variable is apparently needed only on the server.
This PR also includes cosmetical changes: English syntax, "optional" indications.

Add version information to all modules in libvirt+testsuite main.tf example

---

README_ADVANCED.md
modules/aws/host/variables.tf
modules/libvirt/README.md
modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/client/main.tf
modules/libvirt/client/variables.tf
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/evil_minions/main.tf
modules/libvirt/evil_minions/variables.tf
modules/libvirt/grafana/main.tf
modules/libvirt/grafana/variables.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/minionswarm/main.tf
modules/libvirt/minionswarm/variables.tf
modules/libvirt/mirror/main.tf
modules/libvirt/mirror/variables.tf
modules/libvirt/postgres/main.tf
modules/libvirt/postgres/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf

This is to regroup variables so that the distinction between cross-backend and backend-specific properties is clear.
Aim is to make future portability to backends easier.

Libvirt portability refactoring

---

salt/mirror/init.sls

Ever wondered why you setup a mirror and mirror script does not run,
even if cronjob time is already passed?
In our kiwi distribution cron.service is not started (but enabled),
so you either start cron (this PR does it) or reboot the machine.

Fix: mirror: start crontab

---

modules/openstack/base/variables.tf
modules/openstack/host/main.tf
packer/centos7openstack.json
packer/scripts/cloud.sh

Add centos7_image for openstack backend.

Add centos7_openstack_support via packer

---

salt/mirror/minima.yaml

Current mirror URL for openSUSE does not have a `repodata` directory, and minima will fail.

Fix: openSUSE mirror

---

main.tf.openstack-testsuite.example
main.tf.openstack.example

Since the main target audience are probably SUSE people, you might consider changing this.
This way deployments to the ECP cloud are working without modification of the
example config.

Making SUSE ECP Cloud the default

---

main.tf.libvirt-testsuite.example
main.tf.openstack-testsuite.example
modules/libvirt/controller/variables.tf
modules/openstack/controller/variables.tf

We had users stumbling upon the problem that creating the controller "takes forever" - git waits for user input.
I made the credentials passwords mandatory, so they can't be skipped at plan/apply time.
Additionally, since this does not work for users with 2FA, I added a link to where users can find the credentials we use for CI.

Testsuite: clarify need for credentials

---

salt/suse_manager_server/testsuite.sls

[-6, -3] minutes before installation => [-3, -1] minutes
0.05 hour = 3 minutes
0.033 hour = 2 minutes
@moio FYI - just different timings in a test suite configuration file

Fix content staging window

---

README_ADVANCED.md
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
modules/openstack/suse_manager_proxy/main.tf
modules/openstack/suse_manager_proxy/variables.tf
salt/default/repos.d/systemsmanagement-saltstack_products-next.repo
salt/default/repos.sls
salt/mirror/minima.yaml
salt/suse_manager_proxy/repos.d/Devel_Galaxy_Manager_Head_Leap.repo
salt/suse_manager_proxy/repos.d/Leap-SUSE-Manager-Proxy-Head-x86_64-Pool.repo
salt/suse_manager_proxy/repos.sls
salt/suse_manager_server/repos.d/Devel_Galaxy_Manager_Head_Leap.repo
salt/suse_manager_server/repos.d/Leap-SUSE-Manager-Head-x86_64-Pool.repo
salt/suse_manager_server/repos.sls

Superseeds #272 (after the last sumaform changes I was afraid of having to resolve a lot of merge conflicts, so just in case...)
```main.tf``` example:
```
module "server" {
source = "./modules/libvirt/suse_manager"
base_configuration = "${module.base.configuration}"
name = "server"
version = "head"
image = "opensuse423"
// see modules/libvirt/suse_manager/variables.tf for possible values
}
module "proxy" {
source = "./modules/libvirt/suse_manager_proxy"
base_configuration = "${module.base.configuration}"
image = "opensuse423"
name = "proxy"
version = "head"
server_configuration = "${module.server.configuration}"
}
```

Support SUSE Manager on openSUSE

---

salt/controller/run-testsuite.sh

running at moment run-testsuite we don't have the retcode according to failure

add set -e for having in CI the exact retcode

---

modules/libvirt/client/main.tf
modules/libvirt/host/main.tf
modules/libvirt/minion/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf

To be able to define "use_unreleased_updates" also for ssh minions we need to configure the grain
in "host"

configure grain for use_unreleased_updates in host

---

salt/suse_manager_server/master-custom.conf
salt/suse_manager_server/salt_master.sls

while using --wipe the logs went away.
Configuring logfile outside of the thin keep it visible and can be used for debugging.
Also run in debug mode.

log salt-ssh client log outside of the thin dir

---

salt/default/repos.sls

This PR removes the call of `zypper refresh` to refresh additional repositories in case we are using CentOS.
Since ` yum` refreshes the packages lists at each command, we don't do anything instead.

Additional repositories on CentOS don't use zypper

---

salt/client/testsuite.sls
salt/minion/testsuite.sls

In order to test patch installation on CentOS we need the BuildRepo and some packages installed
we can update using the testsuite repo.

Add BuildRepo and install dummy packages also on RedHat systems

---

salt/client/testsuite.sls

this pkg is not used for tests and is failing on sle15

remove pkg unused for tests

---

README_ADVANCED.md
modules/aws/host/variables.tf
modules/libvirt/controller/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
modules/openstack/controller/main.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager/variables.tf
modules/openstack/suse_manager_proxy/main.tf
modules/openstack/suse_manager_proxy/variables.tf
salt/default/repos.d/Devel_Galaxy_Manager_3.2_SLE-Manager-Tools-11-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.2_SLE-Manager-Tools-12-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-11-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-12-Beta-x86_64.repo
salt/default/repos.sls
salt/mirror/minima.yaml
salt/suse_manager_proxy/init.sls
salt/suse_manager_proxy/repos.d/SUSE-Manager-Proxy-3.2-x86_64-Pool.repo
salt/suse_manager_proxy/repos.sls
salt/suse_manager_server/init.sls
salt/suse_manager_server/repos.d/SUSE-Manager-3.2-x86_64-Pool.repo
salt/suse_manager_server/repos.sls

This PR adds support for `3.2-released`, currently defined as latest beta.
Notes:
* the server and proxy pool repository URLs are hardcoded for SLE 12 SP3, but now we also support openSUSE 42.3. I did not find a beta repository for 42.3 though;
* I had to add the development tools repository, otherwise it would not install fine (apache2 was not starting).
* I did not add the other development repositories.
It works with this setup, but please check whether this is correct. Honestly, I'm a bit lost in this repositories jungle.

Add support for 3.2-released

---

salt/default/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-11-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-12-Beta-x86_64.repo
salt/mirror/minima.yaml

This PR changes the meaning of `3.2-released` version, from "Beta 3" to RC1.
Note: RC1 is not out yet - the RC1 developmenet tools repos are a kind of "preview", i.e. they currently contain Beta3 + some fixes.

3.2-released will point to RC1 instead of beta3

---

salt/default/repos.d/SLE-Manager-Tools-SLE-11-Beta-x86_64.repo

According to Michael's email, the path to SLE11SP4 has changed - for RES 7 I'm not sure.

Appending "update/" to path to SLE11SP4 repo

---

packer/http/ks_sles-es7.cfg
packer/scripts/base-es.sh
packer/sles-es7.json

we want to use sles-expanded support instead of centos7 for CI tests. 
This pr is the first milestone for achiving this.
We will have an image that works already with sumaform and avahi setup.
Where we will put this image? Schnell.suse.de or elsewehere?
i already tested the image with sumaform and everything works (avahi, ssh, salt).
I didn't test to swtich centos7 to sles-es but is out of scope for this
where to place the img
- schnell.suse.de
- or like centos7 location
download the image from here (tomorrow)
```m226.mgr.suse.de:/home/jenkins/workspace/sles-es7``` now i have 20% updted

add sle-es7.4 packer img

---

modules/libvirt/controller/variables.tf

If you agree this changes one line to change the memory from 1024 to 2048 so we can remove it from the jobs specific conf and leave the default when this gets merged. Fixes #347

Change the default memory in controller. Fixes #347

---

modules/aws/host/variables.tf
modules/libvirt/controller/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager/variables.tf
modules/openstack/suse_manager_proxy/main.tf
modules/openstack/suse_manager_proxy/variables.tf
salt/default/repos.d/Devel_Galaxy_Manager_3.0_RES-Manager-Tools-7-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.0_SLE-Manager-Tools-11-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.0_SLE-Manager-Tools-12-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.1_RES-Manager-Tools-7-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.1_SLE-Manager-Tools-11-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.1_SLE-Manager-Tools-12-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.1_SLE-Manager-Tools-15-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.2_RES-Manager-Tools-7-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.2_SLE-Manager-Tools-11-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.2_SLE-Manager-Tools-12-x86_64.repo
salt/default/repos.d/Devel_Galaxy_Manager_3.2_SLE-Manager-Tools-15-x86_64.repo
salt/default/repos.sls
salt/mirror/minima.yaml
salt/suse_manager_proxy/init.sls
salt/suse_manager_proxy/repos.d/Devel_Galaxy_Manager_3.2.repo
salt/suse_manager_proxy/repos.sls
salt/suse_manager_server/init.sls
salt/suse_manager_server/repos.d/Devel_Galaxy_Manager_3.2.repo
salt/suse_manager_server/repos.sls

We are short before branching and we need to run cucumber tests for 3.2 on nightly build.

Specify 3.2 nightly

---

salt/mirror/minima.yaml

The new 3.2 main repo is missing in the minimal configuration

add missing 3.2 main repository to minima

---

salt/default/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-11-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-12-Beta-x86_64.repo
salt/mirror/minima.yaml

3.2-released will point to GMC instead of RC1

---

salt/minion/testsuite.sls

Fix this jinja2 bug.
I didn't tested it but should work.
In case of sles11sp4 the require is empty which cause a jinja2 error breaking sumaform
https://ci.suse.de/view/Manager/view/Manager-Head/job/manager-Head-cucumber-sle11sp4/140/consoleFull

Bugfix: in case of sle11 systems require is empty.

---

salt/default/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-11-Beta-x86_64.repo
salt/default/repos.d/SLE-Manager-Tools-SLE-12-Beta-x86_64.repo
salt/mirror/minima.yaml

Switched to latest repository URLs.

3.2-released: GMC -> GMC3

---

salt/repos/default.sls

This PR fixes an issue while deploying the `minssh-sles12sp3` minion on the testsuite. There is a jinja2 error while rendering the template because a bad comparison that wrongly assumes `grains['role']` is a list (the `not in` operator expects an interable object):
```
{% if 'suse_manager' not in grains.get('role') %}    <======================                                                                                                 
tools_pool_repo:
file.managed:
- name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Pool.repo
- source: salt://repos/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Pool.repo
- template: jinja
[...]
---
[CRITICAL] Rendering SLS 'base:repos.default' failed: Jinja error: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
File …
```

Fix wrong comparison since grains['role'] is not a list

---

salt/suse_manager_server/init.sls

New commit for java issue. For some reason putting:
```
suse_manager_setup:
cmd.run:
- name: /usr/lib/susemanager/bin/migration.sh -l /var/log/susemanager_setup.log -s
- creates: /root/.MANAGER_SETUP_COMPLETE
- require:
- pkg: suse_manager_packages
+    - pkg: java-1_8_0-ibm
- file: environment_setup_script
{% if grains.get('apparmor') %}
- sls: suse_manager_server.apparmor
{% endif %}
```
or making the suse_manager_setup require the java_ibm file, fails. Trying with just the state without the setup requiring it works for both 3.1 and 3.2 released for me.

Add right version of java fixes #378

---

salt/suse_manager_server/testsuite.sls

Replaced values are not inserted into rhn.conf because Salt cannot
find them (as they are not part of the default config file).
This PR uses Salt option append_if_not_found to ensure that these
settings will land on rhn.conf

Fix: append replaced values if not found

---

salt/repos/repos.d/Devel:SLEPOS:SUSE-Manager-Retail:Head.repo
salt/repos/testsuite.sls

Workaround: until `kiwi-desc-saltboot` is part of Manager:tools , we need
to manually add this repo that contains `kiwi-desc-saltboot`. Can be removed
when https://github.com/SUSE/spacewalk/issues/5202 is closed

Feat: temporary workaround for kiwi-desc-saltboot

---

modules/libvirt/controller/main.tf

Now we have a `Manager-3.2` branch for spacewalk, we can use it in the test suite controller in case we have requested `3.2-nightly` or `3.2-released` product version.

Using new branch Manager-3.2 as default when needed

---

salt/suse_manager_server/init.sls

Having this hack breaks sumaform for the server for anything != SLE12 (including Leap 42.3)
Not needed anymore, since bsc#1099454 is fixed.
Ping @ktsamis for awareness (can't assign him as reviewer).

Remove hack for bsc#1099454

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
main.tf.openstack-testsuite.example
modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/host/main.tf
salt/controller/bashrc
salt/mirror/minima.yaml
salt/repos/minion.sls
salt/repos/repos.d/Devel_SLEPOS_SUSE-Manager-Retail_Head.repo
salt/suse_manager_proxy/init.sls

This pull request adds support for SUSE Manager for retail:
```
+------------+-----------+------------+  10.160.0.0/16
|            |           |            |
+---+----+   +---+---+   +---+----+   +---+----+
|  eth0  |   |  eth0 |   |  eth0  |   |  eth0  |
|        |   |       |   |        |   |        |
| server |   | proxy |   | client |   | minion |
|        |   |       |   |        |   |        |
+  eth1  |   |  eth1 |   |  eth1  |   |  eth1  |
+---+----+   +---+---+   +---+----+   +---+----+
|            |           |            |
+------------+-----------+------------+  192.168.5.0/24
```
- variable geometry bits:
- new `retail` base setting
- corresponding `retail` grain on the hosts
- corresponding `$RETAIL` variable in the `.bashrc` on the host
- minimalistic network setup if in …

Adjustments for SUSE manager for retail - Rough network setting

---

packer/centos7.json

* correct checksum for new image (*)
* start sshd explicitely on kernel command line
* cosmetical syntax change
(*) GPG signature was checked, but without the CentOS CA

Fixes for new CentOS 7

---

modules/libvirt/base/main.tf

errror when destroying disk because depends_on was based on wrong names
(inexistent)

fix: this typo was causing race condition and

---

salt/default/hostname.sls
salt/repos/default.sls

This is the root cause to the CentOS problems: now Salt defines `osmajorrelease`as an integer and not as a string anymore.

Now osmajorrelease grain is an integer

---

salt/mirror/minima.yaml
salt/repos/controller.sls
salt/repos/repos.d/Devel_Galaxy_cucumber_testsuite.repo

Fixes #403 
Packages are already available at https://build.opensuse.org/project/show/systemsmanagement:sumaform:tools

Use phantomjs and twopence from systemsmanagement-sumaform-tools so they are available for public CI

---

salt/repos/default.sls
salt/repos/repos.d/Devel_Galaxy_Manager_3.1_RES-Manager-Tools-7-x86_64.repo
salt/repos/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo

We were putting 3.2 repos on 3.1 CentOS.
I am not sure at all about the difference between
`Devel_Galaxy_Manager_3.2_RES-Manager-Tools-7-x86_64.repo`
and
`Devel_Galaxy_Manager_3.2_RES-Manager-Tools-7-Beta-x86_64.repo`.
I suspect an error there. Cen you please review that too?

Added CentOS repos for 3.1

---

salt/mirror/minima.yaml
salt/repos/default.sls
salt/repos/repos.d/SLE-Manager-Tools-RES-7-Beta-x86_64.repo
salt/repos/repos.d/SLE-Manager-Tools-SLE-11-Beta-x86_64.repo
salt/repos/repos.d/SLE-Manager-Tools-SLE-12-Beta-x86_64.repo

This removes repos used during the beta phase of SUSE Manager 3.2.
Fixes  #422
cc @Bischoff

Remove beta repos

---

salt/grafana/init.sls
salt/suse_manager_server/postgres-exporter
salt/suse_manager_server/prometheus.sls

The exporter packages now include the systemd service files. 
This requires changes in the configuration.
In addition I have added a jmx_exporter for taskomatic as jmx_exporter is now a template service which can run multiple instances on a system with different configurations.

exporter packages include services

---

packer/scripts/cleanup.sh

When running latest CentOS 7 image (v3) on production servers, I get message
`Device eth0 does not seem to be present, delaying initialisation`
when I do `# ifup eth0`.
Root cause is that we remove the MAC address of the VM from `ifcfg-eth0`, because the running terraform machine will have a different MAC than the packer VM. That's fine, but then the recent RedHat scripts don't know how to identify the card anymore. This PR solves the issue simply by adding `DEVICE=eth0` to `ifcfg-eth0`.
Note: I checked, this is independent from the removal of `TYPE="Ethernet"`. That removal is still needed.
Mode nightmare on: this means rebuilding the images again :scream_cat:.

Fix error on CentOS 7

---

salt/repos/suse_manager_server.sls

When using 'test' as product repo and an opensuse image for the server,
we don't want to have SUSE Manager repos: mixing both Uyuni and SUSE
Manager repos doesn't fly.
Just like Head, switch to Uyuni repos if the server is an opensuse one.

Use Uyuni repos for test product too

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/pxe_boot/main.tf
modules/libvirt/pxe_boot/pxe.xsl
modules/libvirt/pxe_boot/variables.tf
salt/controller/bashrc

This PR defines a new module:
* `pxe_boot`: an unprovisioned host that can boot on its network card
It supersedes #439 (same, with two modules).

Add new minion acquired through PXE booting (single module)

---

modules/libvirt/controller/main.tf
modules/openstack/controller/main.tf
salt/controller/init.sls

This PR renames "Manager" into "master", since this branch does not exist for some time now. Furthermore, newcomers to Uyuni won't have the history for this name.
There is a related PR for the runner:
https://gitlab.suse.de/galaxy/sumaform-test-runner/merge_requests/67
As this will break the `main.tf`file for everyone, the plan is to send an email to the susemanager mailing list.

Use new name of "head" branch

---

salt/suse_manager_server/tomcat.sls

Bugfix for ibm-java was released 3 hours ago, so it should be in all mirrors.
Fixes #459

Remove hack for bsc#1119213

---

salt/default/avahi.sls

On some systems like Ubuntu there is no `eth0` but instead `ens3`. Rather than enabling only `eth0`, disable `eth1`and `ens4`.
BTW, there are 5 other occurrences of  `eth0` in sumaform :cry: .

Disable private network interfaces

---

salt/default/avahi.sls

This problem was not detected before because it works with a simple list on SLE12 SP3 and onwards.

"require:" wants a dictionary

---

salt/mirror/minima.yaml

Only keep the SLES product and the needed module repos in the list of
SCC repositories synchronized in the mirror (issue #472).

Don't mirror the deskop-related repos

---

modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/openstack/base/main.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager_proxy/main.tf
salt/repos/repos.d/systemsmanagement-sumaform-tools.repo
salt/repos/suse_manager_proxy.sls
salt/repos/suse_manager_server.sls
salt/suse_manager_proxy/init.sls

add the missing pieces to install SUSE Manager 4.0 (head) with SLE 15 SP1.
- add  image definition
- sumaform tools for SLE15 SP1
- Module repository definitions required for SUSE Manager
- change defaults for head
- fix firewall package

Switch head to SUSE Manager 4.0 based on SLE15 SP1

---

salt/suse_manager_server/tomcat.sls

Since Tomcat 8, the JDWP '8000' address binds to localhost by default. See
http://tomcat.apache.org/migration-8.html#Debugging
We now need '*:8000' address to be able to remote debug tomcat.

Adapt tomcat JDWP options

---

salt/suse_manager_server/tomcat.sls

Related: #478.
It seems that syntax `*:8000` does not work with Java 1.8, and it prevents tomcat  from starting. Since it's unlikely we want to debug from localhost, using the FQDN/hostname should be enough.
Verified as working with hostname by @cbosdo

Make JDWP options compatible for Java <= 1.8, listen only on FQDN/hostname

---

salt/mirror/minima.yaml
salt/repos/repos.d/SUSE-Manager-Head-x86_64-Pool.repo
salt/repos/repos.d/SUSE-Manager-Proxy-Head-x86_64-Pool.repo

SUSE Manager will change to be a base product.
The old name is now used for the root product and we have a new name for the module which
contains the packages.
Change to use the new module in sumaform.

SUSE Manager 4 become a base product - use the modules in sumaform

---

salt/suse_manager_server/testsuite.sls

When we monitor the whole event log we can easier see why errors happens in the testsuite.

monitor the salt event log when running the testsuite

---

modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf

This PR makes it possible to use additional disks on the suse manager server too. Currently it's only possible on "hosts" (aka suse manager clients).
Syntax is strictly identical to the one for hosts, i.e. you pass a list of volume ids to the `suse_manager` module:
```
additional_disk = [ {
volume_id = "${element(libvirt_volume.packages_disk.*.id, 1)}"
} ]
```
and you define the extra resources like this:
```
resource "libvirt_volume" "packages_disk" {
name = "ebi2-packages-disk"
base_volume_name = "empty_disk.qcow2"
pool = "default"
count = 1
}
```
NOTE: I wanted a more ambitious pull request, that would also do the following:
* define the disk resource for the packages
* modify `/etc/fstab` to define a mount point for `/var/spacewalk`
* do the mount
* possibly reduce the size of the …

Enable additional disk definitions on server too

---

.gitignore
modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf
modules/libvirt/host/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/openstack/base/main.tf
modules/openstack/base/variables.tf
modules/openstack/host/variables.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager_proxy/main.tf
salt/mirror/minima.yaml
salt/repos/default.sls
salt/repos/repos.d/Uyuni-Master-x86_64-Pool.repo
salt/repos/repos.d/Uyuni-Proxy-Master-x86_64-Pool.repo
salt/repos/repos.d/openSUSE-Leap-42.3-Pool.repo
salt/repos/repos.d/openSUSE-Leap-42.3-Update.repo
salt/repos/repos.d/openSUSE-Leap-Pool.repo
salt/repos/repos.d/openSUSE-Leap-Update.repo
salt/repos/repos.d/systemsmanagement-sumaform-tools.repo
salt/repos/repos.d/systemsmanagement_Uyuni_Master.repo
salt/repos/repos.d/systemsmanagement_Uyuni_Stable.repo

Uyuni is now building for OpenSUSE 15.0 only.
This PR:
- adds OpenSUSE 15.0 to base images for libvirt and OpenStack
- switches Uyuni to use OpenSUSE 15.0 as the base OS
- adds OpenSUSE 15.0 repositories containing Uyuni
- mirror repositories as per the previous point in case you are using a mirror
**Test needed**

Feat: switch Uyuni to OpenSUSE 15.0 as base image

---

salt/minion/testsuite.sls

In order for a new cucumber scenario to work properly, it would be nice to have `wget` installed at setup time.
new scenario: https://github.com/SUSE/spacewalk/pull/6906

Install wget on minion

---

salt/mirror/minima.yaml
salt/repos/repos.d/Devel_Galaxy_BuildRepo.repo
salt/suse_manager_server/testsuite.sls

Use SLE 12 SP4 instead of SLE 12 SP1 for the test packages (`andromeda-dummy` and friends).
The new packages are already built at https://build.suse.de/project/show/Devel:Galaxy:TestsuiteRepo and https://download.suse.de/ibs/Devel:/Galaxy:/BuildRepo/ .
(long story made short: I need them anyway for the new suite, so let's upgrade)

Use SLE 12 SP4 to build test packages

---

salt/repos/default.sls

Make sure `APT::Install-Recommends` is always `true` on Debian-like systems. The default and recommended behavior is to install `Recommends` on Debian.

Remove /etc/apt/apt.conf.d/00InstallRecommends on Debian

---

salt/mirror/minima.yaml
salt/repos/repos.d/Devel_Galaxy_Manager_Head_SLE-Manager-Tools-12-x86_64.repo

We have a new URL as the product definition at HEAD was changed to match what we have at SUSE:SLE-12:Update:Products:ManagerToolsBeta

Use the correct URL for SLE12 HEAD Client Tools

---

salt/suse_manager_server/testsuite.sls

OpenIPMI package is required for our tests. In SLE12 it was a dependency of
cobbler -> ipmitool -> OpenIPMI
and installed via cobbler.
In SLE15 ipmitool does not have this dependency anymore. This cause our IPMI tests to fail.
Additionally combine multiple pkg.installed into one to safe time

Open ipmi for testsuite

---

salt/controller/init.sls

The newer driver version 72 has memory leaks and is a lot slower
Use the old one as long as we do not need a newer driver because
of other reasons
This reverts commit f23a0763b2780ef5818273d89a13e030e20359cb.

Revert "use newer chromedriver version"

---

salt/controller/init.sls

First tests show that version 73  of chromium and chromedriver behaves more or less in terms of memory usage.
This PR will run during the night to evaluate if it also behaves more or less fine in terms of run time.
If it does, it will stay. If not, it will be reverted.

Try version 73 of chromium and chromedriver

---

salt/repos/default.sls

The apt daily upgrades can conflict with our package installation. This PR disables them.
(last tests and cleanup under progress)

Disable apt daily upgrades

---

salt/mirror/minima.yaml
salt/repos/repos.d/SLE-15-SP1-x86_64-Pool.repo
salt/repos/repos.d/SLE-Module-Python2-SLE-15-SP1-x86_64-Pool.repo
salt/repos/repos.d/SLE-Module-Server-Applications-SLE-15-SP1-x86_64-Pool.repo
salt/repos/repos.d/SLE-Module-Web-Scripting-SLE-15-SP1-x86_64-Pool.repo

As otherwise the image for SLE-15-SP1 was using the moving target and installing a newer build of salt (1.7) therefore braking sumaform installation as it was using RC1 (1.1).
This workaround will go away with SLE-15-SP1 GM is out.

WIP: Add SLE-15-SP1 moving target (valid until GM is ready)

---

salt/mirror/minima.yaml
salt/repos/repos.d/systemsmanagement_Uyuni_Stable.repo

Two URLs were not in minima, one is apparently wrong in the .repo file.

Bugfix: correct Uyuni Stable URLs

---

salt/controller/init.sls

Emergency fix as long as we can't reach outside SUSE with IPv6 from mgr.suse.de.
This touches only the test suite controller. Hopefully it's enough. If it's not enough, we will need a proper setting `ipv6 = no` at host level.
To be removed once the infra problems are solved.

WORKAROUND while our IPv6 infrastructure is broken

---

salt/suse_manager_server/init.sls

This prevents a non-working Tomcat after deployment.

Bugfix: avoid too old Java versions in Leap 42.3

---

salt/controller/init.sls

SUSE infra team fixed the ipv6 infrastructure :fireworks: , removing the workaround hack.

Remove IPv6 temporary workaround

---

salt/mirror/refresh_scc_data.py

Since commit [cea84f20](https://github.com/uyuni-project/uyuni/commit/cea84f20) SUSE Manager / Uyuni uses a new `product_tree.json` file from SCC. This needs to be mirrored too.

Mirror: get the new SCC product_tree.json

---

salt/suse_manager_server/initial_content.sls

- on SUMA4/Uyuni the SSL validation fails if the 'localhost' is
used as a destination for reposync check script.
Using machine fqdn grain to solve this problem.

Use fqdn instead of 'localhost' as a target for reposync

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
modules/libvirt/README.md
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/virthost/main.tf
modules/libvirt/virthost/variables.tf
salt/repos/virthost.sls
salt/top.sls

Move the virtual host documentation to the libvirt README since this is
not applicable to the clouds.
Also make the virtual host a true salt minion.
Follow up of PR #520

Virtual host improvements

---

modules/libvirt/virthost/main.tf
modules/libvirt/virthost/variables.tf
salt/repos/repos.d/SLE-Module-Server-Applications-SLE-15-x86_64-Pool.repo
salt/repos/repos.d/SLE-Module-Server-Applications-SLE-15-x86_64-Update.repo
salt/repos/virthost.sls
salt/virthost/init.sls

A bunch of fixes for the new virt host module.
Ruled out the 12 family: too much of a pain with libguestfs.

Virthost fixes

---

modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/openstack/controller/main.tf
modules/openstack/controller/variables.tf
salt/controller/bashrc

PR adds variable `http_proxy` to be used by testsuite. The variable specifies hostname and port for HTTP proxy on SUSE Manager. https://github.com/SUSE/spacewalk/issues/7726

Add variable for http proxy

---

salt/default/avahi.sls
salt/default/minimal.sls

If we set up
```
use_avahi = false
```
then it's a good idea to disable Avahi:
1. it can only improve the performance :smile_cat: ;
2. it avoids triggering some product bugs, like the dependence of base Salt grains towards name resolution (https://bugzilla.suse.com/show_bug.cgi?id=1134860);
3. it seems coherent with the expected semantics.
Note: it is **not** a fix for the presence ping problem, only a workaround.

If "use_avahi = false", then disable Avahi

---

salt/suse_manager_proxy/init.sls

This is a workaround that reduce the value for `tcp_keepalive_idle` to 20 seconds instead of 300 (default).
There is currently an issue when the SUSE Manager proxy is configured and registered on SUSE Manager. The `state.apply` which is executed to configure the proxy is doing changes on the network and it's also enabling the firewall on the proxy. It seems this is producing the already established connection from the `salt-minion` process on the proxy and the `salt-master` hangs.
Before this PR, the TCP connection (4505) will get restrablised after 300 seconds, which is making some testsuite scenario to fail.
This PR workaround this issue by reducing the `tcp_keepalive_idle` to 20 seconds. Already tested.
**NOTE:** This issue only happening in our testsuite infrastructure and not …

Reduce "tcp_keepalive_idle" value on proxy to workaround connections hangs

---

salt/suse_manager_proxy/init.sls

This PR removes the `tcp_keepalive_idle` workaround on the Proxy, and preload the `conntrack` kernel modules to actually avoid the connections to hangs when `SuSEfirewall2` is started.

Enable "conntrack" kernal modules on the Proxy to avoid hanging connections

---

modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/openstack/controller/main.tf
modules/openstack/controller/variables.tf
salt/controller/bashrc

Environment variable `SUMA_HTTP_PROXY` shouldn't be declared in `.bashrc` in case `http_proxy` is undefined or has an empty string as a value in `main.tf`.

Empty variable for http proxy should not be defined

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
main.tf.libvirt.example
main.tf.openstack-testsuite.example
main.tf.openstack.example
modules/libvirt/README.md
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/openstack/README.md
modules/openstack/minion/main.tf
modules/openstack/minion/variables.tf
salt/minion/init.sls
salt/minion/reflector.sls

An Avahi reflector can forward mDNS packets between two network cards belonging to different networks.
This PR introduces a new setting, `avahi_reflector`,  that lets a minion act as a reflector. It can then for example forward packets between the minion's `eth0` card and the network interface of a Docker container on that minion. This is needed to run the container tests of the test suite when the VMs have no DNS entries.
This PR sometimes triggers a known Avahi bug, https://github.com/lathiat/avahi/issues/117.

Let a minion contain an avahi reflector if desired

---

salt/default/init.sls
salt/default/locale.sls

This PR sets the default locale to `LANG=en_US.UTF-8` in all sumaform hosts to workaround the inconsistent state where some hosts may not have any default locale assigned.
This situations leads into `UnicodeDecodeErrors` when running `salt-ssh` from a system which does not have any default locale set.

Fix default system locale to "LANG=en_US.UTF-8" for all hosts

---

modules/libvirt/controller/main.tf
salt/controller/init.sls

This is an **emergency fix**. This PR moves controller from opensuse42.3 to opensuse15.0 to address these two problems:
1 - head test suite is not deploying anymore, displaying the error
```
Gem::InstallError: public_suffix requires Ruby version >= 2.3.
```
2 - opensuse42.3 will be deprecated soon
By changing opensuse42.3 to to opensuse15.0, we also change ruby 2.1 to ruby 2.5, which fixes the gem installation error.
Fixes SUSE/spacewalk#7928 .

Move controller from opensuse42.3 to opensuse15.0

---

salt/default/locale.sls

This PR configures `en_US.UTF-8` as default locale on SLE11 where `localectl` command is not available.

Do not use "localectl" on SLE11 systems

---

README.md

We should consider moving `moio/sumaform-images` to `uyuni-project` as well.

Update git URL at README.md

---

modules/aws/mirror/main.tf
modules/aws/mirror/variables.tf
modules/libvirt/README.md
modules/libvirt/mirror/main.tf
modules/libvirt/mirror/variables.tf
modules/openstack/mirror/main.tf
modules/openstack/mirror/variables.tf
salt/mirror/apt-mirror.list
salt/mirror/init.sls
salt/mirror/mirror.sh
salt/repos/init.sls
salt/repos/mirror.sls

To enable cloning the Ubuntu repositories, edit the apt-mirror.list
file.

Use apt-mirror to mirror Ubuntu repos

---

modules/libvirt/client/main.tf
modules/libvirt/client/variables.tf
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/host/main.tf
modules/libvirt/host/variables.tf
modules/libvirt/minion/main.tf
modules/libvirt/minion/variables.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
modules/libvirt/virthost/main.tf
modules/libvirt/virthost/variables.tf
modules/openstack/client/main.tf
modules/openstack/client/variables.tf
modules/openstack/controller/main.tf
modules/openstack/controller/variables.tf
modules/openstack/host/main.tf
modules/openstack/host/variables.tf
modules/openstack/minion/main.tf
modules/openstack/minion/variables.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager/variables.tf
modules/openstack/suse_manager_proxy/main.tf
modules/openstack/suse_manager_proxy/variables.tf
salt/default/init.sls

**Work in progress - not ready yet** 
This PR is written on top of @mcalmer 's #533 PR
The `ipv6` variable is becoming a map:
```
type = "map"
default = {
enable = true
accept_ra = true
}
```
I hesitated with a tristate, but the map is more open to future extensions (yes, I know, YAGNI...). Feel free to disagree and find the tristate simpler, it's easy to change.
As those settings are not really provider-specific, I ported them to openstack as well.
The results go to `/etc/sysctl.d/99-salt.conf`:
```
net.ipv6.conf.lo.accept_ra = 0
net.ipv6.conf.eth0.accept_ra = 0
net.ipv6.conf.eth1.accept_ra = 0
net.ipv6.conf.all.disable_ipv6 = 1
```
When disabling RAs:
- existing dynamic addresses are removed (otherwise, they time out only after a delay that is too long);
- we also make sure that the …

Make it possible to disable IPv6 (fully or only RAs)

---

salt/controller/init.sls

Install the required `npm` package and the [cucumber-html-reporter](https://github.com/gkushang/cucumber-html-reporter) js module on the controller node.
The js module is a `cucumber result output generator` based on the `JSON` output generated by Cucumber itself. For details how the [cucumber-html-reporter](https://github.com/gkushang/cucumber-html-reporter) works please refer to the plugin project itself.
The basic usage of this module is implemented in [this PR](https://github.com/uyuni-project/uyuni/pull/1008). Simply let
- Cucumber produce `JSON` output data [addressed in this PR](https://github.com/uyuni-project/uyuni/pull/967)
- have an `index.js` file to set properties and drive the module
- run `node index.js` to generate the cucumber output `HTML` result

Add cucumber-html-reporter js module on the controller node

---

modules/libvirt/controller/main.tf
modules/openstack/controller/main.tf

It's not needed anymore to specify the branch when building OS image. This PR uses the URL form shared with Docker.

Workaround for bsc#1108218 not needed anymore

---

salt/suse_manager_server/taskomatic.sls

This was addressed here https://github.com/uyuni-project/sumaform/commit/b833c7f8de3f7a1494ff0911c78770be99ec60e5, but it's not possible to connect the debugger to taskomatic.
This address the problem.

Fix taskomatic debug parameters after getting rid of Tanuki wrapper

---

salt/controller/init.sls

This is a workaround to inject [this bugfix](https://github.com/gkushang/cucumber-html-reporter/pull/181) until it is release into a newer version of the `cucumber-html-reporter` module.

HACK: workaround a not yet released bugfix of cucumber-html-reporter

---

modules/openstack/host/main.tf

Fix parsing of Host module in openstack.
This produces the following error when parsing the openstack/host/main.tf file:
Error: Error loading /home/juliogonzalez/Documents/development/git/suse/sumaform/modules/openstack/host/main.tf: Error reading provisioners for null_resource[host_salt_configuration]: parse error at 15:9: expected expression but found invalid sequence "$"

Fix parsing of Host module in openstack

---

salt/virthost/systemd-detect-virt

So we can fully reproduce exactly the same results we would get on a non-virtual instance:
```
juliogonzalez@juliogonzalez:~$ /usr/bin/systemd-detect-virt 
none
juliogonzalez@juliogonzalez:~$ echo $?
1
```
(until now we were returning 0)

Fix systemd-detect-virt to return 1

---

salt/repos/default.sls

Automatically add Ubuntu client tools based on the `product_version` specified in minion configuration.
This is useful to remove `additional_repos` to manually specify Ubuntu client tools.
Fix https://github.com/SUSE/spacewalk/issues/7888

Feat: enable Ubuntu Manager Tools by product ver

---

salt/suse_manager_server/init.sls

The `/etc/products.d/baseproduct` symlink was not set correctly.
@mcalmer this is also true for Uyuni, right?

Fix baseproduct for SUSE Manager 4

---

salt/suse_manager_server/rhn.sls

Prevents a failed deployment with Uyuni Stable and a mirror host.

Bugfix: do not assume nfs-client is installed, it might not be

---

.travis.yml
modules/libvirt/virthost/sysinfos.xsl

Since the sysinfo/chassis configuration element has been introduced in
libvirt 4.1.0 and we may test with older releases, set the chassis using
qemu arguments directly.
Fixes SUSE/spacewalk#8942

virthost: export chassis manufacturer using QEMU args

---

salt/default/avahi.sls
salt/default/hostname.sls
salt/default/set_ip_in_etc_hosts.py.jinja

It is now possible to disable IPv6 as a whole from `main.tf`:
```
ipv6 = {
enable = false
(...)
}
```
On the other hand, sumaform prepares a few IPv6 settings:
* in `/etc/hosts`
* in `/etc/avahi/avahi-daemon.conf`
no matter whether IPv6 is enabled or not.
This PR fixes this situation.

Disable ipv6 in config files when disabled by user

---

salt/controller/bashrc

add scc credentials to env variable in bashrc
Been tested locally...

add scc credentials to env variable in bashrc

---

main.tf.aws.example

I'm not sure why `var.` was used to access variables `cc_username` and `cc_password`, but they are declared in a `local` block, so they should IMHO be accessed via `local.`.
At least I needed to do that to be able to run `terraform init`.

Replace "var" with "local" in aws example

---

salt/suse_manager_server/initial_content.sls

With the new login developed in:
https://github.com/uyuni-project/uyuni/pull/564#
the page content for the login page will be rendered using JavaScript.
This means that `http.wait_for_successful_query` will never read its
exit condition, specified under `match` (because it will be rendered via
JS).
This PR changes exit condition by testing the HTTP status code received
from the server after the POST request to create the first user.
A more robust change would be:
```
-    - match: Discover a new way of managing your servers
+    - match: <script src="/javascript/manager/login/login.renderer.bundle.js
```
but it would obviously be non-compatible with older versions of the
product.

Feat: change create_first_user exit condition

---

salt/controller/run-testsuite.sh

After the improvements made in the test suite to support parallel cucumber features, that script was outdated.
In fact, I'm not sure if that code was never used before :)

Update run-testsuite to use the new rake tasks

---

salt/controller/run-testsuite.sh

Adding the proposal made in https://github.com/uyuni-project/sumaform/pull/581
New options available in run-testsuite to choice which yaml files we want to run, also having as default the current yaml files used in the testsuite pipeline, running all of them sequentially.

Adding new options to run-testsuite

---

main.tf.aws.example

This PR specifies the value of mandatory field `"owners"` when querying available images in the AWS example.
I used value `"amazon"`, which is okay for the community AMIs that I am using for SUSE BYOS images. I am not sure this value is okay for the sumaform images @moio has in mind.

Use "owners" field for existing images lookup

---

modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf
salt/client/testsuite.sls
salt/repos/default.sls
salt/repos/repos.d/systemsmanagement_Uyuni_Master_openSUSE_Leap_15-Uyuni-Client-Tools.repo
salt/repos/repos.d/systemsmanagement_Uyuni_Stable.repo
salt/repos/repos.d/systemsmanagement_Uyuni_Stable_openSUSE_Leap_15-Uyuni-Client-Tools.repo

* add client tools for openSUSE
* use `mgr-cfg-actions` instead of `rhncfg-actions` for Uyuni client tools
* server is now based on 15.1 based, not on 42.3 anymore

Support openSUSE clients for Uyuni

---

salt/controller/init.sls

https://github.com/gkushang/cucumber-html-reporter/pull/197#discussion_r320247815
https://github.com/gkushang/cucumber-html-reporter/commit/7bb1b440e5262d2f43d4e2acfd5bacfa2d8fb1c4
This way we can update the version when needed, and not automatically.

Pin cucumber-html-reporter to 5.0.2

---

salt/mirror/init.sls
salt/mirror/mirror.sh

This PR changes the behavior or the mirror. It introduces
jdupes, a tool to deduplicate RPM files present in the mirror
directory.
Fixes #586

Feat: add jdupes to dedup RPM packages

---

modules/openstack/controller/main.tf

As discussed by email.
My bad, I forgot the openstack module when upgrading the controler from 42.3 to 15.0.

Forgot the openstack module when upgrading the controller

---

salt/virthost/init.sls

Prevent deploy errors of `min-kvm` as per the default testsuite example file for libvirt.
Specifically, the libvirt daemon would not start:
```
----------
ID: libvirtd_service
Function: service.running
Name: libvirtd
Result: False
Comment: The named service libvirtd is not available
```
Moreover, `default-net_destroyed` would fail if the network is there but not active.

Bugfix: virthost would not deploy correctly

---

salt/default/testsuite.sls
salt/repos/testsuite.sls

It adds repos to ssh minion that don't get applied because the jinja if statement doesn't expand anymore. The new module minionssh has role:sshminion and this role wasn't in the list that was checked before now.

Change role to check for new module sshminion

---

salt/default/testsuite.sls
salt/mirror/minima.yaml
salt/repos/testsuite.sls
salt/suse_manager_server/testsuite.sls

In prevision for Uyuni, move RPM test packages to OBS, and merge with DEB repositories that are already there.
See SUSE/spacewalk#9392.
@mateiw, `/srv/www/htdocs/pub/TestRepoDeb` is simply removed: it does not look like you're using it.
** DO NOT MERGE BEFORE THE TEST SUITE PR CAN BE MERGED IN ALL 3 BRANCHES **

Move testsuite test repos to OBS

---

salt/repos/default.sls
salt/repos/testsuite.sls

dummy packages are currently failing because of missing GPG key. This PR adds it.
it also fixes an error of `uyuni-stable` that should be `uyuni-released`.

Forgot the GPG keys for the new repos

---

salt/repos/repos.d/Uyuni-Master-CentOS6-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Master-CentOS7-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Master-SLE12-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Master-SLE15-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Master-openSUSE_Leap_15-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Stable-CentOS6-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Stable-CentOS7-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Stable-SLE12-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Stable-SLE15-Client-Tools-x86_64.repo
salt/repos/repos.d/Uyuni-Stable-openSUSE_Leap_15-Client-Tools-x86_64.repo

We had files named eg `Uyuni-Stable-SLE12-Client-Tools-x86_64.repo` with a dash
but with content eg `[Uyuni-Stable-SLE12-Client_Tools-x86_64]` with an underscore
The test suite assumes name and filename are identical. This PR makes them identical.
Note: this is for the pre-refactoring branches. It does not affect master that comes with its own repo name problems ;smile_cat: .

Ensure repository name and filename are consistent

---

salt/repos/default.sls

This PR fixes a grains test in uyuni case that would lead to stack trace if grain is absent.

Missing default value for grains.get('product')

---

salt/suse_manager_server/master-custom.conf

In most cases, it is not enough if you modify the terraform modules at `modules/libvirt`. Check if you also need changes at `modules/openstack` and `modules/aws`.
Enable debug for salt master and api to debug connection problems when bootstrapping clients

enable debug for salt master and api

---

README_ADVANCED.md
main.tf.libvirt-testsuite.example
main.tf.openstack-testsuite.example
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/openstack/suse_manager/main.tf
modules/openstack/suse_manager/variables.tf
salt/suse_manager_server/rhn.sls

It disables token checking by default on Servers, which is convenient to consume repos from other sumaform hosts.

Disable download token checking by default

---

salt/repos/minion.sls

Since openSUSE minions have no modules, keep those for SLES minions only.

Minion: only add the container module for SLES

---

salt/mirror/minima.yaml
salt/repos/repos.d/Test-Packages_Pool.list
salt/repos/repos.d/Test-Packages_Pool.repo
salt/repos/testsuite.sls
salt/suse_manager_server/testsuite.sls

This PR adopts the new fake packages project layout as discussed by email.
master: #613

Renamed fake repositories to standard_rpm and standard_deb

---

salt/mirror/minima.yaml
salt/repos/testsuite.sls
salt/suse_manager_server/testsuite.sls

This PR adopts the new fake packages project layout as discussed by email.

Renamed fakepackage repositories to standard_rpm and standard_deb

---

salt/repos/repos.d/Test-Packages_Pool.list
salt/repos/repos.d/Test-Packages_Pool.repo

Temporary workaround, `testsuite-stable-with-new-fake-repos` branch only.
Don't use arbitrary mirrors for fake packages. Use the one in the Netherlands.
Reason: we had to keep same version and release numbers when redoing the fake packages, and this puzzles some mirrors, and others not.
Long term solution is to fix problem at mirrors.

Temporarily don't use mirrors for fake packages

---

salt/repos/default.sls

This PR add a missing `pkgrepo.managed` reference when rendering the `tools_additional_repo` state in order to avoid a failure that is caused because a malformed state.

Add missing "pkgrepo.managed" to "tools_additional_repo"

---

salt/mirror/minima.yaml
salt/repos/testsuite.sls

This PR installs the GPG key of download.opensuse.org when we run the test suite.
If we are running the testsuite, we need the fake packages,
and those are now on download.opensuse.org.
Note: This key is also installed during completly different circumstances (on RedHat client, when we are running uyuni)

Install the GPG key of download.opensuse.org

---

salt/controller/init.sls

Removing a hack about cucumber-html-reporter to add a hotfix which is already merged in 5.0.2
https://www.npmjs.com/package/cucumber-html-reporter

Remove hack for cucumber-html-reporter

---

salt/suse_manager_server/master-custom.conf

This PR removes the `log_level: debug` for `salt-master` and `salt-api` in order to prevent testsuite failures due unexpected DEBUG output while checking pillar data.

Remove DEBUG log_level for salt-master and salt-api

---

salt/repos/testsuite.sls

Uniforms the name of a repo to keep code cleaner on the Cucumber testsuite.

Uniform the repo name on Ubuntu clients

---

salt/mirror/minima.yaml

In most cases, it is not enough if you modify the terraform modules at `modules/libvirt`. Check if you also need changes at `modules/openstack` and `modules/aws`.
Fixes 2 issues:
1. testsuite repos must be synced with all archs incl. source packages
2. add Ubuntu devel repos

Fix mirror config

---

salt/mirror/minima.yaml
salt/repos/suse_manager_proxy.sls
salt/repos/suse_manager_server.sls

As part of the new Uyuni product definitions, we are removing the version from the POOL repositories. And we decided to remove the distribution name from the URL as well (so it's now `images` so we don't need to change it when we change the base OS.
This means than in the future no sumaform changes will be needed for new Uyuni versions or base OS changes (also good for development)
Requires https://github.com/uyuni-project/uyuni/pull/1535

Use new Uyuni POOL repositories

---

README_ADVANCED.md
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager/variables.tf
modules/libvirt/suse_manager_proxy/main.tf
modules/libvirt/suse_manager_proxy/variables.tf
salt/suse_manager_proxy/additional_disk.sls
salt/suse_manager_proxy/init.sls
salt/suse_manager_server/additional_disk.sls
salt/suse_manager_server/init.sls

Related task: https://github.com/SUSE/spacewalk/issues/9486
> Note: I had issues testing from master, so my only choice was to move to this temporal branch, where I succeded with the contribution. 
Adding support for an additional disk mounting in /var/spacewalk
On susemanager_server and susemanager_proxy on libvirt provider.
Example main.tf
```
provider "libvirt" {
uri = "qemu:///system"
}
module "base" {
source = "sumaform/modules/libvirt/base"
cc_username = "xxxxx"
cc_password = "xxxxx"
pool = "obarrios_disks"
additional_network = "192.168.6.0/24"
name_prefix = "oba-"
images = ["sles15sp1"]
}
module "server" {
source = "sumaform/modules/libvirt/suse_manager"
base_configuration = "${module.base.configuration}"
product_version = "4.0-nightly"
name = "server"  
repository_disk_size = …
```

Support for additional disk in server & proxy mounting in /var/spacewalk

---

salt/top.sls

Remove the space that prevented setting up virthosts properly

Fix virthost matching in top.sls

---

modules/cucumber_testsuite/main.tf
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/host/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf

Refactor in the host module to return a list of hostnames instead of the hostname of the first domain created.
Adapt modules that use this field to behave according.

Multiple hostnames in host module

---

salt/repos/default.sls
salt/repos/suse_manager_proxy.sls
salt/repos/suse_manager_server.sls

This explains https://github.com/uyuni-project/sumaform/pull/634#discussion_r345767666
Only basesystem is part of `default.sls`, all other modules for server and proxy are part of `suse_manager_server.sls` and `suse_manager_proxy.sls`.
So if we add a new OS for new SUSE Manager or Uyuni versions, we also need to change `default.sls`

Basesystem repos are part of default.sls

---

modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf
salt/suse_manager_proxy/additional_disk.sls
salt/suse_manager_server/additional_disk.sls

Related to https://github.com/uyuni-project/sumaform/pull/615/files#r345705770
To make the port to other backends, at that moment only AWS, we pass via grains the device name.

Device name for additional disk passed via grains

---

modules/libvirt/controller/main.tf
salt/controller/init.sls

Now it works with this PR merged https://github.com/SUSE/spacewalk/pull/9753
Update the controller to openSUSE 15.1. Part of https://github.com/SUSE/spacewalk/issues/9798

Update controller to opensuse151

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

Adds the controller's `git_repo` variable to `cucumber_testsuite`

cucumber_testsuite: add git_repo variable

---

modules/libvirt/base/main.tf
modules/libvirt/base/variables.tf

For each volume, we had one resource block. However, all block are very similar so we can abstract them in one single resource block with "for_each".
Added a map with the URL for each base image. Now add support to a new volume we just need to add the volume base URL to the "image_urls" local variable.
Documentation: https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings

refactor base module with for_each in volumes

---

salt/repos/default.sls

Rework the repository saltstates so that they are generated by jinja instead of being hard coded.
This applies to the base repos and Galaxy repos. I did not touch the SLE11 repos since I have not used sumaform to generate such machines and their paths are dissimilar enough to not fit in the same template.

DRY for SLES and Galaxy paths

---

TROUBLESHOOTING.md

Update `taint` wiki according to the new command interface
Using the previous command with the `-module` parameter I get the error message:
```
The -module option is no longer used. Instead, include the module path in the main resource address, like "module.foo.module.bar.null_resource.baz".
```

Update taint wiki according to the new command interface

---

salt/mirror/minima.yaml
salt/repos/minion.sls

It prepares for testing with SLE 15 SP1 clients
* SLE 15 SP1 development tools repos are needed for Kiwi
* SLE 15 SP1 Python2 repos are needed for Docker
(3.2 and 4.0 only; one can build containers with Python3 on 4.1)
* Using SLE 15 SP1 for containers too
* Mirror developement tools in minima
(Python 2 and Containers seem OK already)
See also uyuni-project/uyuni#1721 for the cucumber side

Adaptations for SLE 15 SP1 clients - batch 1

---

modules/cucumber_testsuite/main.tf
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/host/main.tf
modules/libvirt/locust/main.tf
modules/libvirt/pxe_boot/main.tf
modules/libvirt/suse_manager/main.tf
modules/libvirt/suse_manager_proxy/main.tf

Purpose of this PR is to avoid the following error and similar circumstances:
```
Error: Error in function call
on modules/libvirt/host/main.tf line 30, in resource "libvirt_domain" "domain":
30:           "volume_id" = element(libvirt_volume.main_disk.*.id, count.index)
|----------------
| count.index is 0
| libvirt_volume.main_disk is empty tuple
```
Crucial point here is that `libvirt_volume.main_disk.*.id` might be an empty tuple (because of an in-progress destruction, because state is inconsistent or simply because it was so configured), but we might still try to access element 0 (the first).
This PR tries to address the problem comprehensively and is **best reviewed commit-by-commit**.

Fix empty lookups

---

README_TESTING.md
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
modules/libvirt/controller/variables.tf

That PR make client and minion optional when we set up a main.tf that includes a controller.
Related PRs:
https://github.com/SUSE/spacewalk/pull/10341

All clients optional

---

salt/controller/bashrc

Also add some consistency to this .bashrc file
This PR moves the lines
```
APPEND_BASHRC="
PORTUS_URI=portus.mgr.suse.de:5000/cucutest
PORTUS_USER=cucutest
PORTUS_PASS=cucusecret"
```
from the runner to sumaform, in a way that the test suite works even if we don't use the runner. For now, these variables are hardcoded, but it's easy to make them real terraform variables if the need arises.
It also does some clean up in the code that generates `.bashrc` to increase overall consistency. In particular, variable `ssc_credentials` is now uppercase `SCC_CREDENTIALS`. 
* Issue SUSE/spacewalk#5665
* Runner https://gitlab.suse.de/galaxy/sumaform-test-runner/merge_requests/207/
* Test suite uyuni-project/uyuni#1755

Add portus URI and credentials in sumaform

---

modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
salt/controller/bashrc

Follow-up of #662: get the portus variables from terraform variables.
It also does a small revert of a line in the previous PR.

Pick portus variables from main.tf

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
modules/libvirt/controller/main.tf
modules/libvirt/controller/variables.tf
modules/libvirt/pxe_boot/main.tf
salt/controller/bashrc

This PR:
* renames `PXEBOOTMAC` test suite variable to `PXEBOOT_MAC`
(that's the way to identify the PXE boot minion as it does not have an IP in main network)
* introduces a new variable `PXEBOOT_IMAGE` that contains the operating system
we want to install on it via PXE
(was previously hardcoded)
* determines the latter automatically as identical to the starting operating system
on that minion, so if eg we have SLE 15 SP1 on the PXE boot minion, we will reinstall
a SLE 15 SP1 system via PXE.
(doing so ensures a certain level of idempotency of tests)
Testsuite: uyuni-project/uyuni#1762

New PXEBOOT_IMAGE variable

---

salt/mirror/minima.yaml
salt/repos/default.sls
salt/repos/server.sls

This PR fixes two issues I've found on the `repos` state:
- Fix Uyuni Stable POOL repository url after 202001 release (the URL changed)
- Do not break "repos" state when system is "rhel/centos" and `product_version` is undefined.

Fix some fixes when applying "repos" state

---

salt/controller/init.sls

Changes the state fix_cucumber_html_reporter_style to require the install_cucumber_html_reporter_via_npm still but it's a cmd not sls. It will fix the failing deployment on HEAD. Tested locally on m226 already for head

Change requirement to match state cmd

---

modules/cucumber_testsuite/main.tf

This PR adds the OS released updates to the KVM virtualization host too.
(BTW, the test suite module has no Xen virtualization host).

Use released updates on virthost too

---

README_TESTING.md
modules/controller/main.tf
modules/cucumber_testsuite/main.tf

Allow outputs at the cucumber_testsuite module.
So we can get the hostnames from the `terraform.tfstate` as it was the case in the past.
Ugly thing: unlike with the old sumaform and terraform 0.11, this prints the outputs on-screen. Not sure if it can be avoided.

Allow outputs at the cucumber_testsuite module

---

backend_modules/libvirt/README.md

- backend_modules/libvirt/README.md: Update it with the right location for the list
of supported images.

Show the right location of the list of the supported images

---

salt/minion/init.sls

This PR adds `start_event_grains`  config param, in order to pass grains to the minion start event. 
Related PR:https://github.com/uyuni-project/uyuni/pull/1833

Add config param to pass grains to the minion start event

---

README_ADVANCED.md
salt/default/avahi.sls
salt/minion/reflector.sls

This PR makes sure we use our own custom version of Avahi, whenever it is enabled (even if we use no reflector).
This custom version solves the "spurious names conflict" bug (https://bugzilla.suse.com/show_bug.cgi?id=1163683). It is meant to slowly disappear as Avahi 0.8 is out with the fix, as the fix is backported to Avahi 0.7 in SLE 15, and as SLE 12 gets deprecated.
This is using repositories that are currently under `home:ebischoff` in OBS. @moio, maybe you  rather want it under some Sumaform project? That could also spare us an extra repo.

Use custom version of Avahi

---

README_ADVANCED.md
backend_modules/libvirt/README.md

Document how to use libvirt's dnsmasq for DNS resolution.
This is a must when there are Windows guests, as mDNS is broken on Windows due to wrong decisions by Microsoft back in the day.

Document libvirt dnsmasq for DNS of non-.local domains

---

README_ADVANCED.md
salt/mirror/init.sls
salt/mirror/mirror.sh
salt/mirror/mirror.sh.conf

So now cron will send email to the administrator **only if** there are errors.
It also allows a more flexible usage of mirror.sh, for example to spread execution of each step... or to define a reduced set of repositories with a new yaml file, and run a second cron job with that an extra time each day.
This comes from the SUSE Manager internal repository, as we precisely needed that.
I am also porting a fix from @mcalmer for handling of the nvidia repo. Sorry for not using a separate PR, but I was not aware our script was taking from sumaform :-)

Improve mirroring wrapper that handles errors in all cases

---

salt/proxy/init.sls

See corresponding bug. Fix has already been verified. Trivial.

proxy templates have been moved outside of doc hierarchy (bsc#1166284)

---

salt/mirror/mirror.sh

Adapt the nvidia repositories for any SLE version.
Until now the code was only working for SLE15GA.
As a reminder: this is needed because the nvidia repositories (if even if https://github.com/uyuni-project/minima/issues/18 gets fixed) do not provide the same format as Uyuni/SUSE Manager expects from a RMT mirror, with the target distribution at `RPMMD`

Adapt the nvidia repositories for any SLE version

---

salt/controller/run-testsuite

To support the change made in our YAML files, we need to add the new sanity check stage into the run-testsuite command.
I added it to the sequential and parallel test suite executions, leaving the "essentials" run without it.

Add new sanity check stage into the run-testsuite command

---

salt/default/avahi.sls

This PR works around this bug: https://bugzilla.suse.com/show_bug.cgi?id=1168306
It sets apparmor so that the resolver can read /etc/mdns.allow.

Let the resolver work correctly with multicast DNS

---

backend_modules/libvirt/host/main.tf

- in Retail, with only 1 GB, systemd fails at second reboot with "cannot fork"
- in Yomi, with only 1.5 GB, the oom-killer kills salt-minion process at second boot

change pxe_boot memory used in libvirt

---

README_TESTING.md

- Fix a couple of typos.
- Update instructions to enable/disable a feature in the testsuite: run_sets/testsuite.yml is no
longer under VC (mention other YAML files instead).

Update instructions to enable/disable features in the testsuite

---

salt/default/avahi.sls

We need a custom repository for our test packages (`orion-dummy` and friends) also for SLE 11.
This PR also fixes a bug: the states file `avahi.sls` is run twice, the first time with `osmajorrelease` grain undefined. This resulted in wrong evaluation of the release the first time.
Fixes: SUSE/spacewalk#11002

Use a custom version of avahi for SLE 11 as well

---

backend_modules/libvirt/README.md
backend_modules/libvirt/host/main.tf

For some reason the host-model CPU mode may not show the VMX flag on the
virtual CPU while the host-passthrough blindly passes every flag from
the physical CPU.

virthost: use host-passthrough rather than host-model

---

salt/first_deployment_highstate.sh

This PR introduces a retrying mechanism in case `salt-call` is temporary crashing after the initial `default.minimal` state is applied on any host: i.a. during the salt upgrade.
On any sumaform deployment, the first `salt-call` executed on a deployed system is made in order to apply the `default.minimal` state, which does some minimal host configuration and upgrade Salt to the latest version available. 
Since we know that "upgrading Salt with Salt" sometimes causes problems, we already ignore possible errors from the initial `salt-call` and allows the script to continue running, but this is not enough.
In some particular cases, we see the initial `salt-call` crashing because Salt being updated but we simply triggers the second `salt-call` without checking that `salt-call` is not crashing …

Add retrying mechanism after "default.minimal" state is applied

---

README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
salt/controller/bashrc

Add a new VM 'buildhost'
The idea is to have one VM for the 'salt minion' and another VM
for the 'Docker and Kiwi build host' in the Cucumber test suite.
This change adds flexibility to the test suite; by decoupling the 'salt minion'
from the build host we a are able to test more minion versions (not just
those with a build host functionality available).
Another advantage is a reduction in the number of clean up scenarios
(the slow readd entitlements).
See https://github.com/SUSE/spacewalk/issues/10680
- modules/controller/variables.tf
Add buildhost configuration.
- modules/cucumber_testsuite/main.tf
Add min-build module section.
Remove avahi_reflector from the normal minion; keep it only for the min-build.
- salt/controller/bashrc:
Export environment variable with the build host …

Add buildhost VM

---

backend_modules/aws/README.md
backend_modules/aws/README_ADVANCED.md
backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf
backend_modules/aws/network/main.tf
backend_modules/aws/network/variables.tf

https://github.com/SUSE/spacewalk/issues/11396
Add support for the additional network on aws backend.
An additional network is always created. By default, it has the ip mask 172.16.2.0/24.
This network only allows connections between host on the network, this means not in-bound or out-bound communication
The goal of this network configuration is to simulate client scenarios where minions are placed in a totally independent network, only reachable through a susemanager proxy.
Bastion host is connected with two networks: public (which also allow connections to private network) and the additional private network.
The approach followed on libvirt, which only creates the additional network if the field named `additional_network` where defined on …

add support for additional network

---

salt/repos/default.sls

https://github.com/SUSE/spacewalk/issues/11454
After stop all apt services make sure lock is released before continue to apt update steps.
The code checks if the file don't exist or if exist it is not locked by another process.

Ubuntu 1804 unable to get apt lock when updating salt

---

backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml

Add support for rhel 8 and rhel 7 images on aws.
At the moment this PR is using community images provided by red Hat.
https://github.com/SUSE/spacewalk/issues/11453

AWS: add image support for RHEL 7/8

---

backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/network_config.yaml
backend_modules/libvirt/host/user_data.yaml
salt/controller/bashrc
salt/mirror/apt-mirror.list

Issue: https://github.com/SUSE/spacewalk/issues/11489
Draft PR to add ubuntu 20.04 image support for libvirt and aws.
After clients tools get published on Uyuni, we need to update the repositories in use on cloud-init user data.

Ubuntu2004 image support on libvirt and aws

---

salt/repos/default.sls

This PR renames a repo to the name that is expected by the test suite.
Needed by openSUSE clients.

Test suite expects "tools_pool_repo" as a name

---

salt/repos/default.sls
salt/repos/minion.sls

This PR reverts commit 0a0391dccc49233a2f089be2c6b6e511c62202bb from 17 October 2019. 
That commit tried to revert to old repositories names in sumaform, while the issue was already fixed on the test suite side by switching to the new names on 16 October 2019 in commit  SUSE/spacewalk@05a0aa0fbde999e8e6412a49bd965d333ec8d7fa .

Revert change to old repositories name

---

salt/mirror/minima.yaml

Enable SUSE Manager 4.1 on the mirror. Do not merge yet. I need the product definitions building at 4.1 devel project (in a few days)
3.2 are not used by any product since 4.0 GM was published, and are not needed anymore.

Enable SUSE Manager 4.1 on the mirror

---

backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
backend_modules/null/host/variables.tf
main.tf.uyuni.example
modules/base/variables.tf
modules/cucumber_testsuite/variables.tf
modules/host/variables.tf
modules/proxy/main.tf
modules/server/main.tf
modules/sshminion/variables.tf
modules/virthost/variables.tf
salt/mirror/minima.yaml
salt/repos/proxy.sls
salt/repos/server.sls

Add openSUSE Leap 15.2 and move Uyuni Master to it
Libvirt image: https://build.opensuse.org/package/show/systemsmanagement:sumaform:images:libvirt/opensuse152
OpenStack iamge: https://build.opensuse.org/package/show/systemsmanagement:sumaform:images:openstack/opensuse152

Add openSUSE Leap 15.2 and move Uyuni Master to it

---

backend_modules/libvirt/base/main.tf

Use GM image for official SLES15SP2 image. The previous URL doesn't exist anymore (and it was Snapshot7)

Use GM image for official SLES15SP2 image

---

README_ADVANCED.md
modules/controller/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/mirror/minima.yaml
salt/repos/default.sls

- Add 4.1 to the doc
- Enable default images for 4.1
- Adjust variables descriptions for 4.1
- Change all SUSE Manager versions to use 4.1 client tools
- Enable Maintenance Test repositories for SLE15SP2 and 4.1 on the mirror
I tested a cucumber environment creation locally based on 4.1-nightly. Worked fine.

Add missing stuff for 4.1

---

.travis.yml

force installed version of importlib-metadata
This library is a transitive dependency from coala.
We are getting some conflicts on version number
since another transitive library is depending on
this one (stevedore)

force installed version of importlib-metadata

---

.ci-travis/salt-client-validation
.ci-travis/salt-ctl-validation
.ci-travis/salt-minion-validation
.ci-travis/salt-server-validation
backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/null/base/main.tf
backend_modules/null/base/variables.tf
backend_modules/ssh/base/main.tf
backend_modules/ssh/host/main.tf
main.tf.libvirt.example
main.tf.ssh.example
main.tf.uyuni.example
modules/base/main.tf
modules/base/variables.tf
salt/default/init.sls
salt/default/minimal.sls
salt/default/ntp.conf
salt/default/time.sls

Experimentation proved we could have up to 5 minutes offset between the different machines deployed by sumaform. It's not only a problem for the test suite, but could hit the operation of SUSE Manager itself.
Corresponding issue: https://github.com/SUSE/spacewalk/issues/11934
Test suite part: uyuni-project/uyuni#2413
Implementation details:
* there's a new option, `use_ntp`, that is `true` by default, and that enables you to disable this code.
* the old `timezone` stuff moves to the new `time.sls` states file.
* CentOS and Ubuntu are not handled because they are already correct, as far as I can see
Concerns with current code:
* what happens with vanilla hosts? I guess we will get this stuff (?) as I call it from `minimal.sls`. Do we really want that?
* probably too many `use_ntp` here and …

Install NTP on most hosts

---

salt/default/chrony.conf
salt/default/time.sls

Follow-up of #729.
It looks like `chronyd` needs to be properly configured too.

Add a configuration file for chrony too

---

salt/default/time.sls

follow-up of recent chrony and ntp additions, this time for SLE 11 SP4

SLE 11 SP4 uses "service ntp start"

---

salt/virthost/init.sls

Restarting the network is suspecting to cause weird terraform failures
like the following:
remote command exited without exit status or exit signal

virthost: don't restart network

---

salt/default/avahi.sls

Convert a int-string comparison into a int-int one.
The int-string comparison is always False, and it causes to always choose the 'else' branch. 
- salt/default/avahi.sls: Filter the grain as an integer
before the comparison.

Fix grains integer comparison

---

README_ADVANCED.md
modules/client/main.tf
modules/client/variables.tf
modules/host/main.tf
modules/host/variables.tf
modules/minion/main.tf
modules/minion/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/sshminion/main.tf
modules/sshminion/variables.tf
salt/default/firewall.sls
salt/default/minimal.sls
salt/default/network.sls
salt/server/firewall.sls

Instead of removing firewall packages which will be needed
by susemanager we now disable the firewall with a parameter
if it is needed.
PR relates to: https://github.com/uyuni-project/sumaform/pull/725
Solves: https://github.com/SUSE/spacewalk/issues/12012

Do not remove firewall packages but disable it

---

salt/proxy/init.sls
salt/server/init.sls
salt/server/initial_content.sls

As Uyuni/SUSE Manager Server/Proxy require more than updating packages in order for them to be upgraded, do not attempt just updating the packages.
In normal cases (first installations) no change in behavior is expected. When re-applying highstate at a later point in time, do not leave Servers/Proxies in a half-upgraded state.

Avoid upgrading on state re-apply

---

salt/repos/minion.sls

This PR fixes few issues on the repository definition for SLE15 (all SPs) minions:
- Set the right SP repository for the SLE modules (not always SP1)
- Add "SLE-Modules-Desktop-Applications" repository which is required by already added "SLE-Module-Development-Tools"
This PR should fix issues due a mix of SP1 and SP2 repos on SLE15SP2 minions, and also the issues on the Uyuni:Master testsuite regarding "applying highstate on build host".

Fix the minion repositories for SLE15 systems (all SPs)

---

salt/mirror/minima.yaml

Missing SLE15SP2 repo for desktop product
Having such commented repos is done so we can just `s/SP2/SP3/g` that part when SP3 beta is ready, and uncomment the lines.

Missing SLE15SP2 repo for desktop product

---

salt/mirror/minima.yaml
salt/repos/default.sls

Adds missing repos to support CentOS 8 minions/clients using the `centos8o` image with a mirror.

Add RES8 repos to mirror

---

salt/repos/default.sls

Differently than zypper, yum does not invalidate cached repo metadata if
a repo's URL changes, this can lead to situations in which package
downloading is attempted from the wrong URL.
This has been reproduced on 4.0-released traditional clients with the
centos7o image.

Cleanup repo metadata after repo changes in CentOS

---

salt/minion/testsuite.sls

Make conditions more precise to match current reality.

Testsuite: openSCAP is only supported for Ubuntu minions from 18.04 on

---

backend_modules/libvirt/host/user_data.yaml

Apparently qemu-ga is installed but not started by default at least on CentOS 6, leading to terraform-provider-libvirt errors at deploy time.
This is a tentative fix.

Start qemu-ga at cloud-init stage on CentOS 6

---

salt/client/testsuite.sls

CentOS 6 has 2 packages for manual pages:
```
man man-pages
```
where CentOS 7 has 3:
```
man man-db man-pages
```
This PR avoids installing `man-db` on CentOS 6.
Note: the version comparaison is between two strings: it will probably use lexicographic order. HCL syntax is not clear in this respect... I took https://github.com/uyuni-project/sumaform/pull/755/files from Silvio as an example.

There is no man-db package on CentOS 6

---

salt/minion/testsuite.sls

The previous if the statement was wrong.
As if the host was a Ubuntu and higher version than 16.04 it was installing something, but in the `else` case, if you had an Ubuntu with 16.04 it went through the else statement.
What it does now is, only install `openscap-utils` package if it is not a Ubuntu, and only  `libopenscap8` ,`ssg-debderived` if the version of Ubuntu is higher than 16.04.

Fix openscap on Ubuntu16

---

salt/server/init.sls

It uses the modern name for former `migration.sh` script

Use modern script name

---

salt/repos/default.sls

Prevents a traceback on vanilla hosts
Fixes #764

Default to stable Uyuni tools for Ubuntu hosts

---

backend_modules/libvirt/README.md

The first part of the link command (`../backend_modules/libvirt`) is currently relative to the `modules` folder, the second part (`modules/backend`) is relative to the repository root. As it is, the command will fail because the paths don't line up.
Fixes a small inaccuracy in the libvirt configuration guide.

Fix incorrect link command in libvirt readme

---

README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc
salt/minion/testsuite.sls

configure a different container registry for the testsuite 
Part of a series of PRs in different repos:
https://github.com/uyuni-project/sumaform/pull/716
https://github.com/SUSE/susemanager-ci/pull/78
https://github.com/uyuni-project/uyuni/pull/2224

specify an alternative container registry (without auth) for the testsuite

---

TROUBLESHOOTING.md

I was having resolution problems with Avahi on an openSUSE 15.2 host trying to resolve a sumaformed Uyuni server:
```
opensuse # avahi-resolve -n uyuni.tf.local
uyuni.tf.local 192.168.122.154
ping: uyuni.tf.local: Name or service not known
PING 192.168.122.154 (192.168.122.154) 56(84) bytes of data.
64 bytes from 192.168.122.154: icmp_seq=1 ttl=64 time=0.245 ms
```
The problem disappears when I change Avahi configuration in the Uyuni host to use the first-level domain `local` (instead of `tf.local`).
Turns out that in the newest version of `nss-mdns` (shipping with OpenSUSE 15.2), second-level `.local` domains must be explicitly allowed to be resolved in `/etc/mdns.allow` AND `mdns` (not `mdns_minimal`) must be used in `nsswitch.conf`.
The latter is already covered in the troubleshooting, …

Fix: add section to troubleshoot Avahi and mDNS

---

TROUBLESHOOTING.md

Add information about zypper not installing docs on JeOS images.

add information about package missing docs

---

backend_modules/libvirt/base/main.tf

Update centos8o with the latest stable image (8.2.2004).
- backend_modules/libvirt/base/main.tf (centos8o):
Point url to the latest CentOS 8 image.

Update centos8o with the latest released image

---

backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/user_data.yaml

This PR changes `user_data.yaml` to use the mirror in the case of libvirt backend, like we already do with aws backend.

WIP Use mirror in cloudinit too

---

backend_modules/libvirt/host/user_data.yaml

This PR solves a problem with ubuntu 16.04 official image:
```
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

Allow unauthenticated packages on ubuntu 16.04

---

backend_modules/libvirt/host/user_data.yaml

This PR takes current values of the GPG key for;
* http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1604-Uyuni-Client-Tools/xUbuntu_16.04/Release.key
* https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/Release.key
We take profit of the occasion to switch from `Master` to `Stable` for Ubuntu 20.04.
We also start QEmu guest agent, which apparently does not start anymore automatically on Ubuntu 20.04

Update Ubuntu's keys, and switch to stable

---

modules/controller/main.tf
salt/controller/init.sls

This PR upgrades the controller default image from opensuse150o toopensuse152o
It might need additional packages here:
https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/host/user_data.yaml#L100-L101
And upgrade versions here:
https://github.com/uyuni-project/sumaform/blob/master/salt/controller/init.sls#L60-L68
But let's give it a try first without any more change.

Upgrade controller image to opensuse152o

---

modules/controller/main.tf
salt/controller/init.sls

Reverts uyuni-project/sumaform#779
We have problems on Leap 15.2 not supporting VA
suma-41-ctl:~/spacewalk/testsuite # /usr/lib64/chromium/chromium --no-sandbox --disable-dev-shm-usage --headless --disable-gpu-sandbox
[1015/154337.242264:ERROR:vaapi_wrapper.cc(422)] Could not get a valid VA display

Revert "Upgrade controller image to opensuse152o"

---

salt/server/testsuite.sls

The SUSE Manager server uses minima to get a copy of the test packages
moio -> uyuni-project
v0.4 -> v0.11
Note: it would be better to get test packages directly, as already stated in SUSE/spacewalk#9429 . This would remove the minima dependency as a side effect.

Use latest release of minima on server

---

salt/wait_for_salt.sh

This prevents from lines as the following one in the output:
... minion.module.host.null_resource.provisioning[0] (remote-exec): /root/salt/wait_for_salt.sh: line 7: salt-call: command not found
- salt/wait_for_salt.sh:
Redirect both, stdout and stderr to /dev/null.

Reduce noise in the sumaform log

---

salt/repos/default.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/repos/virthost.sls

Fix some mirror repo urls.
- salt/repos/proxy.sls
- salt/repos/server.sls
- salt/repos/virthost.sls
- salt/repos/default.sls:
The prefix `/ibs/` is also part of the url in the mirror for those urls as `/ibs/SUSE:/...`

Fix some mirror repo urls

---

backend_modules/libvirt/host/user_data.yaml

Add support to mirror OBS repositories.
What this PR doesn't do is to suppport mirror for other repos like:
```
baseurl: http://download.fedoraproject.org/pub/epel/6/$basearch
mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
```

Support mirroring OBS packages in our cloudinit

---

salt/mirror/mirror.sh

Create /srv/mirror in mirror.sh script, otherwise, the "chmod -r 777" gets executed in / !!!

Create /srv/mirror in mirror.sh script

---

salt/client/testsuite.sls
salt/minion/testsuite.sls

The openSCAP packages were installed half in sumaform, half in the test suite, leading to a huge mess.
This situation is due to the fact that the QAM test suite does not use sumaform's `testsuite` module. But besides this immediate reason, it has always been wrong to let sumaform prepare ulterior processings. sumaform should prepare machines as pristine as possible.
This PR lets the test suite do all the job. See uyuni-project/uyuni#2880 for implementation on test suite side.

Let the test suite install OpenSCAP packages

---

modules/cucumber_testsuite/variables.tf
modules/virthost/variables.tf

This PR fixes the **SLES15SP3** image id introduced in https://github.com/uyuni-project/sumaform/pull/792.
The image id should be `sles15sp3o` instead of `sle15sp3o`, otherwise the following error is raised during `terraform apply`, when `images` is not explicitly set on `main.tf`:

Fix 'sles15sp3o' image id

---

.travis.yml

Set `bandit` python dependency to version `1.6.2` to fix the error currently happening in github actions.
Bandit dependency on is last release (`1.6.3`) bump the version for dependency `PyYAML` from version `3.13` to version `5.3.1` [1].
Coala have a dependency from bandit set to `bandit~=1.2` and also dependes on `pyyaml~=3.12` [2]. This pop up an error:
```
There is a conflict in the version of a dependency you have installed and the requirements of coala. This may be resolved by creating a separate virtual environment for coala or running `pip install "PyYAML>=5.3.1"`. Be aware that the latter solution might break other python packages that depend on the currently installed version.
```
[1] https://github.com/PyCQA/bandit/pull/588/files …

fix bandit python dependency at 1.6.2

---

README_ADVANCED.md
modules/controller/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/mirror/minima.yaml
salt/repos/default.sls
salt/repos/proxy.sls
salt/repos/server.sls

Adds something similar to what `4.2-released` will be, but using beta channels for the clients.
So if you specify `4.2-beta`, you get:
- Server: SLE15SP3 pool + update repos (for whatever milestone is out) + 4.2 beta pool + update repos  (for whatever milestone is out)
- Proxy: SLE15SP3 pool + update repos  (for whatever milestone is out) + 4.2 beta pool + update repos  (for whatever milestone is out)
- Client tools: The usual OS repositories + pool and/or beta repos (depending on the OS, for whatever milestone is out)
Requested by QA so they can use it for the QAM testsuite during milestone validations (https://github.com/SUSE/spacewalk/issues/13202)
Also:
- Simplify Ubuntu repo management
Tests:
In all cases I used a `tf` file that defined: Server, Proxy, SLE11 Traditional Cllient, …

Add 4.2-beta to sumaform

---

salt/controller/run-testsuite

This PR adds a `qam` option to `run-testsuite` script.
It's only half of the story, at some point we will need to have both `qam-prepare` and `qam-run`.

Make it possible to run QAM testsuite from script

---

salt/controller/init.sls

This PR solve a problem starting when we published our twopence gem in rubygems, as now it will try to use the latest version which comes from rubygems.
For this, it needs all the native extensions, otherwise it fails on the `bundle install` step.

As we published the twopence gem in rubygems, we need to install all native extensions dependencies

---

salt/repos/default.sls

libvirt-libs is in Base System Module while libvirt-client is in Server
Applications Module. We were including on the Server Applications Module
and so libvirt-libs was not found.

Add Base System Module to get libvirt-libs

---

salt/client/testsuite.sls

Related to https://github.com/SUSE/spacewalk/issues/13314
By default in our official image, from sumaform, we have pre-installed:
```suma-qam-41-min-sles12sp4:~ # rpm -qa| grep cryptography
python-cryptography-1.3.1-7.10.1.x86_64
```
That results on this issue, at boostrap:
```* registering
From cffi callback <function ssl_verify_callback at 0x7f3797639488>:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 214, in wrapper
_lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
An error has occurred:
rhn-plugin: The SSL certificate failed verification.
See /var/log/up2date for more information
```
But in our repos we have the proper version 2.1.4:
zypper actually display the correct version is also available 
```S …
```

Fix SLES12SP4 python-cryptography dependency issue with its version

---

backend_modules/libvirt/host/user_data.yaml

As the official CentOS6 repositories were closed.
This PR changes the CentOS6 Base and Updates repositories URLs, to use another server that backups them.
Related to https://github.com/SUSE/spacewalk/issues/13615 and https://github.com/SUSE/spacewalk/issues/13658

CentOS6 deprecated repo, using archived repo

---

salt/server/init.sls
salt/server/release-notes-workaround.sls

Comment the extra includedir line in sudoers to prevent including twice
the files in /etc/sudoers.
This workaround will be mentioned in the release notes for 4.2.
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

add workaround for bsc#1181283

---

salt/virthost/init.sls

Work around https://bugzilla.suse.com/show_bug.cgi?id=1181264

Workaround wrong 50-xen-hvm-x86_64.json on KVM hosts

---

salt/server/release-notes-workaround.sls

The bug only affects SLE15SP3, meaning @includedir is only added in SLE15SP3
By having commented #includedir, I introduced a bug for previous
products based on SLE15SP2 or older, which was that there was no includedir
so sudo was not working on those products.
Let's comment the one that starts with @ so it only affects SP3.

fix workaround for bsc#1181283

---

backend_modules/libvirt/base/main.tf

Update opensuse150o image URL
They have dropped the soft link to the latest image;
update the URL to refer directly to the latest snapshot.
- backend_modules/libvirt/base/main.tf (opensuse150o)
Update image URL.

Update opensuse150o image URL

---

backend_modules/libvirt/base/main.tf

The image at SLE-15-SP3-Full-TEST is updated quite often.
Instead, use the one at SLE-15-SP3-JeOS-Snapshot9.
- backend_modules/libvirt/base/main.tf (sles15sp3o):
Update image URL.

Update sles15sp3o image

---

salt/repos/proxy.sls
salt/repos/server.sls

As SCC still not contains the latest packages for the Server and Proxy modules, we need to use IBS repositories for 4.2-beta product version

4.2 beta version of server and proxy modules have to point to IBS images

---

salt/repos/proxy.sls
salt/repos/server.sls

Change the 4.2 beta url to match mirrors without changing for default
Because for download.suse.de the url doesn't change, but our mirror script put the folder of the product with the /ibs/ as well so we need that in the end result url.

Change the 4.2 beta url to match mirrors without changing for default

---

salt/controller/init.sls

Inside the controller, we only make use of the `testsuite` folder, so there is no need to download the rest of the repository.
Also, we increase the depth of the shallow-clone to 100 commits, so we can compare and navigate from the last 100 commits.
We need that in order to extract, during our test suite pipeline the product commit changes between to test suite executions (Internal card: https://github.com/SUSE/spacewalk/issues/13630)
Our current shallow clone takes about 354M, with these changes the repository folder will size around 60M.

Reduce the content checkout from github to the ctl and checkout last 100 commits

---

.ci-travis/salt-server-validation
README_ADVANCED.md
modules/server/main.tf
modules/server/variables.tf
salt/server/rhn.sls

Implements https://github.com/uyuni-project/sumaform/issues/859
Currently, if we want to use a Minima mirror only to configure SUSE Manager to download the content from a mirror, so rhn.conf, we can't; we are forced to also mirror everything that sumaform needs during the automatic configuration phase, so during salt states in Sumaform, where tons of temporary repositories are set up.
In this PR we use a different variable to use only for the disk mirror feature on SUMA, when syncing products from SCC.

New parameter: server_mounted_mirror (mirror only for product sync.)

---

backend_modules/libvirt/host/user_data.yaml

Apparently, the new version of https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2 already fixed the workaround we had for Vault repositories, by adding CentOS-Vault.repo.
So we can safely remove our workaround.

Get rid of CentOS 6 workaround about Vault repo

---

backend_modules/libvirt/host/user_data.yaml

Reverts uyuni-project/sumaform#863
My bad, this workaround still valid.
We want to enable Vault repositories for 6 last version, not to any specific 6.x

Revert "Get rid of CentOS 6 workaround about Vault repo"

---

backend_modules/libvirt/host/user_data.yaml

Adds 3 needed packages in debian deployment for bootstrap. `apt-transport-https", "python-apt", "python3-apt"` are needed, see https://bugzilla.suse.com/show_bug.cgi?id=1183649#c2 . Using this I deployed 2 debian hosts and it worked. So there is no concern about the order of the package installation (cloud-init vs salt)

Add 3 needed packages in debian deployment for bootstrap

---

salt/server/init.sls

In replace of https://github.com/uyuni-project/sumaform/pull/808
Solves: https://github.com/uyuni-project/sumaform/issues/806
I have tried to use pkg.install but it doesn't have support for the flag `--force-resolution`.
As an alternative, I'm running a `cmd.run` with the needed full command.

baseproduct symlink  ofsuse manager product in jeos images

---

README_ADVANCED.md
modules/cucumber_testsuite/main.tf
modules/proxy/main.tf
modules/proxy/variables.tf
salt/proxy/init.sls

In the cucumber test suites, we already install retail pattern manually. We would like to do the same for the proxy pattern.
Benefits:
- BV test suite: do not collide with salt cleanup scenario (it was removing `/etc/salt/broker` configuration file)
- closer mimicking of what a customer does in the test suite
- independance of sumaform
To achieve that, this PR introduces a new `install_proxy_pattern` configuration variable that defaults to `true` for compatibility.
See also uyuni-project/uyuni#3487 and SUSE/susemanager-ci#219

Do not always install proxy pattern

---

salt/server/testsuite.sls

After https://github.com/uyuni-project/uyuni/pull/3481, the test suite uses SLES15-SP2
in the Cobbler test.
- salt/server/testsuite.sls: Provide SLES15-SP2 .

Follow a recent change in the testsuite

---

salt/repos/default.sls

Use Head client tools for all nightly versions, until we have the 4.2 projects ready (after GM), when the changes I did here will be done again, replaced Head with 4.2

Use Head client tools for all nightly versions

---

salt/server/testsuite.sls

The PR remove the upload of install files needed for srv_distro_cobbler.feature from the sumaform deployment to the testsuite execution.
Dependency : https://github.com/uyuni-project/uyuni/pull/3562
No difference.
- No documentation needed
Issue : 
https://github.com/SUSE/spacewalk/issues/13755
- Cucumber background test were added
If you don't need a changelog check, please mark this checkbox:
If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)
If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

Remove files needed for  srv_distro_cobbler.feature from suma deployment and upload its during tests

---

README_ADVANCED.md
modules/cucumber_testsuite/main.tf
modules/server/main.tf
modules/server/variables.tf
salt/server/rhn.sls

Disable forwarding registrations to SCC by default. This is to prevent dozen of dummy registration proxies to appear in SCC.

disable forwarding of registrations by default in sumaform

---

backend_modules/libvirt/base/main.tf

This images includes uyuni server dependencies so that, when used for
testing, it takes 3 minutes to install, instead of 15.
With the plain JeOS, when installing uyuni server pattern, we need to
install more than 900 packages. With this new image, only 115 are
needed.
This goes with https://build.opensuse.org/request/show/891292

Add opensuse 15.2 image for PR testing

---

salt/mirror/minima.yaml

Remove RES6 and Ubuntu16 from mirror they are EOL and no longer needed

Remove RES6 and Ubuntu16 from mirror

---

salt/repos/default.sls

Rename to `tools_update_repo`, to follow same naming than other products.
Currently, we have:
```
root@suma-head-min-ubuntu2004:/etc/apt/sources.list.d# cat tools_pool_repo.list
root@suma-head-min-ubuntu2004:/etc/apt/sources.list.d# cat Ubuntu2004-Client-Tools.list
root@suma-head-min-ubuntu2004:/etc/apt/sources.list.d# ls /etc/apt/sources.list.d
susemanager:channels.list  test_repo_deb_pool.list  tools_pool_repo.list  Ubuntu2004-Client-Tools.list
``` 
With these changes we expect to have:
```
root@suma-head-min-ubuntu2004:/etc/apt/sources.list.d# cat tools_pool_repo.list
root@suma-head-min-ubuntu2004:/etc/apt/sources.list.d# cat tools_update_repo.list
root@suma-head-min-ubuntu2004:/etc/apt/sources.list.d# ls /etc/apt/sources.list.d
susemanager:channels.list  test_repo_deb_pool.list …
```

Rename to tools_update_repo, to follow same naming than other products

---

salt/repos/default.sls

Add ltss repos for 11sp4, 12sp4, 15, 15sp1 and in advance 15sp2 and 15sp3. I didn't add all the 12sp* because we need to add them in the mirrors and there is no point since we won't be using them.
Adding the LTSS repos would fix openscap failures for older OS that only have the scap-security-guide in LTSS repos and not any others.

Add ltss repos for 11sp4, 12sp4, 15, 15sp1

---

salt/default/grub.sls
salt/default/init.sls

This PR makes sure SLES 11 SP4 uses same version for kernel and kernel modules after a reboot.
A better solution would be to generate correct images. For more details, see #887.

Work around initrd issue in sle11sp4

---

salt/proxy/init.sls

PR set product for proxy to `SUSE-Manager-Proxy` by calling:
```
zypper --non-interactive install --auto-agree-with-licenses --force-resolution -t product SUSE-Manager-Proxy
```

Set product for proxy

---

backend_modules/aws/base/main.tf
backend_modules/azure/base/main.tf
backend_modules/libvirt/base/main.tf
main.tf.aws-testsuite.example
main.tf.aws.example
main.tf.azure.example
main.tf.uyuni.example
modules/base/variables.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/server/main.tf

Next Uyuni version is going to be Leap 15.3
Change Server and Proxy to openSUSE Leap 15.3, as well as the examples.
WARNING: ci-pr image is not ready yet, @jordimassaguerpla is having a look (https://build.opensuse.org/package/show/systemsmanagement:sumaform:images:libvirt/opensuse153-ci-pr)

Change Uyuni to Leap 15.3

---

salt/default/ids.sls

This PR makes two states more independant of location of systemd's utilities:
```
root@suma-bv-42-min-debian9:~# which systemd-machine-id-setup
/bin/systemd-machine-id-setup
root@suma-bv-42-min-debian10:~# which systemd-machine-id-setup
/usr/bin/systemd-machine-id-setup
```

systemd utility can be at various places

---

salt/repos/default.sls

fixes: https://github.com/uyuni-project/sumaform/issues/862
Add LTSS repository in all machines with sles15sp0 and sles15sp1.
Deployments tested:
- minion sles15sp0
- minion sles15sp1
- Suse Manager 4.0
This will be needed after LTSS release for python3 bundle.

add ltss repo to sles15sp0 and sles15sp1

---

backend_modules/libvirt/base/main.tf

While opensuse admins fix the issue with a wrong pointer in their mirrros for that image, we will go directly to a source.

Temporary workaround: As the mirror list for Leap15.3 seems broken go directly to a source

---

backend_modules/aws/base/main.tf

Remove opensuse153 for aws backend because the ami is not available. Without ami matching opensuse153 search, it blocks sumaform deployment.

Remove opensuse153 waiting for it to be available on AWS

---

salt/controller/init.sls

In order to support the latest version of cucumber-ruby gem, we need to fix cucumber-html-reporter.
As the new output from the internal reporter is slightly different, so the hooks we have in place that contains the screenshots and logs of a failed scenario are stored differently, so we need to parse them differently.
As the external reporter has not many updates, it will probably take long time to have a new release.
So, as temporary solution, I would like to use my personal fork that includes the fix.

Temporary replace the npm of cucumber-html-reporter

---

backend_modules/libvirt/base/main.tf

The link is working again:
https://progress.opensuse.org/issues/94321#change-422708
Revert 'Temporary workaround: As the mirror list for Leap15.3 seems broken go directly to a source (#905)'
This reverts commit 837d573526eeeac021789f3cf6cf543da29b559c

Restore the regular link to opensuse153o

---

modules/virthost/variables.tf

Updating the KVM qcow2 image to retrieve it from a official repository, using a OpenStack JeOS version.
**Note:** We need to discuss if we want the mirror option on them, so using:
```
"${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2"
``` 
as we do for **opensuse153o**

Update KVM image, using a JeOS openstack qcow2

---

backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf

I tried to install Uyuni Master on libvirt with a mirror and one of the problems is that opensuse153 does not come with avahi preinstalled.
This patch fixes it.

Fix opensuse153's avahi

---

README_ADVANCED.md
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
modules/base/variables.tf
modules/cucumber_testsuite/variables.tf
modules/locust/main.tf
modules/virthost/variables.tf
salt/mirror/etc/minima.yaml
salt/mirror/etc/mirror-images.conf

This drops the unsupported distro, to lighten up mirrors a bit.
Builds on top of https://github.com/uyuni-project/sumaform/pull/896 (is best merged after that one)

Drop openSUSE 15.0 and 15.1

---

backend_modules/libvirt/base/main.tf

Point to a static mirror for the Leap 15.3 image (https://progress.opensuse.org/issues/95512)
Right now some mirrors do not have the image.
Related: https://github.com/uyuni-project/sumaform/pull/921

Point to a static mirror for the Leap 15.3 image (https://progress.opensuse.org/issues/95512)

---

salt/repos/default.sls

Leap 15.3 requires two new repos that are always present.
This PR is adding them. Please review if my evaluation of `osrelase_info` grain is correct.
This fixes the issue:
```
Run 1810:
module.cucumber_testsuite.module.server.module.server.module.host.null_resource.provisioning[0] (remote-exec): Problem: the to be installed firewalld-0.9.3-1.1.noarch requires 'python3-firewall = 0.9.3', but this requirement cannot be provided
module.cucumber_testsuite.module.server.module.server.module.host.null_resource.provisioning[0] (remote-exec):   not installable providers: python3-firewall-0.9.3-1.1.noarch[os_pool_repo]
module.cucumber_testsuite.module.server.module.server.module.host.null_resource.provisioning[0] (remote-exec):  Solution 1: downgrade of libfreebl3-3.53.1-3.53.1.x86_64 to …
```

Add SLE and backport updates for Leap >= 15.3

---

salt/minion/testsuite.sls
salt/repos/additional.sls

In SLES15SP3, the directory `/etc/pki/trust/anchors` is watched via the `ca-certificates.path` systemd unit, and as soon as its contents changed, the system-wide certificates are updated automatically. In `certs` state, we run `update-ca-certificates` right after deploying certs. These two processes create a race condition that in rare cases leads to an error.
This PR updates the `certs` state to run `update-ca-certificates` only if this systemd unit does not exist or is not running.
See https://bugzilla.suse.com/1188500

Skip 'update-ca-certificates' run if the certs are updated automatically

---

salt/minion/testsuite.sls
salt/repos/additional.sls

Reverts uyuni-project/sumaform#926 due to a python exception during initialization of the minion.

Revert "Skip 'update-ca-certificates' run if the certs are updated automatically"

---

backend_modules/aws/README.md
backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/null/base/main.tf
backend_modules/null/base/variables.tf
modules/base/main.tf
modules/base/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/repos/default.sls
salt/repos/server.sls
salt/server/init.sls

The use of internal repositories for public imply the use of mirror. The use of this mirror make the deployment very time consuming.
The idea of this PR is  to have the possibility to use SCC repositories when deploying on AWS. So when we want to test AWS deployment, we will only need to mirror repositories needed for the test and don't need to mirror all the default repositories.
The scc is an added behavior that change nothing  on default deployment. 
To use it, you need to add to module `base` the variable `server_registry_code` in your main.tf
The code has to be a Suse Manager Server activation code.

Add scc support for aws deployment

---

salt/repos/default.sls

It does the required changed here https://github.com/uyuni-project/sumaform/pull/877/ after GM

Fix: Change nightly tools after GM to point to 4.2 instead of Head

---

backend_modules/aws/README.md
backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/null/base/main.tf
backend_modules/null/base/variables.tf
modules/base/main.tf
modules/base/variables.tf
modules/proxy/main.tf
modules/server/main.tf
salt/repos/default.sls
salt/repos/proxy.sls
salt/server/init.sls
salt/server/rhn.sls

I added the proxy deployment support using SCC. I needed to rewrite some parts of the code and I have some instability aloso with the bastion deployment.
Just to explain why I copy / paste the SUSEConnect commands : I have to first register the server and then add the repositories in a specific order. Indeed suse proxy and server manager depends on specific repositories. So it 's impossible to use group of code to declare the repositories.

Add scc proxy support for AWS

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
modules/base/variables.tf

This PR is created to add Alma Linux 8 to client for libvirt provider.
Currently, it has to be describe with the option `auto_register` set to `false`.
Packages to install spacewalk are missing in centos 8 repositories.

Add Alma linux 8 client support to libvirt

---

salt/server/testsuite.sls

Force the installation of salt-ssh and its dependencies from our internal repository.
This tries to solve the current issue deploying Uyuni CI:
```
uyuni-master-srv:~/salt/server # zypper in expect aaa_base-extras salt-ssh wget OpenIPMI
Loading repository data...
Reading installed packages...
'wget' is already installed.
No update candidate for 'wget-1.20.3-3.12.1.x86_64'. The highest available version is already installed.
'aaa_base-extras' is already installed.
No update candidate for 'aaa_base-extras-84.87+git20180409.04c9dae-3.45.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Problem: the to be installed salt-ssh-3002.2-26.8.uyuni1.x86_64 requires 'salt = 3002.2-26.8.uyuni1', but this requirement cannot be provided
not installable …
```

Force installing salt packages from server_devel_repo

---

README_ADVANCED.md
modules/controller/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
salt/repos/default.sls

We need this so we can not add the master repos, when testing Pull
Requests.
Repos will be added as additional repos, instead.
Each PR has a different repo, so it can not be added here, but instead
will be added to susemanager-ci sumaform config files.
I also changed the README to state "openSUSE Leap image" instead of "openSUSE Leap 15.2 image", because stating the version is outdated.

Add new product version uyuni-pr

---

backend_modules/libvirt/base/main.tf

openSUSE official images are being constantly being updated. This
creates 2 problems:
1- The image can be different from build to build
2- Sometimes the image is not available
Given this is for testing PRs, we don't need to use the official one.
For master testing, yes, but for PRs, we are allowed to take some
shortcuts that add stability or velocity.
In this case, what we are doing is building the image once and disabling
the build. This way, once the image has been synced in all mirrors, there won't
be new builds.
Thus, by using our image, every build will have the same image, which
adds consistency and test stability.

Use custom image for openSUSE clients when testing PRs

---

modules/cucumber_testsuite/main.tf

Update default images in test suite module.
Following the values we use in our SUSE Manager 4.2 CI, as if we don't set those new values, a user deploying with default values will have a failed test suite (the test suite expect these concrete versions):
``` 
module "cucumber_testsuite" {
source = "./modules/cucumber_testsuite"
product_version = "4.2-nightly"
// Cucumber repository configuration for the controller
git_username = var.GIT_USER
git_password = var.GIT_PASSWORD
git_repo     = var.CUCUMBER_GITREPO
branch       = var.CUCUMBER_BRANCH
cc_username = var.SCC_USER
cc_password = var.SCC_PASSWORD
images = ["centos7o", "opensuse152o", "sles15sp2o", "sles15sp3o", "ubuntu2004o"]
use_avahi = false
name_prefix = "suma-42-"
domain = "mgr.prv.suse.net"
from_email = "root@suse.de" …
```

Update default images in testsuite module

---

backend_modules/aws/base/main.tf

Change opensuse152 name declaration in AWS to be compatible with mirror default image ( opensuse152o )

Update opensuse152 name to be compatible with mirror

---

salt/virthost/init.sls

Now that tuned is installed on the virtual host machines, virt-what is
automatically installed and causes Salt and Uyuni to think the VM is a
VM.
In order to properly test the virtualization features, we need Uyuni to
think the virtual hosts to be physical machines even if it's not true...
Replacing /usr/sbin/virt-what by an empty script mimics the bare metal
machine case.

Fake virt-what on virtual hosts

---

salt/repos/proxy.sls

with the last change we had a duplicate repo introduced on head/uyuni.
For older versions we had a bit wrong directory names which should be fixed now.

fix duplicate repos and wrong URLs

---

backend_modules/libvirt/README.md
backend_modules/null/base/variables.tf
modules/base/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

This PR adds a configuration variable for the `cucumber_testsuite` module to allow setting an ssh key different from the default `~/.ssh/id_rsa.pub`. This prevents the `terraform apply` to fail due a different ssh key name.

Allow to set a custom ssh key in the cucumber test suite module

---

salt/repos/additional.sls

The repo generated for pull request testing is not signed. Thus, for
this particular case, we need to trust the repo.
Partial fix for: https://github.com/SUSE/spacewalk/issues/15846

Use an untrusted repo for a pull request testing

---

backend_modules/libvirt/base/main.tf

Without this patch, all CIs will fail during "Deploy" phase because now opensuse Leap qcow2 images are being pulled from https:// not http:// mirrors.

fixed mirror url to be https not http

---

salt/repos/proxy.sls

This PR adds a new repository in the proxy systems in order to get devel packages for those that are not part of SUMA Proxy channels, like "salt".
These new repositories "Basesystem-Overlay" and "openSUSE-Overlay" currently contains the Salt package + some new dependencies which are not part of SLE.
This way, the deployed proxy will have the devel testing package for Salt and not the latest released Salt in SLE or Leap.

Add "basesystem overlay" testing repo to the proxy

---

salt/repos/proxy.sls

Same as https://github.com/uyuni-project/sumaform/pull/964 for `4.1-nightly`

Add "basesystem overlay" testing repo to the proxy for 4.1 nigthly

---

modules/virthost/variables.tf

Otherwise, these images are unavailable if we use http.

Use https for opensuse 15.3 images

---

backend_modules/aws/host/main.tf
backend_modules/azure/host/main.tf

Before this:
```
module.jenkins.module.jenkins.module.host.null_resource.host_salt_configuration[0] (remote-exec): mv: cannot move '/tmp/salt' to '/root/salt': File exists
```
After this:
The states are refreshed at `/root/salt`

Allow refresing salt states for AWS and Azure

---

backend_modules/aws/host/user_data.yaml

They were right for the libvirt backend, but not for AWS, so I copied those we have at libvirt, which (of course) are those we get from the client tools themselves.

Update the Ubuntu Client tools GPG keys for Ubuntu

---

README_ADVANCED.md

@rjmateus my understanding is that official images will use a mirror - thus can work without internet connections these days. Also, several are used by default

README: official images are used by default now

---

README_ADVANCED.md
backend_modules/aws/host/main.tf
backend_modules/azure/host/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/ssh/host/main.tf
modules/jenkins/main.tf
modules/jenkins/variables.tf
modules/jenkins/versions.tf
salt/jenkins/basic-security.groovy
salt/jenkins/configuration.sls
salt/jenkins/configure-jenkins.sh
salt/jenkins/etc/jenkins.conf
salt/jenkins/init.sls
salt/mirror/etc/minima.yaml
salt/repos/init.sls
salt/repos/jenkins.sls
salt/top.sls

Enable deployment of a Jenkins instance with sumaform that:
- Installs the latest LTS version from OBS
- Creates a user `admin` with a random password stored at `/var/lib/jenkins/secrets/initialAdminPassword`
- Enables default security for Jenkins (integrated DB)
- Installs the required plugin run an acceptance test pipeline, and swarm, so we can later add workers
Since we don't have workers yet, I had to do some workarounds at Jenkins so it would also act as worker:
- Install sumaform
- Create `/home/jenkins`, `/home/jenkins/.ssh`, create a private/public keypair, and copy `/home/jenkins/.credentials` from the internal Jenkins-worker to the same location at the AWS Jenkins. This allowed us to have a pipeline that's no different from others
- Link `/home/jenkins/.ssh` at …

Allow Jenkins VMs

---

salt/jenkins/http_proxy.sls
salt/jenkins/init.sls
salt/jenkins/podman.sls

Add a http_proxy to Jenkins, required by the Uyuni testsuite
It uses a new container, defined at https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master:Docker/proxy, which is basically the same thing as the proxy we have for the tests at the internal infra.
I deployed this, and works, this is a test from the bastion to the http proxy at Jenkins:
```
ec2-user@ip-172-16-0-82:~> telnet 172.16.1.252 3128
Trying 172.16.1.252...
Connected to 172.16.1.252.
Escape character is '^]'.
^CConnection closed by foreign host.
```

Add a http_proxy to Jenkins, required by the Uyuni testsuite

---

backend_modules/libvirt/host/main.tf

Fix empty string for terraform update

---

backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
modules/base/main.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

This PR fix the current issues caused by previous commit in order to enable the `venv-salt-minion` installation. 
This PR introduces a new configuration parameter for the "base" configuration named `install_salt_bundle` (default: false).

Install Salt bundle based on 'install_salt_bundle' base config

---

modules/client/main.tf
modules/client/variables.tf
modules/cucumber_testsuite/main.tf
modules/host/main.tf
modules/minion/main.tf
modules/minion/variables.tf
modules/mirror/main.tf
modules/mirror/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
modules/sshminion/main.tf
modules/sshminion/variables.tf
modules/virthost/main.tf
modules/virthost/variables.tf
salt/post_provisioning_cleanup.sh

This PR fixes a problem with newly introduced `install_salt_bundle` which is not working properly after the last refactor.
This also copies the `/etc/salt/grains` file deployed by sumaform to `/etc/venv-salt-minion/grains` in case `install_salt_bundle` is set.

Fix propagation of "install_salt_bundle" after last refactor

---

salt/server/testsuite.sls

This PR makes the server role to define a custom pillar `mgr_force_venv_salt_minion: True` for all minions in order make the bootstrap state during Uyuni testsuite execution to use the `venv-salt-minion` package (even if this is not available in the bootstrap repository).
See how this pillar data affects bootstrapping here: https://github.com/uyuni-project/uyuni/pull/4497
Without this change, since the testsuite is not syncing the client tools for the different systems, then `venv-salt-minion` is not part of the bootstrap repo (but it's installed on the system), the bootstrapping is using "salt-minion" and not "venv-salt-minion" as we would expect.

Add custom pillar for "testsuite" to enable Salt Bundle when doing bootstrapping

---

modules/base/versions.tf
modules/client/versions.tf
modules/controller/versions.tf
modules/cucumber_testsuite/versions.tf
modules/grafana/versions.tf
modules/host/versions.tf
modules/jenkins/versions.tf
modules/locust/versions.tf
modules/minion/versions.tf
modules/mirror/versions.tf
modules/proxy/versions.tf
modules/pxe_boot/versions.tf
modules/registry/versions.tf
modules/server/versions.tf
modules/sshminion/versions.tf
modules/virthost/versions.tf

If we use multiple libvirt providers definitions it needs each module that doesn't use the default.
Since each provider independent module doesn't define the provider namespace in use, terraform tries to resolve the same to `hashicorp/libvirt` instead of using the name space defined in the root main tf file.
With this change, all provider indepoendent module version file is now a symbolic link to the provider in use. With this approach we make sure all needed providers are defined for each module and we maintain compatibility with all backend providers.
@srbarrios ping

version files as symbolic link to backend in use

---

backend_modules/libvirt/base/main.tf

This PR fixes a broken link for the AlmaLinux8 image source. Since AlmaLinux 8.5 was released the link changed and it is not raising 404.
This changed to the link to the generic name pointing to latest release of AlmaLinux 8.

Fix broken link to use proper AlmaLinux8 qcow2 image name

---

modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/proxy/init.sls
salt/server/init.sls

As our server and proxy has a default Apache configuration that doesn't allow old SSL Protocols, our SLES11SP4 or CentOS6 systems will require to manually that config. This parameter automated it for us.
See also https://github.com/SUSE/spacewalk/issues/15659

Optional parameter to accept a greater range of SSL protocol versions

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

Correct generation of Retail information
See also uyuni-project/uyuni#4567
Tested to work on 4.1 BV.
This PR also removes build hosts and terminals for sles12sp4 and sles15sp2, forgotten in a previous PR. We now use sles12sp5 and sles15sp3.

Terminals are known only by their MAC address

---

README_TESTING.md
modules/cucumber_testsuite/main.tf
modules/virthost/main.tf
modules/virthost/variables.tf

implementation of: https://github.com/SUSE/spacewalk/issues/16660
Give the possibility to add or overwrite additional grains on the testsuite module.
It only applies to salt minions.
This is needed because we should be able to overwrite the xen/kvm image download location. `vhost` have a property to do it, but in the context os the `cucumber_testsuite` module it cannot be used, since we cannot have a variable be conditionally passed to a module, which would be the scenario when the user didn't provide any different URL on cucumber testsuite configuration
To support this behavior on the virtual host module we would need to get it completely dirty. 
With this implementation we support overwrite this grains and at the same time support any …

additional grains on cucumber testsuite module

---

salt/post_provisioning_cleanup.sh

As a final steps for instances with `install_salt_bundle = True`, sumafom performs the execution of a bash script to remove any "salt" package that got installed during sumaform deployment in order to make the instance to only contain `venv-salt-minion` package installed after deployment.
During this cleanup, the messages coming from zypper/yum/apt when removing the packages, particularly in case any python2-salt is not installed, the message error messages shown are confusing, since it seems the deployment fail during the cleanup while it was not the case.
This PR simply hides the raw output from the cleanup and the confusing messages do not appear

Salt Bundle: Do not show confusing messages from Zypper while removing normal Salt

---

salt/virthost/init.sls

This PR fixes an issue that we have seen already happening in some of our deployments where "virthost" is involved.
One of the latest steps during configuration of the instance is to schedule a reboot of the system:
https://github.com/uyuni-project/sumaform/blob/master/salt/virthost/init.sls#L131-L139
Then sometime it happens that the `post_provisioning_cleanup.sh` cleanup script is running while the reboot is done, so terraform raises an error:
```
01:50:34  │ Error: remote-exec provisioner error
01:50:34  │ 
01:50:34  │   with module.kvm-minion.module.virthost.module.minion.module.host.null_resource.provisioning[0],
01:50:34  │   on /home/jenkins/jenkins-build/workspace/uyuni-master-infra-reference-NUE/results/sumaform/backend_modules/libvirt/host/main.tf line 239, in resource …
```

virthost: schedule reboot after two minutes to allow cleanup script to finish

---

README_ADVANCED.md
README_TESTING.md
modules/build_host/main.tf
modules/build_host/variables.tf
modules/build_host/versions.tf
modules/cucumber_testsuite/main.tf
salt/repos/build_host.sls
salt/repos/init.sls
salt/repos/minion.sls

We don't need container module nor development tools module on normal minions. Worse, these modules are now creating problems during client migration.
Create a module of its own for build hosts.
Fixes SUSE/spacewalk#16770 .
See also SUSE/susemanager-ci#443

Create module for build hosts

---

salt/post_provisioning_cleanup.sh

Fix miscontructed pipes to `/dev/null`. The current issue is not making the deployments to fail but it does not work as expected.

Fix miscontructed piping for stdout and stderr

---

salt/repos/proxy.sls
salt/repos/server.sls

Trying to deploy server and proxy using product version 4.3-beta, I have two issues:
1)
```
[1mmodule.proxy.module.proxy.module.host.null_resource.provisioning[0] (remote-exec):[0m [0m    Detected conflicting IDs, SLS IDs need to be globally unique.
```
Fixing this by renaming the salt state.
2)
```
[1mmodule.server.module.server.module.host.null_resource.provisioning[0] (remote-exec):[0m [0m    Rendering SLS 'base:repos.server' failed: while constructing a mapping
[1mmodule.server.module.server.module.host.null_resource.provisioning[0] (remote-exec):[0m [0m  in "<unicode string>", line 10, column 1:
[1mmodule.server.module.server.module.host.null_resource.provisioning[0] (remote-exec):[0m [0m    server_product_pool_repo: …
```

Not add moving target repos in 4.3-beta for server and proxy

---

salt/build_host/init.sls

because there is a systemd unit that watches for changes and runs it
already:
/usr/lib/systemd/system/ca-certificates.path
If we try to run it, it fails with an error because it runs twice
at the same time.

Do not run update-ca-certificates on SLE15

---

salt/server/postgres.sls

When external connections to the postgresql DB should no be allowed, do not configure pg_hba.conf to do so.

change pg_hba.conf when external connections should not be allowed

---

backend_modules/libvirt/host/user_data.yaml

Change cloud-init so that we use vault.centos.org instead of mirror.centos.org

centos 8 moved to vault

---

modules/build_host/main.tf
modules/build_host/variables.tf
modules/client/main.tf
modules/client/variables.tf
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/jenkins/main.tf
modules/jenkins/variables.tf
modules/minion/main.tf
modules/minion/variables.tf
modules/mirror/main.tf
modules/mirror/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/registry/main.tf
modules/sshminion/main.tf
modules/sshminion/variables.tf
modules/virthost/main.tf
modules/virthost/variables.tf

We need this to disable opensuse official repos and instead use mirrored
repos. Also, to disable updates to have a more stable environment.

Add additional_repos_only to cucumber testsuite module

---

salt/default/avahi.sls
salt/repos/additional.sls
salt/repos/build_host.sls
salt/repos/default.sls
salt/repos/jenkins.sls
salt/repos/minion.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/repos/testsuite.sls
salt/repos/tools.sls
salt/repos/virthost.sls

Enable autorefresh in all the repository definitions added with salt.
This PR try to prevent an issue during deployments and even during our test suite.
Once we do a `zypper refresh`, we obtain a metadata file from the repositories. If by bad luck the repository gets updated after this `zypper refresh`, our metadata will be old and invalid, so the packages we try to download will not be available. This autorefresh in the repository definition will force zypper to always run `zypper install`, having before a `zypper refresh`.
WARN:
This change could very well cause issues, even if we hope to prevent one issue.
Probably the best approach is to after deployment, disabled this parameter in all the repositories again, but that could be kind of tough :confused:

Enable autorefresh in all the repository definitions added with salt

---

salt/minion/testsuite.sls
salt/repos/additional.sls

older salt had problems with `unless`
with recent salt, those `{% if`s are not needed anymore

Remove ifs that are not necessary anymore

---

salt/virthost/init.sls

We are setting br0 but we are not activating this.
We need to restart the network, but I don't want to do this and loose
the connectivity when salt is setting up configurations.
I think the safest thing is just to force the reboot always, to activate
this network configuration.

Reboot always after setting virthost to enable br0

---

salt/server/prometheus.sls

This PR fixes an issue caused by the rename of `golang-github-wrouesnel-postgres_exporter` package to the new name `prometheus-postgres_exporter`:
```
----------
ID: postgres_exporter
Function: pkg.installed
Name: golang-github-wrouesnel-postgres_exporter
Result: False
Comment: An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r26d6462004e94715bc8379823f80b52e.scope
Package 'golang-github-wrouesnel-postgres_exporter' not found.
Started: 10:56:02.685046
Duration: 775.988 ms
Changes:
```
The new `prometheus-postgres_exporter` package does provides `golang-github-wrouesnel-postgres_exporter`.
This PR changes the state to resolve the "provides" when looking the package to install.

Fix issue with renamed "prometheus-postgres_exporter" package

---

salt/server/testsuite.sls

This PR prepares testsuite deployments to force the usage of Salt bundle during bootstrapping not only for Uyuni but also for SUSE Manager 4.3 and Head versions.
I'm currently testing this PR together with some other changes in the testsuite in our internal TEST enviroment.
Please, do not merge this PR yet. I'll take care of merging this once it is the time for this.

Set custom "mgr_force_venv_salt_minion" pillar also for head and 4.3

---

salt/server/master-custom.conf
salt/server/salt_master.sls

This reverts commit b3a6f939b47c1af63ed153685064b554a8e32616, as we have already debugged the issue (deadlock) and this change is currently causing some Uyuni acceptance tests scenarios to fail.

Revert "debug logging for master and api"

---

CONTRIBUTING.md
DESIGN.md
README.md
README_ADVANCED.md
README_TESTING.md
TROUBLESHOOTING.md
backend_modules/aws/README.md
backend_modules/aws/README_ADVANCED.md
backend_modules/azure/README.md
backend_modules/libvirt/README.md
backend_modules/null/README.md
backend_modules/ssh/README.md

Fixes
- outdated cucumber command in the testsuite README
- grammar/spelling
- code snippet syntax
- headings
- missing/empty lines
- listings
- bare URLs
All in all this will align the documents more with the Markdown language standard.
Adds
- `terraform validate` command in the base README to verify ones configuration

docs: Several (Markdown) fixes

---

modules/cucumber_testsuite/main.tf

This parameter is useful to "skip" SCC and instead get the info and
packages from a mirror.
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

Add server_mounted_mirror to the testsuite server

---

salt/server/testsuite.sls

This PR fixes a problem detected on Uyuni Master testsuite caused by a typo on the list of products version where to force the usage of Salt Bundle

Fix products version for Uyuni to force Salt bundle usage

---

salt/repos/init.sls

We sometimes have the case, that a normal refresh skip repos as they were just refreshed a minute ago, but the repo changed anyway. Do a force refresh to really get the latest packages.

force the refresh to really have latest repos

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/config.ign
backend_modules/libvirt/host/main.tf
salt/first_deployment_highstate.sh
salt/repos/default.sls
salt/repos/minion.sls
salt/repos/proxy.sls
salt/repos/server.sls

Adds link for SLE Micro 5.1 build at [sumaform:images:microos project](https://build.opensuse.org/project/show/systemsmanagement:sumaform:images:microos)
MicroOS, being a transactional system, requires salt to skip creating new snapshots. Added `direct_call` module executor ensures that.

Add SLE Micro 5.1 support

---

salt/repos/default.sls
salt/repos/init.sls
salt/repos/vendor.sls

Otherwise, we cannot add additional_repos via terraform to test, for
example, salt packages under development.

modify vendor files also when additional_repos_only is set

---

README_ADVANCED.md
modules/server/main.tf
modules/server/variables.tf
salt/server/init.sls

At _sumaforming time_ set the webUI `login_timeout` as desired.
At development time you don't really want to re-login again during the day while you are going back and forth fir a bit more than just 1 hour. This _optional_ parameters overrides the default one by editing the `/etc/rhn/rhn.conf` file in the same way the normal user should in the real life to change that value.
Note: review asked to some random developer

Devel parameter: extend login timeout

---

modules/cucumber_testsuite/main.tf
modules/server/main.tf
modules/server/variables.tf
salt/server/init.sls

A Hub environment require 1 Root CA for the hub and all peripheral servers to make the reporting feature work.
Download CA cert and key from "server" and re-use it when generating the SSL server certificates

download CA cert and key from a hub when setting up a peripheral server

---

salt/repos/default.sls

Fix an issue created by https://github.com/uyuni-project/sumaform/pull/1075 for the Ubuntu client tools:
```
local:
Data failed to compile:
----------
Rendering SLS 'base:repos.default' failed: while parsing a block mapping
in "<unicode string>", line 57, column 7
did not find expected key
in "<unicode string>", line 60, column 13
```
All in all, I decided to switch all comments to Jinja style

Switch salt/repos/default comments to Jinja style

---

salt/repos/default.sls

Nigthlies can be unified, but not `released`, as Uyuni "Stable" is also `uyuni-released`

Rollback simplification of 4.1/4.2-released

---

modules/server/main.tf
salt/server/tomcat.sls

This will also adjust the timeout in web.xml in Tomcat according to [rhn_web.conf](https://github.com/uyuni-project/uyuni/blob/d59de49972ee98d8542c852e4e9d24f4d8f5bd42/web/conf/rhn_web.conf#L29-L31).
According to the [Jinja docs](https://jinja.palletsprojects.com/en/3.0.x/templates/#math) we can use `//` to return a truncated integer result of the division that is made.
> //
Divide two numbers and return the truncated integer result. {{ 20 // 7 }} is 2.

fix: Enable login timeout

---

modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf

This will add the `login_timeout` variable that @ncounter indroduced to the `cucumber_testsuite` module.
Links:
* https://github.com/uyuni-project/sumaform/pull/1074
* https://github.com/uyuni-project/sumaform/pull/1079

Add `login_timeout` variable to `cucumber_testsuite`

---

salt/repos/default.sls

```
root@suma-42-min-ubuntu2004:~# cat /etc/apt/preferences.d/tools_update_repo
Package: *
Pin: release l=Devel:Galaxy:Manager:Head:Ubuntu20.04-SUSE-Manager-Tools
Pin-Priority: 800
```
While for example head does not have the comment, and didn't add the empty line.

A comment was generating an empty line

---

backend_modules/libvirt/base/main.tf
salt/mirror/etc/mirror-images.conf

JeOS does not exist anylonger and is now called "Minimal". This adjusts
the URLs for SLE15SP4 and fixes #1083.

fix: Switch SLE15SP4 image from JeOS to Minimal

---

salt/server/tomcat.sls

$subject
Duplicate ID: see [`salt/server/init.sls`](https://github.com/uyuni-project/sumaform/blob/master/salt/server/init.sls#L131)

Fix: rename duplicate salt state id

---

salt/repos/default.sls

Resolution for: https://github.com/SUSE/spacewalk/issues/17512
In the nightly build installations, we add a devel repo for client tools for each minion. This channel has a higher priority than all others, to make sure we install packages from this channel.
When we install the package `golang-github-prometheus-prometheus` it has as a dependency the package `firewalld-prometheus-config`.
On sles15SP3 this package is obsoleted by the package `firewalld`, provided in the OS base channel.
Since the devel repo has a higher priority, it will ignore this relationship and installation fail with a package conflict.
This PR solves this by locking the package `firewalld-prometheus-config` on sles15SP3 and higher, which solves the conflict problem.
I …

lock package to allow deployment of prometheus in sles15sp3 and newer

---

salt/repos/default.sls

This PR fixes an issue we are getting in our SUMA 4.1 and 4.2 deployments because an issue when installing Salt 3004 in the SLE15SP2 instances.
The problem is that Salt 3004 requires two new dependencies `python3-contextvars` and `python3-immutables`. These packages are released for SLE15SP2 in the LTSS repos, which is not yet enabled in sumaform for those instances.
This PR simply enabled the LTSS repos for SLE15SP2.

Enable LTSS repos for SLE15SP2 instances

---

salt/proxy/init.sls

Use client tools to get the containers proxy rpm package.

Fix proxy_rpm_download URLs to use client tools

---

salt/server/init.sls

If the product being deployed is HEAD, then we should change the flag "java.product_tree_tag = Beta"
Implementation of https://github.com/SUSE/spacewalk/issues/17928

set product tree to Beta on HEAD

---

backend_modules/libvirt/base/main.tf
modules/proxy/main.tf
modules/server/main.tf
salt/mirror/etc/minima.yaml

Change base OS image for uyuni master to opensuse leap 15.4

use opensuse leap 15.4 for uyuni master

---

backend_modules/libvirt/README.md
backend_modules/libvirt/host/main.tf

Change inheritance of pool when no variable is set. From using the default pool to using the pool that is defined in the base module.

Change inheritance of pool when no variable is set

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/default.sls

Centos tools repository are out of support and we should use EL8 tool for all rhel based systems from now on.

change tools repo for RHEL based os to use EL8

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml

Add support to deploy rocky linux 8 on libvirt backend.
Implements: https://github.com/SUSE/spacewalk/issues/16319
Looks like some of the mirrors have problems with the http response status which leads to inconsistent errors when downloading the image file.
I will try to find which one is, and try to contact someone from rocky linux.

add support for rocky linux 8 on libvirt backend

---

salt/default/network.sls

remove fqdn from /etc/hosts added by cloud-init which was causing problems when running debian on Build Validation testsuite.

remove fqdn from /etc/hosts

---

salt/mirror/etc/minima.yaml
salt/repos/proxy.sls
salt/repos/server.sls

Implements: https://github.com/SUSE/spacewalk/issues/17912
Final touches in support of SUSE Manager 4.3 released and nightly versions.
@juliogonzalez has already done most of the work. 
After https://github.com/SUSE/spacewalk/issues/18057 is done, the URL in here need to be verified.

final preparation to support 4.3

---

salt/repos/default.sls

Before this PR:
* on a tests on PRs deployment:
```
[root@suma-pr2-min-centos7 yum.repos.d]# ls *_repo.repo 
tools_pool_repo.repo
```
* on Uyuni master deployment:
```
[root@uyuni-master-min-centos7 yum.repos.d]# ls *_repo.repo 
tools_pool_repo.repo tools_update_repo.repo
```
This PR enables `tools_update_repo.repo` also for tests on PRs on CentOS.

use tool updates also on tests on PRs

---

salt/server/init.sls

Temporary assign beta client tools for 4.3, until `Manager-4.3` is fully branched and the testsuite can stop requiring beta client tools.

Temporary assign beta client tools for 4.3

---

backend_modules/libvirt/base/main.tf

This will add support for using SLE Micro 5.2 as base image. This is needed for adding SLE Micro 5.2 to our test suite.
Fixes https://github.com/SUSE/spacewalk/issues/16316

Add SLE Micro 5.2 support

---

modules/cucumber_testsuite/variables.tf

Adds opensuse 15.4 image to cucumber testsuite images list

QE: Add opensuse 15.4 image to images list for cucumber testsuite module

---

salt/repos/default.sls

Remove the workarounds as 4.3 is now released

change additional_tools_repo to 4.3 devel URL

---

salt/server/init.sls

When setting up a monitored server, Tomcat will not start, Apache sending a 503 error, and several states will fail. The reason is Tomcat needs `/etc/prometheus-jmx_exporter/tomcat/java_agent.yml` to start, but that file has not yet been created as the corresponding states run later.
`journalctl -u tomcat` indeed shows:
```
Aug 22 03:58:04 suma-ref41-srv server[5940]: Caused by: java.io.FileNotFoundException: /etc/prometheus-jmx_exporter/tomcat/java_agent.yml (No such file or directory)
```
This patch fixes ordering, thereby allowing Tomcat to start correctly.
Noticed in the internal reference host: https://ci.suse.de/view/Manager/view/Manager-4.1/job/manager-4.1-infra-reference-PRV/788/console
Tested: https://ci.suse.de/view/Manager/view/Manager-4.1/job/manager-4.1-infra-reference-PRV/789 …

Fix ordering: install Prometheus components before starting Tomcat

---

backend_modules/null/base/variables.tf
modules/cucumber_testsuite/variables.tf

Follow-up of #1147
In the default images list:
- remove centos8o
- remove opensuse152o
- remove sles11sp4
- remove sles12sp3
- remove sles15o, sles15sp1o, and sles15sp2o
- add sles15sp4o

Update default images list

---

salt/mirror/etc/mirror-images.conf

Fixes the URL for Ubuntu 22.04 introduced in https://github.com/uyuni-project/sumaform/pull/1153. The URL for Ubuntu Bionic is already there.

fix: Ubuntu 22.04 URL in mirror config

---

salt/server/testsuite.sls

This PR fixes a problem when deploying the "server" node on Cobbler versions higher than 3.3.0, where the settings file is now named `settings.yaml`.
Tracks: https://github.com/SUSE/spacewalk/issues/16538
**IMPORTANT NOTE: DO NOT MERGE THIS PR UNTIL WE HAVE COBBLER 3.3.2 AT HEAD AND UYUNI**

Use proper "cobbler" settings file on newer Cobbler versions

---

salt/server/init.sls

We now need the beta tools only for version 4.4
** Merge all 4 PRs at once **
* 4.2: https://github.com/SUSE/spacewalk/pull/18866
* 4.3: https://github.com/SUSE/spacewalk/pull/18866
* Uyuni: https://github.com/uyuni-project/uyuni/pull/5887

Use beta tools on 4.4 instead of 4.3

---

modules/cucumber_testsuite/main.tf

This will update the SUSE minion and SSH minion from SLES15 SP3 to SP4 since we use SP4 in the test suite for them. The migration from SP3 to SP4 was moved to build validation so they do not need to be SP3 any longer.

Cucumber test suite module: Update used SUSE images

---

main.tf.libvirt-testsuite.example

This will move our test suite example file from our internal repository to sumaform to have it in the right place and prevent duplication.
For reference: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/594

Add libvirt test suite example file

---

salt/repos/default.sls

Fixes a wring indentation in the `repos/default.sls` file preventing RHEL family OSs to be configured.

Fix pillars for RHEL family OSs

---

README_TESTING.md
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc

Reverts uyuni-project/sumaform#1164
Reverting as this is breaking our deployments.
https://ci.suse.de/view/Manager/view/Manager-4.3/job/manager-4.3-dev-acceptance-tests-PRV/189/console

Revert "New variable to set up custom download endpoint"

---

backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf

On AWS bastion host now have a public static  IP (eip) assigned to it.
Before this, the bastion had a public IP but it was not static. This is a better approach to deploying the test infrastructure needed for testsuite.

aws: bastion host with static IP

---

backend_modules/libvirt/base/main.tf
salt/mirror/etc/mirror-images.conf

The SLES12 SP4 images were removed from `download.suse.de`. So I've updated the link to `schnell.suse.de`, where they are now being hosted. New link being used is https://schnell.suse.de/SLE12/SLE-12-SP4-JeOS-GM/SLES12-SP4-JeOS.x86_64-12.4-OpenStack-Cloud-GM.qcow2
Fixes https://github.com/uyuni-project/sumaform/issues/1171

QE: Fix download link for SLES12SP4o image

---

main.tf.libvirt.example
main.tf.ssh.example

This commit updates the image name to "sles15sp4o" in the example config for libvirt and ssh. Previously, this was set to "sles12sp3", an image which is no longer available, so `terraform apply` would fail.

Use newer image in example libvirt and ssh config

---

backend_modules/libvirt/README.md

Fix typo in symlink command (`ln-sfn` -> `ln -sfn`)

Fix typo in README.md

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/azure/base/main.tf
backend_modules/azure/host/user_data.yaml
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/cpu_features.xsl
backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/user_data.yaml

Added support for the following OSs:
**libvirt backend** [Commit](https://github.com/uyuni-project/sumaform/pull/1166/commits/dcf8a6e598ea8e6354f95cfd3528e17928896e93)
- Rocky 9
- CentOS 9
- AlmaLinux 9
- Oracle Linux 9
Also addressed the issue with the x86-64-v2 architecture. 
See [the bugzilla thread](https://bugzilla.redhat.com/show_bug.cgi?id=2060839) and [the article from RedHat](https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#) for more details. 
**aws and azure backend** [Commit](https://github.com/uyuni-project/sumaform/pull/1166/commits/195a2bf1fce18b0ba558576eb3bef843d7ae7d39)
- RHEL9

RHEL9 and derivatives support in sumaform

---

salt/proxy/init.sls

Containerized proxy services installed in 4.3-nightly and Uyuni PR tests
Necessary to develop and run Containerized proxy tests in PR tests and CI tests.

Containerized proxy services installed in 4.3-nightly and Uyuni PR tests

---

backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf
salt/mirror/configuration.sls
salt/server/additional_disk.sls

When deploying on AWS, if we use an instance type > t2.XXX, the partition name will be nvme1nX . Sumaform doesn't support this naming for mirror and server with additional disk.
This PR adds nvme1nX naming support
traditionaly partitions are just numbered after the device name:
sda1, sda2, xvdf1, xvdf2, etc.
On NVMe drives this seems to have changed as the device name ends with a number. So they use p1, p2, etc. for partition 1, partition 2, etc.
nvme0n1p1,
nvme0n1p2,
nvme1n1p1

Add support for AWS partition name

---

salt/proxy/init.sls

Reverts uyuni-project/sumaform#1181
We need to revert this, because sumaform is not prepared to support the installation of podman in SUMA Proxy, and we will need some changes first.

Revert "Containerized proxy services installed in 4.3-nightly and Uyuni PR tests"

---

salt/proxy/init.sls

Add condition to containerized proxy not to be executed when run on AWS.

Containerized proxy not compatible with aws

---

salt/server/initial_content.sls

In head we dropped traditional registration. A lot of bootstrap script parameters are gone as well.
create a standard bootstrap script as example.

traditional was dropped from uyuni, create a standard bootstrap script

---

salt/repos/default.sls

Implementation of: 
- https://github.com/SUSE/spacewalk/issues/17050
- https://github.com/uyuni-project/sumaform/issues/1048
Now if the product being deployed is set but is not uyuni, we will be using the sle client tools.

leap deployment with suma uses suma tool repos

---

salt/proxy/init.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/server/testsuite.sls

Reverts uyuni-project/sumaform#1189
Reverting as it's breaking Uyuni PR deployments.
```
Oscar Barrios Torrero
[9:15 AM](https://suse.slack.com/archives/C02DRMDU69E/p1668154508564349)
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1928/
[9:15](https://suse.slack.com/archives/C02DRMDU69E/p1668154511191259)
image.png
image.png
[9:15](https://suse.slack.com/archives/C02DRMDU69E/p1668154522969099)
Ah, yes, Erwan shared already
[9:15](https://suse.slack.com/archives/C02DRMDU69E/p1668154540911849)
I will take a look to latest commits in Sumaform
[9:18](https://suse.slack.com/archives/C02DRMDU69E/p1668154718228429)
Last commit is on me and 
[@Cedric Bosdonnat](https://suse.slack.com/team/U02CL734EH5)
[9:18](https://suse.slack.com/archives/C02DRMDU69E/p1668154719005309) …
```

Revert "Containerized proxy services installed in 4.3-*, uyuni-* and head test environments"

---

README_ADVANCED.md
modules/controller/main.tf
salt/mirror/etc/minima.yaml

Remove SUSE Manager 4.0 leftovers. It was already removed from repositories list and other important places.
We will keep 4.1 in sumaform for the time being.

Remove 4.0 leftovers

---

backend_modules/libvirt/host/user_data.yaml

Was there a good reason for using a different path as for Rocky 8 for the tools ?
This PR aligns the path for both distros.

Align Rocky 9 tools repo with Rocky 8

---

salt/mirror/etc/minima.yaml
salt/repos/default.sls

RES9 is being renamed to EL9 due to the phasing out of RES in favour of SLL.
This PR introduces a variable `rhlike_client_tools_prefix` that maps to either `EL` or `RES` according to the release.
This PR also renames existing variable `centos_client_tool_prefix` to the same name.

Add EL 9 manager tools

---

salt/repos/default.sls

fix testsuite error on enabling repos for prometheus test.
The test enable also the "tools update" repo which does not exist when the product_version grain is set to "uyuni-pr"

PR testsuite should test like master

---

salt/default/ids.sls

Create /var/lib/dbus directory if it does not exist yet to avoid this error:
```
Could not create /var/lib/dbus/machine-id.hqgEmrC1: No such file or directory
```

Create /var/lib/dbus directory if it does not exist yet

---

salt/repos/default.sls

Reverts uyuni-project/sumaform#1211
Hi ! This is not correct. This PR is adding a repo from opensuse mirror infrastructure:
`baseurl: http://{{ grains.get("mirror") | default("download.opensuse.org", true) }}/repositories/systemsmanagement:/Uyuni:/Master:/SLE15-Uyuni-Client-Tools/SLE_15/`
we are in purpose not using these repos in the `uyuni-pr`
We should use the repos from the worker instead:
See: https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/environments/common/pipeline-pull-request.groovy#L250

Revert "PR testsuite should test like master"

---

salt/default/avahi.sls

Otherwise we are relying on the repositories injected during the Cloud Init phase.
And I have a open PR to precisely get rid of these left-overs in Cloud init. (https://github.com/uyuni-project/sumaform/pull/1218)

Adding support for SLES15.4 in Avahi

---

salt/repos/default.sls
salt/repos/proxy.sls
salt/repos/server.sls
salt/repos/testsuite.sls
salt/repos/tools.sls

We have often problems with Uyuni repositories on opensuse.org as the metadata do not match the packages on the mirror we get redirected to.
This is a try to use downloadcontent.opensuse.org for repositories/systemsmanagement mostly for Uyuni repositories.
Let's see if we get better results with this setup.

Use original repo for uyuni repos

---

README_ADVANCED.md
README_TESTING.md
modules/virthost/main.tf
modules/virthost/variables.tf
salt/virthost/init.sls

This will add the possibility to parameterize the `hvm_disk_image` variable and use more than 1 image. 
See https://github.com/SUSE/spacewalk/issues/17238

Parameterize `hvm_disk_image` variable

---

backend_modules/libvirt/base/main.tf

The specific SP versions are removed as soon as a newer is available. Use always the latest by referencing the major version folder.

use latest Rocky Linux images

---

backend_modules/libvirt/README.md
backend_modules/libvirt/host/main.tf

This will increase the default RAM to 4GB on the virthost due to more demand when working with nested VMs in our test suite.
See https://github.com/SUSE/spacewalk/issues/17238

Increase default RAM on virthost

---

salt/server/download_ubuntu_repo.sh

The latest upgrade of HTML pages from download.opensuse.org is causing that our script for downloading ubuntu repos is now producing a non-zero retcode that is breaking our automation. The issue is caused because latest upgrades in the HTML from d.o.o is making our script to raise some exception while wget is recursively downloading.
This PR simply fixes the script by passing `--adjust-extension` to wget command in order to prevent the mess.

Fix "download_ubuntu_repo.sh" after changes in d.o.o repos

---

backend_modules/aws/base/main.tf
backend_modules/aws/host/main.tf
backend_modules/aws/network/main.tf
backend_modules/aws/network/variables.tf

This PR is implementing 2 things:
1. possibility to create new private and additional private networks with instances for a given public network and VPC. This allow multiple separated environments in the same Cloud VPC using the same mirror and bastion host
2. assign fixed private IP addresses to the instances. Together with "Route 53" we can have dedicated names for our instances.

Aws set private ip and support multiple environments

---

salt/server/download_ubuntu_repo.sh
salt/server/testsuite.sls

This PR reverts changes made at https://github.com/uyuni-project/sumaform/pull/1230 and properly fix the execution of `download_ubuntu_repo.sh` for "d.o.o" and also for other mirrors.

Fix execution of "download_ubuntu_repo.sh" for mirror servers

---

backend_modules/aws/host/main.tf
backend_modules/null/host/variables.tf
salt/default/hostname.sls
salt/server/setup_env.sh

In AWS we use Route 53 to provide meaningful hostnames for the systems.
We also make use of some tricks with CNAMES. 
To be able to use these hostnames, this PR add the possibility to overwrite the FQDN with a given value in the provider settings.
See also https://github.com/SUSE/spacewalk/issues/19888

overwrite host FQDN via provider settings

---

backend_modules/libvirt/host/user_data.yaml

Ubuntu 22.04 does not always fall back correctly to IPv6 when IPv6 route to the outside is missing, which is the case for now in Provo.
Remove these lines (and many other similar workarounds we did for IPv6 in the past) when IPv6 appears in Provo.

Disable IPv6 for apt-get until we have IPv6 in Provo

---

backend_modules/libvirt/host/user_data.yaml

Disable IPv6 for apt-get on Ubuntu 2004, too. Follow up of https://github.com/uyuni-project/sumaform/pull/1240

Disable IPv6 for apt-get on Ubuntu 2004

---

.ci-travis/salt-client-validation
.ci-travis/salt-minion-validation
.ci-travis/salt-server-validation
README_ADVANCED.md
backend_modules/aws/host/main.tf
backend_modules/azure/host/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/null/host/main.tf
backend_modules/null/host/variables.tf
backend_modules/ssh/host/main.tf
modules/build_host/main.tf
modules/build_host/variables.tf
modules/client/main.tf
modules/client/variables.tf
modules/host/main.tf
modules/minion/main.tf
modules/minion/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/registry/main.tf
modules/registry/variables.tf
modules/server/main.tf
modules/server/variables.tf
modules/sshminion/main.tf
modules/sshminion/variables.tf
modules/virthost/main.tf
modules/virthost/variables.tf
salt/default/init.sls
salt/repos/default.sls

This PR removes the `use_os_unreleased_updates` flag.
The plan is to start testing SLE updates with the build validation test suite. The MI numbers are passed through the usual json file.
The technical advantage over using `Maintenance:/Test:` aggregation of maintenance updates is that it is easier to spot the MI causing a regression, as we apply only one.
The organizational advantage is that we have not the bandwidth to follow another CI test suite that would retest periodically all features with the unreleased updates.

Deprecate use_os_unreleased_updates flag

---

salt/proxy/init.sls

Follow up of https://github.com/SUSE/spacewalk/issues/18094#issuecomment-1341160388
Currently it could happen that something goes wrong running configure-proxy.sh, but error is not visible (an example here https://github.com/SUSE/spacewalk/issues/18094#issuecomment-1341130039 ).  We should make this error visible

do not hide configure-proxy issue

---

salt/default/avahi.sls

- Fixes https://github.com/SUSE/spacewalk/issues/19969
- https://build.opensuse.org/package/show/systemsmanagement:sumaform:tools:avahi:0.8/avahi
- http://download.opensuse.org/repositories/systemsmanagement:/sumaform:/tools:/avahi:/0.8/15.4/

Use avahi 0.8 on Leap/SLES 15.4

---

salt/first_deployment_highstate.sh

`/etc/os-release` in SLE Micro 5.3 is:
```
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="SUSE Linux Enterprise Micro 5.3"
ID="sle-micro"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro:5.3"
```
we need to adapt the script used as provisioner for the first deploy

fix SLE Micro 5.3 provisioner

---

README_ADVANCED.md
README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc
salt/virthost/init.sls

In the `.bashrc` on the controller we need to set environment variables for all VMs we use in the test suite. For the nested VMs this becomes a problem since we create and define them only on the `virthost`.
We need to transfer information from the `virthost` minion to the `controller` if we use nested VM images.
All solutions regarding Salt cannot be achieved because the controller is not managed via Salt and therefore cannot interact with the Salt master.
Adjust the `cucumber_testsuite` and `controller` module to be able to handle the `hvm_disk_image` variable of the `virthost`.
Using the [Salt Mine](https://docs.saltproject.io/en/3004/topics/mine/index.html#the-salt-mine) is not possible because it was disabled in SUMA due to performance issues in the past.
@meaksh pointed out to use …

`cucumber_testsuite` and `controller` changes for nested VMs

---

salt/default/time.sls

Use by default chrony except in specific cases, SLES 11.4, Debian 10 and Leap. Those use ntp.
Without this we don't set ntp or chrony in ubuntu, debian, ol, almalinux, rocky and in BV where we do use them we see failures because the clock drifts.

Use by default chrony except in specific cases

---

salt/default/time.sls

Fix time state to use ntpd in Leap instead of ntp. Partially reverts https://github.com/uyuni-project/sumaform/pull/1256 and fixes the issue for the controller in HEAD.

Fix time state to use ntpd in Leap

---

salt/first_deployment_highstate.sh
salt/highstate.sh
salt/post_provisioning_cleanup.sh
salt/wait_for_salt.sh

This PR makes sumaform to use `venv-salt-call` if available instead of  `salt-call` for running the provisioning of the new instances. As we are moving to Salt Bundle, there are instances now where classic `salt-call` is not really available.
Addtionally, this PR introduces a mechanism to check that `cloud-init` is not still running before we start with the provisioning, as it was detected that sometimes `salt-call` execution starts with `cloud-init` still installing packages on the instance.

Make sumaform to use "venv-salt-call" for deployments if available and wait for "cloud-init" to finish

---

backend_modules/aws/host/main.tf
backend_modules/azure/host/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/ssh/host/main.tf
salt/first_deployment_highstate.sh
salt/highstate.sh
salt/post_provisioning_cleanup.sh
salt/wait_for_salt.sh

This PR is a continuation of https://github.com/uyuni-project/sumaform/pull/1264, in order to fix some issues:
- Grains are deployed after initial `wait_for_salt.sh` script runs, so grains are not properly captured in case of Salt Bundle.
- Sumaform deploys grains to `/etc/salt/grains` and this directory might not exist if there is only Salt Bundle.
In order to fix these issues, this PR does the following changes:
- sumaform grains are now set to `/tmp/grains` instead of directly to `/etc/salt/grains` (which might not exist)
- the deployment of `/tmp/grains` is now done before initial `wait_for_salt.sh` execution.
- the initial stage, `wait_for_salt.sh`, waits for cloud-init and then check the expected salt installed, then it copies grains to `/etc/salt/grains` or …

Do not use "/etc/salt/grains" as the place to deploy sumaform grains

---

salt/wait_for_salt.sh

As mentioned, this PR increases the waiting time for "cloud-init" to finish. We have noticed that in certain environments, the current waiting time (100 sec) was not really enough. 
This PR increases this to 500 sec.

Increase retries when waiting "cloud-init" to finish

---

modules/controller/variables.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc
salt/virthost/init.sls

After adding a static hostname for the nested VM in the infrastructure repository, I need to make adjustments here, too.
- `min-nested` is the default name for nested minions. Furthermore we only need one default hostname.
- `MIN_NESTED` is the default environment variable that is exposed on the controller.

Adjust virthost for static nested VM hostname

---

salt/virthost/init.sls

This will add the official Leap 15.4 repositories and install e.g. the `venv-salt-minion` package in order to not have to sync the complete Leap 15.4 repository in the test suite CI servers to be able to bootstrap this nested VM. Furthermore I added `nss-mdns` and  `qemu-guest-agent` like we do in sumaform.

Fix for nested Leap 15.4 VM

---

modules/base/main.tf

When setting false to eip bastion in main.tf base, the variable is not correctly setup in sumaform.
Fix the base module to correctly handle the variable.

Correctly handle eip bastion variable

---

README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc

This will add a new variable to the `controller` and `cucumber_testsuite` module to be able to specify MAC addresses for a nested VM. We need this to be able to specify MAC addresses for the Salt bundle migration tests in our CI test suite. Before they were defined in an array in the test suite code which was not optimal.
I tested this locally. After deploying a environment, I see the correct exports.
```bash
uyuni-ctl:~ # cat .bashrc | grep NESTED
export MIN_NESTED="['uyuni-master-min-nested'].tf.local"
export MAC_MIN_NESTED="['aa:b2:93:01:00:df']"
```
- https://github.com/SUSE/spacewalk/issues/17238
- https://github.com/uyuni-project/sumaform/pull/1278

QE: Add `nested_vm_macs` variable

---

salt/controller/bashrc

Fixup for the nested VM code related to getting the correct value for the MAC address and the hostname.
Before:
```bash
uyuni-ctl:~ # cat .bashrc | grep NESTED                                                                                                                                       
export MIN_NESTED="['uyuni-master-min-nested'].tf.local"                                                                                                                      
export MAC_MIN_NESTED="['aa:b2:93:01:00:df']" 
```
After:
```bash
uyuni-ctl:~ # cat .bashrc | grep NESTED
export MIN_NESTED="uyuni-master-min-nested.tf.local"
export MAC_MIN_NESTED="aa:b2:93:01:00:df"
```

Fixup for nested MAC and hostname

---

README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc

Revert the nested VM variables from a list to a string since we only support one nested VM in the test suite for now.

Revert nested VM variables from list to string

---

salt/controller/bashrc

This fixes a logic issue for the nested VM parameters in the Jinja templates on the controller. We basically need need 2 distinct `if` conditions instead of an `elseif`. Furthermore it aligns the formatting to the other code.

Fix logic error for nested VM parameters

---

salt/controller/bashrc

This will not remove the empty line before the `if` condition. See
```bash
export MAC_MIN_NESTED="aa:b2:93:01:00:3b"
````

Do not remove empty line before if condition

---

salt/server/tomcat.sls

I'm trying to clean up all the tomcat custom configuration in uyuni and sumaform. Currently we have configuration in:
- `/etc/sysconfig/tomcat`
- `/etc/tomcat.conf`
and apply them requires parsing the content with some regex.
This change is aligned with the ones that I'm having for `uyuni`, where each different configuration is in a different file in `/etc/tomcat/conf.d/*conf`
Fixes https://github.com/SUSE/spacewalk/issues/19824

change remote debug tomcat configuration

---

salt/server/testsuite.sls

This PR enables the use of `testing_overlay_devel_repo` repository for the PR CI.

QE: Re-enable testing_overlay repo for prs CI 

---

backend_modules/libvirt/host/user_data.yaml
salt/proxy/init.sls
salt/virthost/init.sls

- Switch all EL9 clients to the Uyuni Stable client tools since they are now released
- Fix client tools for the Uyuni Proxy

Differentiate between Uyuni Master and Stable

---

backend_modules/aws/base/ami.tf

change the image owner to the one mentioned in here: https://ubuntu.com/server/docs/cloud-images/amazon-ec2
I have tested the lookup and the returned AMI is valid from this list: https://cloud-images.ubuntu.com/locator/?_ga=2.257394819.988291425.1682329785-1164604681.1682329785

update owner filter for ubuntu aws ami

---

salt/mirror/etc/minimum_repositories_testsuite.yaml

Add RES8 test tool repository to minimal mirror list for AWS

Add RES8 test tool repository to minimal mirror list for AWS

---

backend_modules/libvirt/host/user_data.yaml
salt/default/ids.sls
salt/default/minimal.sls
salt/default/time.sls
salt/minion/init.sls
salt/minion/testsuite.sls
salt/mirror/etc/minima.yaml
salt/repos/init.sls
salt/repos/testsuite.sls
salt/server/testsuite.sls

This will fix issues found during deploying our new Uyuni BV pipeline.
- add SLE Micro 5.4 to the minima configuration
- fix SLE Micro 5.x issues
- `salt-minion` vs. `venv-salt-minion` related issues
- Cobbler adjustments for the server
Before merging, I will squash and sort the commits according to the change.
Partially fixes https://github.com/SUSE/spacewalk/issues/16082

Fix Uyuni build validation issues

---

backend_modules/libvirt/host/user_data.yaml

The `failovermethod` parameter got removed in DNF starting with EL8. I discovered that when using the verbose parameter with DNF on Liberty Linux 9. See https://github.com/rpm-software-management/libdnf/blob/dnf-4-master/docs/release_notes.rst#0640-release-notes
Split out of https://github.com/uyuni-project/sumaform/pull/1287

Remove deprecated `failovermethod` for RHEL/EL8

---

salt/server/testsuite.sls

This adds `uyuni-released` to the `products_using_new_cobbler_version` variable since it is also using the new Cobbler version.
Split out of https://github.com/uyuni-project/sumaform/pull/1287

Fix for Cobbler on `uyuni-released` version

---

salt/proxy/init.sls

Require field expect an id not a package name.
```
proxy-container-packages:
pkg.installed:
- pkgs:
- uyuni-proxy-systemd-services
```
So, instead of using `uyuni-proxy-systemd-services` I need to use `proxy-container-packages`

Require field expect an id not a package name

---

backend_modules/libvirt/host/user_data.yaml

Clean up  cloud-init so that we do not install both the bundle and normal `salt-minion` packages.

Do not install both venv-salt-minion and salt-minion

---

salt/repos/additional.sls

Fix deployment issue : 
```
ID: 28935_repo
Function: pkgrepo.managed
Result: False
Comment: Failed to configure repo '28935_repo': sequence item 9: expected str instance, int found
Started: 05:00:31.625197
Duration: 216.064 ms
```
It seems `pkgrepo.managed:` in salt when humanname variable is only number and -/_ is not correctly supported.
I tried to force label to string but I had the same issue ( `{% set label_str = label | string %}` ).
This just add repo string extension after label ( done automatically by sumaform previously but still failing sumaform deployment )

Add repo to humanname when adding additionnal rapository.

---

salt/default/ids.sls
salt/default/minimal.sls
salt/minion/init.sls
salt/minion/testsuite.sls

This fixes issue regarding the distinction between Salt and the Salt bundle in the `minimal` state.
- CentOS 7 (minion and client) is failing in BV in the deployment stage
- Alma / Rocky do not have the `venv-salt-minion` service running
- Liberty is trying to install `salt-minion`, although the package is not available and we specified in sumaform to use `venv-salt-minion`
```bash
10:28:26  │ Error: remote-exec provisioner error
10:28:26  │ 
10:28:26  │   with module.centos7-sshminion.module.sshminion.module.host.null_resource.provisioning[0],
10:28:26  │   on /home/jenkins/jenkins-build/workspace/uyuni-master-qe-build-validation-NUE/results/sumaform/backend_modules/libvirt/host/main.tf line 249, in resource "null_resource" "provisioning":
10:28:26  │  249:   provisioner "remote-exec" { …
```

Fix distinction between Salt and Salt bundle

---

backend_modules/libvirt/host/user_data.yaml

This PR makes `cloud-init` to configure corresponding Client Tools channels in SLE/openSUSE images, in order to have a configured repository which is able to provide `venv-salt-minion` package to run the deployment.
This should fix the current issue we see on our testsuites deployments: https://github.com/SUSE/spacewalk/issues/21545
I've tested deployments of SLE12SP4 and SLE15SP4/SP3 instances with these changes and they were successful.

Make "cloud-init" to setup a repo that provides "venv-salt-minion" package

---

salt/minion/init.sls

Creating a minion with `install_salt_bundle = true` was failing with the following error:
```
---------
ID: master_configuration
Function: file.managed
Name: /etc/salt/minion.d/master.conf
Result: False
Comment: Parent directory not present
Started: 09:31:23.345210
Duration: 0.943 ms
Changes:
---------
ID: minion_service
Function: service.running
Name: venv-salt-minion
Result: False
Comment: One or more requisite failed: minion.master_configuration
Started: 09:31:23.346503
Duration: 0.002 ms
Changes:
---------
```
Now it's the file `/etc/venv-salt-minion/minion.d/master.conf` that keeps the master configuration in the minion in case we want it to be managed with Salt Bundle.

Manage proper configuration file if the minion is Bundle managed

---

backend_modules/aws/host/user_data.yaml
backend_modules/libvirt/host/user_data.yaml

This PR works around https://the-codeslinger.com/2020/03/26/debian-bullseye-the-repository-does-not-have-a-release-file/ (it was already done for AWS, now doing it for libvirt as well).
I am not completely sure why this is needed: I had a look at the qcow2 file `debian11o` that we download, and its `/etc/apt/sources.list` file is correct...

Work around "The repository does not have a Release file"

---

backend_modules/libvirt/base/main.tf

Cloud-init only runs on images that end with 'o'...

Rename opensuse154-ci-pr to opensuse154-ci-pro, to run cloud-init

---

modules/server/main.tf
modules/server/variables.tf
salt/server/rhn.sls

This PR configures c3p0 connection timeout. It is useful for detecting leaked connections, like in https://github.com/SUSE/spacewalk/pull/21717
It configures timeout 900s by default. It can be changed by setting grain
`c3p0_connection_timeout = <timeout>`
or disabled with
`c3p0_connection_timeout = false`
Additional debug output can be enabled with
`c3p0_connection_debug = true`
It is disabled by default, because it causes certain overhead.

Configure c3p0 connection timeout

---

salt/post_provisioning_cleanup.sh

We can have venv-salt-minion in combination with salt-master and salt-api. Actually, we use venv-salt-minion with sumaform to install all the necessary packages, including salt/python3-salt (salt-master and salt-api).
What is incompatible, is having salt-minion and venv-salt-minion. See https://github.com/SUSE/spacewalk/issues/21704 .
However, if we remove salt and python3-salt, this removes patterns-uyuni_server. (see https://github.com/SUSE/spacewalk/issues/21704 ).
Thus, what we really need is to remove salt-minion if venv-salt-minion is installed.
This fixes https://github.com/SUSE/spacewalk/issues/21704

Only remove salt-minion

---

salt/default/avahi.sls
salt/default/init.sls
salt/default/minimal.sls

Most of SLE Micro setup was disabled because of some problems with package updates. This resulted for example in no hostname for SLE Micro 5.1 and 5.2. We can't disable all initialization at once.
The idea with SLE Micro is to prepare all packages in the image and having no package to update in sumaform - merely to check everything is there. However, `pkg.install` does not do the job because it is impossible to acquire a rpm lock  on a read-only filesystem.
Fixes https://github.com/SUSE/spacewalk/issues/21792

Prepare SLE micro properly

---

backend_modules/aws/host/user_data.yaml

Remove priority for AWS user_data
This cloud init repositories have only venv-salt-minion version 3004 and so bock upgrade.

Remove priority from user data AWS

---

salt/mirror/etc/minimum_repositories_testsuite.yaml
salt/server/additional_disk.sls

The urls were incorrect for res8 and res7 suma tool in minimum repo list.
As a remember, minimum_repositories_testsuite.yaml is the minimum list of repositories needed to run the testsuite in AWS.
It's used to create internal and external mirror with this repositories.

Fix url issues for res8 in minimum_repositories_testsuite.yaml

---

modules/cucumber_testsuite/main.tf

Now that we use count to enable or disable the server modules in the cucumber_testsuite module, terraform generates an array of their configurations, even though there is just one.

cucumber: now terraform creates an array of server* configurations

---

salt/repos/default.sls

Fix the GPG key issue with RHEL 8 clones for BV.
Fixes https://github.com/SUSE/spacewalk/issues/21955

Import gpg key for RES8

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf

Remove sles12sp4 ami search because sles12sp4 was removed from AWS

sles12sp4 ami not available anymore on AWS

---

salt/server/rhn.sls

We want to be in control on what the server is doing during our testsuite to avoid any instability.
This PR disable the auto_generate_bootstrap_repo when testsuite is true on server side.
I reuse the testsuite variable to avoid adding new variable.
It tested the change and it works as expected.

Disable auto_generate_bootstrap_repo when running the testsuite

---

salt/server_containerized/install_podman.sls

See title. Fixing https://github.com/SUSE/spacewalk/issues/22103 together with https://github.com/uyuni-project/uyuni-tools/pull/9

Add netavark on podman hosts for IPv6-capable networks

---

salt/server/rhn.sls
salt/server_containerized/rhn.sls

With Uyuni we have much more packages that get synced compared to SLES. This limits the amount of changelogs to download and keep.
See
- https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/tuning-changelogs.html
- https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace

Limit changelog entries per package

---

salt/repos/server_containerized.sls

use ServerContainer repo also in k3s (required by `uyuni-tools` )

use ServerContainer repo also in k3s

---

salt/server_containerized/uyuniadm.yaml

Use localhost reportdb hostname to avoid hairpins.

containers: use localhost for the reportdb

---

salt/repos/server_containerized.sls

No need to mirror a temporary repo: it would only force us to mirror it.

Don't use mirror for ServerContainer branch repo

---

salt/server/taskomatic.sls
salt/server/tomcat.sls

In order to debug this bug https://bugzilla.suse.com/show_bug.cgi?id=1212498
We want to have more fine trace logs in Java side, so we can understand what Taskomatic and SaltServerActionService (from Tomcat) side are doing.

This tweak enable some logs to debug hibernate and SaltServerActionService

---

salt/build_host/init.sls

Since we kill the openSUSE Leap reposync in the test suite, we have to install the kiwi package in order to be able to successfully bootstrap the buildhost. We also see failures regarding this in our 4.3 CI.
See https://github.com/SUSE/spacewalk/issues/22440

Add kiwi packages to buildhost

---

salt/build_host/init.sls

This will rename the Salt step used for the Kiwi package on the build host.

Rename Salt state for kiwi package on build host

---

README_ADVANCED.md
modules/server/main.tf
modules/server/variables.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server/taskomatic.sls
salt/server/tomcat.sls

This PR creates two new variables to enable additional java logs.
Before this PR all the java debug logs were handled by the same variable, but this variable "java_debugging" is set by default as "true".
This was generating too many overhead for regular cases, so now, we have two more variables to switch debug logs for Hibernate and SaltService.

Adding two additional variables to enable additional java debugging

---

modules/controller/main.tf

Reverts uyuni-project/sumaform#1389
That was a good idea :) . Dependencies were failing to be installed.

Revert "Update controller to leap 15.5"

---

backend_modules/aws/base/ami.tf

Bump RHEL version. RHEL-8.2 is not available anymore

Upgrade rhel 8 version ( 8.2 not available anymore)

---

backend_modules/null/base/variables.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc
salt/server/setup_env.sh
salt/server_containerized/uyuniadm.yaml

This PR removes the requirement for the SCC Credentials, allowing to set up an environment without them.
Fixes https://github.com/SUSE/spacewalk/issues/22501

Allow setting up an environment without SCC credentials

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml

RHEL 8.2 AMI was removed. Switch to latest 8.8 version.
RHEL 9.0 also replaced by 9.2 version

Update RHEL ami

---

salt/controller/init.sls

For the container tests we need to move the redfish mock server to the controller. For this we need unzip to unpack the Redfish archive.

Add unzip package to the controller

---

README.md

In this PR, I am documenting:
* Libvirt prerequisites: this seemed reasonable to me since the section also contains description of installing the `terraform-provider-libvirt` package
* Variables: a newcomer to Uyuni probably won't know what `CC` stands for. Additionally, the `images` section might be helpful

fix(README): Document prerequisites and common variables for deployment

---

backend_modules/null/host/main.tf

In github action, we are using null backend for testing our main.tf. This backend doesn't support public names needed for AWS. 
In this PR, I'm adding a default publis_names variable ouput for null backend
```
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 717, in output "aws_mirrors_public_name":
│  717:   value = module.mirror.configuration.public_names
│     ├────────────────
│     │ module.mirror.configuration is object with 3 attributes
│ 
│ This object does not have an attribute named "public_names".
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

Add public names output value to null backend

---

README_ADVANCED.md
modules/controller/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/repos/additional.sls
salt/repos/proxy43.sls
salt/repos/proxyUyuni.sls
salt/repos/server43.sls
salt/server/postgres.sls
salt/server/testsuite.sls

We need to run tests on PRs with 4.3. This is essentially a 4.3-nightly with the "Trusted=yes" for debian/ubuntu repos.

Add 4.3-pr product version

---

modules/server_containerized/variables.tf
salt/repos/server_containerized.sls

While at it bump the server container host default image to Leap 15.5.

Update the containerized server repo to get uyuni-tools from

---

salt/build_host/init.sls
salt/repos/build_host.sls

When running the build hosts in the cloud this package is required.
In future the cloud images should contain it pre-installed.
But for now let's take care that it gets installed during setup

install python-instance-billing-flavor-check on buildhost

---

salt/repos/default.sls

While reviewing sumaform's code with Julio, we noticed those two places where `4.3-released` case has apparently been forgotten. This PR fixes that.
**Note:** to avoid this problem in the future, it could be a good idea to refactor, testing `contains(..., '-released')` to cover all `4.x-released` cases, while taking care of the fact that `uyuni-released` also exists.

We forgot 4.3-released case

---

.github/workflows/mirror-update-warning.yml

- Fix the action execution (404 erorrs) by using different workflows
- Report the list of updated images in the comment
- Comment on the PR instead of individual commits
See it in action: https://github.com/cbbayburt/sumaform/pull/2#issuecomment-1820784218

Fix and enhance mirror-update-warning action

---

salt/salt_testenv/init.sls

We need libhttp_parser_2_7_1, which is a dependency of libgit2. It's available in our SUMA Server channel, but that's only for a single SLE SP. Since it's also in the HPC Module, we can use that repo.

Add SLE-HPC-Module to Salt Testenv 

---

salt/mirror/etc/minimum_repositories_testsuite.yaml

To run the BV tests on AWS, we need the minion tool repositories. This list is the minimum you need to run the tests on AWS.
Update the minimum repository list to run BV on AWS with ubuntu2204 tool repo

Remove useless repository for RES 8 and add ubuntu2204 tools repo

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

Add the possibility to test paygo images on controller. 
To do so, add new bashrc variable related to paygo image

Add support to paygo images on controller

---

backend_modules/null/base/main.tf
backend_modules/null/base/variables.tf

Those parameters have been moved to server and proxy module. They are not used in base module

Those parameters have been moved to server and proxy module

---

salt/repos/build_host.sls

`os_pool_repo` is needed this time as a dependency of `python-instance-billing-flavor-check`.
Original explanations from Michael:
```
When running the build hosts in the cloud this package is required.
In future the cloud images should contain it pre-installed.
But for now let's take care that it gets installed during setup
```

os_pool_repo is needed anyway on build host

---

salt/repos/build_host.sls
salt/repos/default.sls

Here in repos we need to check different as the negate is happening for all the grains check
`not (grains.get("...") or grains.get("...") or 'payg' in grains.get("...") | default('', true))`
This makes also the fix from @Bischoff obsolete (I had to revert it as it creates now a duplicate ID)

fix enabling of repos

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

For paygo testing, I need to bootstrap a byos without SCC. This instance should fail to bootstrap.
That's why I have two sles15sp4 instance
- sles15sp4-byos-minion => fail bootstrap without SCC
- sles15sp4-minion => run default minion pipeline once I add SCC credential

Add sles15sp4 byos instance support to controller

---

modules/controller/main.tf
modules/controller/variables.tf
salt/controller/bashrc

Related to https://github.com/SUSE/spacewalk/issues/22410
This PR adds the entries needed in order to test the migration from a Salt minion (OS Salt)  to the Salt bundle on a dedicated host, removing the need for a nested VM.
Note: `salt_migration_minion` is just a placeholder name

Add Salt migration minion entries

---

README_ADVANCED.md
README_TESTING.md
modules/controller/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/mirror/etc/minima.yaml
salt/repos/default.sls
salt/scc/proxy.sls
salt/scc/server.sls

Remove oldies: SUSE Manager 4.0 and 4.1.
(note about the minima part: this code is used only when creating a new mirror from sumaform ; the cleanup is already done in our permanent mirrors).

Remove 4.0 and 4.1

---

.github/workflows/ci-validation/salt-server-validation
.gitignore
README_ADVANCED.md
backend_modules/aws/host/main.tf
backend_modules/azure/host/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/null/host/variables.tf
backend_modules/ssh/host/main.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
modules/host/main.tf
modules/server/main.tf
modules/server/variables.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server/additional_disk.sls

This is a PR to parametrize the partition size for /var/lib/pqsql, aiming to solve not enough disk space issues in our CI tests.
To use it, you need to set this variable (on GB) in your main.tf:
```
server = {
...
database_disk_size = 50
}
```

Additional disk for /var/lib/pgsql partition custom size

---

README_TESTING.md
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/controller/bashrc

Related to https://github.com/SUSE/spacewalk/issues/22410
We'll test the migration from OS Salt to Salt bundle only on a dedicated BV host.
The entries for a minion running in a nested VM are thus no longer needed.

Remove nested VM entries

---

backend_modules/azure/host/main.tf
backend_modules/libvirt/host/main.tf
backend_modules/null/host/variables.tf
modules/cucumber_testsuite/main.tf
modules/server_containerized/variables.tf

Title - keep the same convention when defining disk sizes.

Use 0 as default value for disk sizes

---

backend_modules/feilong/host/main.tf

with 20 GB i cannot spawn 4 VMs on 0C LPAR - reducing to 12 GB each

Less disk for s390

---

backend_modules/ssh/host/main.tf

This PR fixes an issue with `ssh` backend module, where `install_salt_bundle` grain is not available. Leading to this errors during deployment:
```
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'install_salt_bundle'; line 15
```
/cc @Etheryte

Add "install_salt_bundle" flag to ssh backend grains

---

salt/salt_testenv/init.sls

This PR just fixes the `salt_testenv` and makes Salt testsuite executor to be installed on hosts where the classic Salt package is being installed: at the moment for SLE15SP1+.

salt_testenv: install "python3-salt-test" package on nodes with Salt classic package

---

salt/server_containerized/initial_content.sls

To avoid network hairpins, spacecmd should use its default values to connect the server from a container.

Container server should no longer have the spacecmd config

---

salt/default/network.sls

SLE Micro uses Network Manager, and Network manager enables IPv6 privacy by default.

We want predictable IPv6 addresses: disable privacy

---

salt/default/network.sls

IPv6 does not need fixing in SLE Micro 5.1 and 5.2

SLE micro 5.1 and 5.2 use wicked

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
modules/cucumber_testsuite/main.tf

This PR refactor the cloud-init support for slemicro5.5, to be able to deploy it as a regular minion, instead of a containerized server.
It also removed an entry in the list of images, as we were duplicating the URL, and when deploying a sle micro 5.5 minion with `slemicro55-ign`, it seems there was some error in the image and we did not have the repositories in place.

Support cloud-init on slemicro55o for not containerized servers

---

.github/workflows/ci-validation/salt-server-containerized-validation

Add the `product_version` grain to the containerized server tests. We also have this defined in the normal server tests.
Necessary for e.g. https://github.com/uyuni-project/sumaform/pull/1475

Add `product_version` to cont. server validation

---

salt/server_containerized/testsuite.sls

Fix the empty `require:` statement.

Fix: Empty `require:` due to if statement

---

backend_modules/libvirt/host/user_data.yaml

Without the fix I get: 
```
│ Error: failed to render : <template_file>:407,1-11: Unexpected endif directive; The control directives within this template are unbalanced.                                                                      
│                                                                                                                                                                                                                  
│   with module.sles15sp4o.module.host.data.template_file.user_data,                                                                                                                                               
│   on backend_modules/libvirt/host/main.tf line 47, in data "template_file" "user_data": …
```

Fix if statement end

---

salt/default/avahi.sls

For SLE Micro there should be nothing to install from the states, so we would like to skip the update of avahi packages.

Skip updating avahi packages on SLE Micro

---

salt/default/network.sls

Let IPv6 changes to SLE micro survive a reboot.
In Network Manager world, `nmcli device` is apparently transient, while `nmcli connection` seems to be permanent.

Make IPv6 changes to SLE micro permanent

---

salt/repos/default.sls

/ibs/ is only part of the URL when we download from a mirror

fix URL or SLES15-SP4-LTSS repository

---

README_ADVANCED.md
backend_modules/libvirt/README.md
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/main.tf
main.tf.libvirt-testsuite.example
modules/controller/main.tf
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
modules/proxy/main.tf
modules/proxy/variables.tf
modules/server/main.tf
modules/server/variables.tf
salt/default/avahi.sls
salt/default/minimal.sls
salt/default/testsuite.sls
salt/repos/default.sls
salt/repos/proxy43.sls
salt/repos/server43.sls
salt/server/additional_disk.sls
salt/server/postgres.sls
salt/server/testsuite.sls

Preparing SLE15SP4 EOL, new SUMA4.3 releases will be image based. This PR adds support for `4.3-VM` and `4.3-VM-released` version.
Another changes:
- add support to use jump hosts for libvirt provider
- ensure base repos are present before installing avahi
- 4.3-VM uses tools from cloud environment to setup data disks. This PR allows sumaform to use it.

Allow SUMA4.3 VM image

---

salt/server_containerized/initial_content.sls
salt/server_containerized/mgradm.yaml

Now that mgradm install [kubernete|podman] can create the first user use this feature rather than querying the API ourselves.

Create first user using mgradm

---

backend_modules/libvirt/host/user_data.yaml

Fix repository installed twice:
```
[2024-02-16T18:19:45.729Z] module.slemicro55-sshminion.module.sshminion.module.host.null_resource.provisioning[0] (remote-exec):
Comment: Failed to configure repo 'test_repo_rpm_pool': Repository 'test_repo_rpm_pool' already exists as 'test_packages_pool'.
```

Remove duplicate repository

---

salt/default/avahi.sls

the default repo should have been in the "if" clause.

fix default repo for avahi installation

---

README_ADVANCED.md
backend_modules/libvirt/host/main.tf
backend_modules/null/host/variables.tf
modules/server_containerized/variables.tf

This PR:
* allows to override the host name for libvirt like it's already possible for AWS
* removes the variable `overwrite_fqdn` definition from `host` and `server_containerized` modules,
as `overwrite_fqdn` is only used as a hash key in the provider settings map
* documents the functionality
* fixes typos in external database section of documentation (piggyback)
This for example allows me to have both PRV and NUE test suites on the same ARM server without conflicts at libvirt level.
By the way, shouldn't we name this key `override_fqdn` rather than `overwrite_fqdn`? :thinking:

Allow to override the host name for libvirt too

---

salt/default/init.sls

Conform to best practices.
According to https://tedboy.github.io/jinja2/templ13.html
```
The special constants true, false, and none are indeed lowercase. Because that caused confusion
in the past, (True used to expand to an undefined variable that was considered false), all three can
now also be written in title case (True, False, and None). However, for consistency, (all Jinja
identifiers are lowercase) you should use the lowercase versions.
```

Jinja booleans should be lower case

---

salt/salt_testenv/init.sls

This PR just includes the `SLE-Module-Containers` repositories when deploying Salt testenv nodes on SLE15[SP?] images, as we need as source for `docker` package (which is now a dependency for `python3-salt-testsuite`).
This should fix the issue we see for Salt Shaker in our internal CI: https://ci.suse.de/user/manager/my-views/view/Salt%20Shaker/job/manager-salt-shaker-products-next-sles15sp5/61/console

Add SLE-Module-Containers repos to Salt testenv nodes

---

salt/default/pkgs.sls
salt/server_containerized/large_deployment.sls

This fixes
- `large deployments` requirements on the containerized server. This is needed because of the following change: https://github.com/uyuni-project/sumaform/commit/37393f84eeb4a64d86a6b22a925d30ed9665618f#diff-af6a4441405654e0b2b396bf711aa3b290fe1c0bcba22c4489f79ba5f9e21b53: 
```diff
+ {% if grains['osfullname'] != 'SLE Micro' %}
uyuni-tools:
pkg.installed:
- pkgs:
- mgradm
- mgrctl
+ {% endif %}
```
in
https://github.com/uyuni-project/sumaform/blob/2ee9b10275c8b7609be7a985a86342e9f6f93745/salt/server_containerized/install_common.sls#L3-L9
```bash
suma-bv-50-srv:~ # rpm -q uyuni-tools
package uyuni-tools is not installed
uma-bv-50-srv:~ # which mgradm
/usr/bin/mgradm
suma-bv-50-srv:~ # rpm -qf /usr/bin/mgradm
mgradm-0.1.4-150550.1.1.develHead.x86_64
uma-bv-50-srv:~ # zypper info …
```

Containerization fixes found in 5.0 BV

---

backend_modules/libvirt/host/user_data.yaml

It was a typo in cloud-init for sle micro 5.5, when container_proxy.
So, we were not installing all that was necessary.

Fix cloud init for slemicro 5.5 when container_proxy

---

backend_modules/libvirt/host/user_data.yaml

If we have the grain **install_salt_bundle** we expect to have installed the salt bundle during the clound-init phase of the sle micro 5.5 deployment.

Install salt-bundle in sle micro 5.5 on cloud-init stage

---

backend_modules/libvirt/host/user_data.yaml

Install mgrctl when we deploy a containerized proxy.
We need it in the testsuite in order to onboard a proxy, as we will be using mgrctl cp server:<path_proxy_config>

Install mgrctl when we deploy a containerized proxy

---

backend_modules/libvirt/host/user_data.yaml
salt/proxy_containerized/init.sls

Install mgrtools in proxy containerized for Uyuni.
Until we move our Uyuni containerized proxy to use Leap Micro 5.5, this fix change will unblock us by installing mgrtools during the salt state.

Install mgrtools in proxy containerized for Uyuni

---

README.md
main.tf.libvirt-testsuite.example
main.tf.libvirt-testsuite.example.Manager-43
main.tf.libvirt.example
main.tf.libvirt.example.Manager-43

Change the main.tf libvirt examples to use container server

---

backend_modules/libvirt/host/user_data.yaml
salt/server_containerized/large_deployment.sls
salt/server_containerized/testsuite.sls

- [1.](https://github.com/uyuni-project/sumaform/pull/1513/commits/2616bd9e539722629184c5d4424ee693a060e92b) Since we use cloud-init to install the `uyuni-tools`, we can assume that they are already installed for SLE Micro and only require them for others distros. Partially reverts https://github.com/uyuni-project/sumaform/pull/1509. Cedric did the same with https://github.com/uyuni-project/sumaform/commit/37393f84eeb4a64d86a6b22a925d30ed9665618f
-[2.](https://github.com/uyuni-project/sumaform/pull/1513/commits/5d6eb33a99f62e7c74b690c034e557c4309319a6) we try to install the `*-dummy` test packages via cloud-init, but do not add the repository for them
```bash
transactional-update 4.1.6 started
Options: --continue --non-interactive pkg install andromeda-dummy milkyway-dummy virgo-dummy …
```

BV: Fix containerized server issues

---

modules/cucumber_testsuite/main.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server_containerized/mgradm.yaml

Since the first user creation is now mandatory in mgradm install, don't offer the choice anymore.
Related to https://github.com/uyuni-project/uyuni-tools/pull/192

Remove create_first_user variable for server_containerized

---

salt/mirror/configuration.sls

jdupes package url changed.
I tested the new version with the mirror deployment and I had not compatibility issues.

Update jdupes source

---

.github/workflows/ci-validation/salt-server-containerized-validation
modules/proxy_containerized/main.tf
salt/proxy_containerized/init.sls

This removes the deleted variable `create_first_user` in https://github.com/uyuni-project/sumaform/pull/1527 from the containerized proxy and the CI.

CI: Remove deleted variable `create_first_user`

---

modules/server_containerized/main.tf

Since there are still issues with installing k3s on Leap Micro, switch back to leap in the mean time to unblock everyone.

Revert default master server to Leap 15.5 image

---

salt/server_containerized/install_k3s.sls
salt/server_containerized/wait_for_kube_resource.py

If mgradm install runs before traefik had time to deploy the ingressroutetcp resources we wouldn't get any of the TCP and UDP ports exposed.

Wait for traefik to be started in k3s installs

---

salt/salt_testenv/init.sls

In order to allow some Docker related tests to run, we want "docker" service is enable when testing classic Salt package.

salt_testenv: start docker daemon after classic Salt testsuite installation

---

salt/server_containerized/mgradm.yaml

We found an issue in some tests, as we expected different values when we create the first org and the first user.
```
Scenario: Create admin user and first organization
Given I access the host the first time
When I go to the home page
And I enter "SUSE Test" as "orgName"
And I enter "admin" as "login"
And I enter "admin" as "desiredpassword"
And I enter "admin" as "desiredpasswordConfirm"
And I select "Mr." from "prefix"
And I enter "Admin" as "firstNames"
And I enter "Admin" as "lastName"
And I enter "galaxy-noise@suse.de" as "email"
And I click on "Create Organization"
Then I am logged in
```

QE: Align the org and first user to the values set in the Cucumber feature

---

README_ADVANCED.md
backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/network_config.yaml
modules/base/main.tf
modules/client/main.tf
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
modules/dhcp_dns/main.tf
modules/dhcp_dns/variables.tf
modules/dhcp_dns/versions.tf
modules/host/main.tf
modules/minion/main.tf
modules/proxy/main.tf
modules/pxe_boot/main.tf
modules/pxe_boot/variables.tf
modules/sshminion/main.tf

This PR makes it possible to deploy a DHCP and DNS server inside the private network. This is useful for the containerized proxy because it stops playing that role in Retail context.
This PR also stops inserting the traditional client and the normal minion into the private network. They were only used for ping tests.
This PR also works around a bug transmitting the configuration from AWS :cry: .
Some adaptation in the test suite will be needed, especially in containerized proxy context, but not only.
```bash
dhcp-dns:~ # ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 52:54:00:de:7d:2d brd ff:ff:ff:ff:ff:ff
altname enp0s3
altname ens3
inet 192.168.1.53/24 brd 192.168.1.255 scope global eth0
valid_lft forever …
```

DHCP and DNS host

---

modules/cucumber_testsuite/main.tf

Use integers as default values for disk sizes in ` lookup` calls.

Use integers as default for disk sizes

---

backend_modules/aws/base/iam_instance_profile.tf

To deploy paygo server on AWS, you need an IAM role with specific rights. 
This IAM role was also creating when deploying a BYOS server.
Fix the deployment to correctly not create the IAM role when deploying an BYOS server.

Fix an issue where role is also created when not using a paygo server.

---

backend_modules/libvirt/host/combustion
modules/proxy_containerized/main.tf
modules/proxy_containerized/variables.tf

We had a bootstrap issue because we were install salt-minion instead of venv-salt-minion in our containerized_proxy module

Fix install_salt_bundle in Containerized proxy

---

backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/main.tf

Install salt bundle, when required, through Combustion.
For instance, we need it to bootstrap the Containerized Proxy Host when it's running in a SLE Micro 5.5

Install salt bundle, when required, through Combustion

---

backend_modules/aws/host/main.tf

Currently, we can't modify the default main disk size ( 50Gib ). 
With this change, we will now use correctly main_disk_size variable to setup the main disk size.

Correctly handle the main disk size for aws host

---

modules/dhcp_dns/main.tf

The path to the PXE boot kernel depends on the context:
Traditional proxy:
* cobbler: `pxelinux.0`
* retail: `boot/pxelinux.0`
Containerized proxy:
* cobbler: `pxelinux.0`
* retail: `pxelinux.0`
This PR takes the new and "most common" location as default value.

PXE kernel: use by default the path for containerized proxy

---

backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/main.tf
modules/server_containerized/main.tf
salt/default/minimal.sls
salt/repos/additional.sls
salt/server_containerized/testsuite.sls

Add Leap Micro to sumaform and use it by default for PR testing.
Because of Leap Micro being transactional, we need to install any additional package with combustion

Add Leap Micro with combustion and make it default for PR testing

---

modules/dhcp_dns/main.tf

For example, use `db.50.168.192.in-addr.arpa`  for BV 5.0 instead of `db.1.168.192.in-addr.arpa`.

Fix wrong name for reverse master file

---

README_ADVANCED.md
modules/dhcp_dns/main.tf
modules/dhcp_dns/variables.tf

The worker and the hypervisor may be two different hosts.
Reminder: the DHCP and DNS server is exclusively on the private network.

Add a jump host for the DHCP and DNS server

---

backend_modules/null/host/variables.tf
modules/build_host/variables.tf
modules/client/variables.tf
modules/minion/variables.tf
modules/mirror/variables.tf
modules/proxy/variables.tf
modules/server/variables.tf
modules/server_containerized/variables.tf
modules/sshminion/variables.tf
modules/virthost/variables.tf

This PR change the default value of _install_salt_bundle_ variable in the majority of modules.
It keeps untouched the host modules from other backends.
The aim of this refactor is to simplify our main.tf for most of our environments, where we were replacing the value of this variable in almost all the cases.

Change the default value of install_salt_bundle to true

---

modules/cucumber_testsuite/variables.tf
modules/proxy_containerized/main.tf
salt/repos/proxy_containerizedUyuni.sls

Use Leap Micro in Uyuni Proxy Containerized.
This change the default image for all the uyuni product versions.
**WARNING**:
- We need to change the default image if we are under a K3S deployment. In such case, for now, we will keep using Leap Micro 5.5, to be aligned with the server, as we encountered some technical issues there.
**Related PR**:
- https://github.com/SUSE/susemanager-ci/pull/1190

Use Leap Micro in Uyuni Proxy Containerized

---

modules/server_containerized/main.tf

Use leap Micro in Uyuni Server Containerized
https://github.com/SUSE/spacewalk/issues/24037

Use Leap Micro in Uyuni Server Containerized

---

backend_modules/libvirt/host/combustion

To solve this issue deploying a Leap Micro 5.5 VM
```
transactional update # zypper lr
Repository priorities are without effect. All enabled repositories share the same priority.
--+--------------------+------------------------------+---------+-----------+--------
1 | ca_suse            | ca_suse                      | Yes     | (r ) Yes  | No
2 | container_utils    | container_utils              | Yes     | (r ) Yes  | No
3 | repo-debug         | Leap Micro Debug Repository  | No      | ----      | ----
4 | repo-main          | Leap Micro Main Repository   | Yes     | (r ) Yes  | Yes
5 | repo-sle-update    | SLE Micro Update Repository  | Yes     | (r ) Yes  | Yes
6 | repo-source        | Leap Micro Source Repository | No      | ----      | ----
7 | test_packages_pool | …
```

Adding Uyuni Client Tools for Leap 15 in Combustion

---

backend_modules/aws/host/main.tf

Currently, using the overwrite_fqdn will create wrong fqdn with a double `-`.
Remove this issue by removing the extra `-` in sumaform.

Fix system domain to avoid having double -

---

salt/default/network.sls

Before:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether aa:b2:93:01:00:22 brd ff:ff:ff:ff:ff:ff
(...)
inet6 2a07:de40:b208:1:b6b6:4e36:289d:e13c/64 scope global dynamic mngtmpaddr noprefixroute 
valid_lft 2591520sec preferred_lft 604320sec
(...)
```
Running command:
```
uyuni-master-podman-pxy:/etc/salt # nmcli device modify eth0 ipv6.addr-gen-mode eui64
Connection successfully reapplied to device 'eth0'.
```
After:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether aa:b2:93:01:00:22 brd ff:ff:ff:ff:ff:ff
(...)
inet6 2a07:de40:b208:1:a8b2:93ff:fe01:22/64 scope global dynamic mngtmpaddr noprefixroute 
valid_lft 2591996sec preferred_lft 604796sec
(...)
```

SLE Micro uses Network Manager too

---

modules/proxy_containerized/versions.tf

Fixes this:
```
jenkins@jenkins-worker:~/workspace/manager-5.0-qe-build-validation-PRV/results/sumaform> terraform validate
╷
│ Error: Provider libvirt is undefined
│
│   on main.tf line 355, in module "proxy_containerized":
│  355:     libvirt = libvirt.terminus
│
│ Module module.proxy_containerized does not declare a provider named libvirt.
│ If you wish to specify a provider configuration for the module, add an entry for libvirt in the required_providers block within the module.
╵
```

Add missing symlink for containerized proxy module

---

salt/repos/default.sls

We noticed that we don't inject anywhere the tools_update_repo for Debian systems.

Add tools_update_repo for Debian systems

---

TROUBLESHOOTING.md

Based on @cbosdo discussion post: https://github.com/uyuni-project/uyuni/discussions/8434

Add troubleshooting entry for 'dmacvicar/libvirt does not support resource type libvirt_combustion error'

---

backend_modules/libvirt/host/combustion

This PR changes "Network Connection" into "Network connection 1" and "Network connection 2".
It also installs bind-utils, needed for "host" utility by test suite.

Fix Network Manager connection names for Leap micro

---

backend_modules/libvirt/host/user_data.yaml
salt/proxy_containerized/init.sls

Do not install  mgrctl  on containerized proxy.
This PR makes most sense in conjunction with #1580 from Michael (meaning: without that other PR, you don't even reach this problem).

No mgrctl on proxy

---

README.md
backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml
backend_modules/azure/base/main.tf
backend_modules/azure/host/user_data.yaml
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
modules/controller/main.tf
modules/controller/variables.tf
modules/server_containerized/variables.tf
salt/controller/bashrc
salt/mirror/etc/minima.yaml
salt/repos/build_host.sls
salt/repos/default.sls
salt/repos/virthost.sls

Related cards:
- https://github.com/SUSE/spacewalk/issues/23468
- https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/891

Add SLES 15 SP6

---

salt/repos/default.sls

Fix tools_update_repo for Debian, we were using a wrong URL.

Fix tools_update_repo for Debian

---

backend_modules/aws/host/user_data.yaml
backend_modules/libvirt/host/user_data.yaml

This PR aims to solve:
```
Command "rm -f /etc/machine-id && rm -f /var/lib/dbus/machine-id && mkdir -p /var/lib/dbus && dbus-uuidgen --ensure && systemd-machine-id-setup && touch /etc/machine-id-already-setup" run[0;0m
(...)
[2024-05-15T12:14:41.850Z] [0m[1mmodule.rocky9-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec):[0m [0m                  [0;32m/bin/bash: line 1: dbus-uuidgen: command not found[0;0m
```

Install dbus-tools package in RH-Like images to have available dbus-uuidgen

---

README_ADVANCED.md
README_TESTING.md

Adds the heads up about `head` needing to use a containerized setup to `README_ADVANCED.md` and `README_TESTING.md` files.
Related to https://github.com/SUSE/spacewalk/issues/24332

QE: Add documentation for head with containerized setup

---

backend_modules/feilong/host/main.tf

```
backend_modules/libvirt/host/main.tf:        reset_ids                     = true
backend_modules/aws/host/main.tf:        reset_ids                     = true
backend_modules/ssh/host/main.tf:        reset_ids                     = true
backend_modules/azure/host/main.tf:        reset_ids                     = true
```
reset machine id in case of Feilong too

s390: reset machine id

---

salt/salt_testenv/init.sls

As title mentions, this PR make sure `python3-salt`, which is preinstalled on the VM by cloud-unit/combustion, get upgraded to latest version available after setting up the corresponding repositories (depending on salt flavor) during sumaform deployment.
Without this change, there are changes that the `python3-salt-testsuite` package gets installed but not aligned with the actual codebase provided by `python3-salt`, as this package was not updated after configuring the final repos.

Salt Shaker: Make sure "python3-salt" is upgraded after final repos are set

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/user_data.yaml
backend_modules/null/base/variables.tf
modules/salt_testenv/main.tf
modules/salt_testenv/variables.tf
salt/default/hostname.sls
salt/salt_testenv/init.sls

The goal is to be able to run Salt Shaker tests in openSUSE Tumbleweed (for the classic Salt package).

Enable salt_testenv module to use openSUSE Tumbleweed

---

salt/salt_testenv/init.sls

Also fixes missing bits for testing the Salt package built in in `systemsmanagement:saltstack`.

Fix the salt_testenv module to properly run Salt Shaker tests in Leap

---

modules/cucumber_testsuite/main.tf

We were forgetting to pass `container_tag` in the case of containerized proxy.

Pass all container variables to conteinerized proxy

---

backend_modules/libvirt/host/combustion
salt/repos/testsuite.sls

This PR aims to fix this issue when deploying a SL Micro 6.0 in BV:
```
----------
ID: test_repo_rpm_pool
Function: pkgrepo.managed
Result: False
Comment: Failed to configure repo 'test_repo_rpm_pool': Repository 'test_repo_rpm_pool' already exists as 'test_packages_pool'.
Started: 14:58:55.901492
Duration: 3.084 ms
Changes:   
```
I don't really like the solution, that's more a quick fix to have this deploying.
I think we need a [card](https://github.com/SUSE/spacewalk/issues/24483), and refactor the combustion/cloud-init stages, so we don't install test-packages there but in salt states phase.

Don't add the repo when we already added it on Combustion

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/default.sls
salt/salt_testenv/init.sls
salt/salt_testenv/postinstallation.sls
salt/salt_testenv/salt_bundle_package.sls
salt/salt_testenv/salt_classic_package.sls

This PR does a refactor on the Salt state to deploy the Salt Shaker in order to make it cleaner and also fix several detected issues:
- The Salt state to configure Salt Bundle and Salt classic package are now splited in two different files.
- The main `salt/salt_testenv/init.sls`  contains now the mapping between "OS -> Salt packages to install"
- Ensure the right Salt classic package is installed by forcing upgrade/downgrade from a specific repository to use.
- Disable rebootmgr to not reboot SLMicro 60 at night.
- Fix issues rendering the Salt Shaker state for some OSes.
Additionaly, this PR fixes some issues around Debian 10 backport repository, where repository has been archived but the image still contains references to the old repo, causing errors, and also fixes a wrong path to …

Fix issue with Debian 10 and Debian Uyuni Client Tools and refactor Salt Shaker state

---

backend_modules/aws/base/ami.tf

Update opensuse 15.5 name regex with the new opensuse name.

Update opensuse155 name for aws

---

backend_modules/aws/host/user_data.yaml

Currently, rocky8 cloud init is failing to install venv-salt-minion. On minion side, the temporary repository is not visible. 
Adding repository using `yum_repo` ( not visible using yum repolist ) and installing venv-salt using `packages` ( even with the repository correctly declared ) seem to not be correctly executed during the cloud init on Rocky8.
I moved the steps using runcmd to install venv-salt and I can correctly see the repository and the venv-salt-minion package install.
I also removed `dbus-tools` package because this package is not available in the temporary repository.

Fix cloud init issue with rocky8

---

backend_modules/aws/host/user_data.yaml
backend_modules/azure/host/user_data.yaml
backend_modules/libvirt/host/user_data.yaml
salt/proxy/init.sls
salt/repos/build_host.sls
salt/repos/default.sls
salt/repos/proxy42.sls
salt/repos/proxy43.sls
salt/repos/proxyUyuni.sls
salt/repos/server42.sls
salt/repos/server43.sls
salt/repos/serverHead.sls
salt/repos/serverUyuni.sls
salt/repos/virthost.sls
salt/scc/build_host.sls
salt/scc/client.sls
salt/scc/minion.sls
salt/scc/proxy.sls
salt/scc/server.sls

Make arch depend on grains instead of hard coded. Makes sumaform work with MacOS. Basically I did `sed -i 's/x86_64/{{ grains.get("cpuarch") }}/g'` for each file here.
NOTE: This has not been tested except for server Uyuni which works. The rest I have to test, at least one of each kind of node, server, proxy, minion, client. It's a big, potentially destructive change. If we want we can only change the uyuni server and proxy and leave the rest intact as well, which would limit the scope and the potential for breakage as well.

Make arch depend on grains instead of hard coded

---

salt/default/minimal.sls

Temporary disable opensuse leap 15.5 zypper update because the last last version is broken.

Don't update zypper and libzypp for opensuse leap15.5

---

salt/mirror/etc/minimum_repositories_testsuite.yaml

RES8 product tool is missing for rocky8 deployment on aws

Add RES8 product tool to minimal mirror list for rocky8 deployment on aws

---

backend_modules/libvirt/host/user_data.yaml

This PR fixes the deployments for CentOS 7 instances that was broken since July 1st, as `mirrorlist.centos.org` is not existing anymore, therefore neither Salt or Salt Bundle can be installed by cloudinit and sumaform deployment fails with:
```
Error: Cannot find venv-salt-call or salt-call on the system
```
Example: https://ci.suse.de/user/manager/my-views/view/Salt%20Shaker/job/manager-salt-shaker-products-testing-centos7-bundle/
To fix this, we just switch to not use mirror list and use vault.centos.org repository.

Fix deployment for CentOS7 instances as "mirrorlist.centos.org" doesn't exist anymore

---

modules/server/main.tf
modules/server_containerized/main.tf
salt/repos/additional.sls

Following the [SUMA interlock](https://confluence.suse.com/display/SUSEMANAGER/Engineering+Interlock+5.0+-+Sign+off?preview=%2F1359085797%2F1386250774%2FSUSE+Manager+5.0+Engnieering+Interlock+v5.0.pdf), the server containerized is deployed on top of SLE Micro 5.5. Therefore, given the grains, additional repositories are not added to the server in the later stages. This PR adds them to ensure their inclusion in the Jenkins 5.0 BV pipelines.
Server and server_containerized modules were treated with `fmt` afterwards.

terracumber does not install MU repositories on containerized server

---

README_ADVANCED.md
modules/proxy/main.tf
modules/server/main.tf

Prevents deploying `server` and `proxy` modules with versions `head` and `5.0-X`. Updates the advanced readme to reflect this constraint.
Unfortunately with `terraform-1.0.10` it's not possible to print out a specific clear message for this case. Below is an example output when attempting to deploy `server` on `head` (same error when using a non-existent `product_version`):
```
Error: Invalid index
on modules/server/main.tf line 40, in module "server":
40:   image = var.image == "default" ? var.images[var.product_version] : var.image
├────────────────
│ var.images is object with 14 attributes
│ var.product_version is "head"
The given key does not identify an element in this collection value.
```
There are some features that help with this in `1.5.x` and later. We can revisit this when we …

Disable non-containerized deployments for head

---

salt/controller/init.sls

Controller upgraded chromedriver and chromium to version `126.0.6478.126`. This version is creating timeout error during the testsuite execution. This timeout is related to `client.read_timeout = 240` and probably cause by the session being lost.
*Error*
`Net::ReadTimeout (Net::ReadTimeout)`
To prevent this issue, this PR is downgrading chromedriver and chromium to version `125.0.6422.141-bp155.2.91.1` that was the previous version.
Related card: https://github.com/SUSE/spacewalk/issues/24883

QE: Downgrade chronium and chromedriver version

---

salt/controller/init.sls

Adds a comment to remember that the chromedriver version set is a workaround to unblock the issue described here https://github.com/SUSE/spacewalk/issues/24883

Adding a comment for a workaround related to chromedriver

---

backend_modules/libvirt/host/combustion

The current way of configuring combustion is incorrect with the last changes and prevent sumaform to deploy.
`failed to render : <template_file>:90,20-22: Extra characters in if marker; Expected a closing brace to end the sequence, but found extra characters`
and 
`failed to render : <template_file>:90,9-10: Invalid character; Single quotes are not valid. Use double quotes (") to enclose strings., and 2 other diagnostic(s)`
Fix the issue by refactoring this block
Related to : https://github.com/uyuni-project/sumaform/pull/1629

Refactor `Do not check for gpg keys` in combustion

---

salt/minion/init.sls
salt/proxy/init.sls
salt/server/init.sls

This removes the kernel package `kernel-default-base` and use `kernel-default` instead on our SLES 15 SP4 VMs. The former one is used due to the nature of the minimal VM image, we use.
For more information, take a look at the issue: https://github.com/SUSE/spacewalk/issues/24903
Running the change on e.g. the 4.3 proxy:
```bash
suma-bv-43-pxy:~ # venv-salt-call --local --file-root=. state.sls dom
/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/pycrypto.py:26: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
import crypt
/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/linux_shadow.py:21: DeprecationWarning: 'spwd' is deprecated and slated for removal in Python 3.13
import spwd
local:
----------
ID: …
```

Use correct kernel package for SLE15 SP4

---

salt/server_containerized/mgradm.yaml

Use the container registry flag instead of hard-code the image name/path.

correct image registry usage for server config

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/clienttools.sls
salt/repos/default_settings.sls
salt/repos/init.sls
salt/repos/os.sls
salt/repos/testsuite.sls

default.sls is too big and confusing.
This PR split it into 3 parts:
- os.sls to setup OS Vendor repositories only
- clienttools.sls to setup the Client Tools repositories for the various OSes
- default_settings.sls which contains special settings needed for the various OSes

split default.sls in default_settings, os and clienttools

---

backend_modules/aws/base/iam_instance_profile.tf

Make sure iam role is not created when running a non paygo instance.

Remove iam role creation when deploying a none paygo instance

---

salt/repos/init.sls
salt/repos/os.sls

Do not include `os_ltss_repo` for server and proxy.
```bash
suma-43-pxy:~/salt/repos # venv-salt-call --local --file-root=. state.sls os
local:
----------
ID: os_pool_repo
Function: pkgrepo.managed
Result: True
Comment: Configured package repo 'os_pool_repo'
Started: 17:02:53.049577
Duration: 186.698 ms
Changes:
----------
repo:
os_pool_repo
----------
ID: os_update_repo
Function: pkgrepo.managed
Result: True
Comment: Configured package repo 'os_update_repo'
Started: 17:02:53.236404
Duration: 97.605 ms
Changes:
----------
repo:
os_update_repo
----------
ID: os_nop
Function: test.nop
Result: True
Comment: Success!
Started: 17:02:53.334560
Duration: 0.494 ms
Changes:
Summary for local
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time: …
```

Fix: Do include repos.os for server and proxy

---

salt/server_containerized/large_deployment.sls

Fix conditional for transactional systems and aligns the conditions for `pkg: uyuni-tools` with the other occurrences.
```bash
null_resource.provisioning[0] (remote-exec): ----------
null_resource.provisioning[0] (remote-exec):           ID: large_deployment_increase_tasko_parallel_threads
null_resource.provisioning[0] (remote-exec):     Function: cmd.run
null_resource.provisioning[0] (remote-exec):         Name: mgrctl exec 'echo "taskomatic.com.redhat.rhn.taskomatic.task.MinionActionExecutor.parallel_threads = 3" >> /etc/rhn/rhn.conf'
null_resource.provisioning[0] (remote-exec):       Result: False
null_resource.provisioning[0] (remote-exec):      Comment: The following requisites were not found:
null_resource.provisioning[0] (remote-exec):                                  require: …
```

Fix conditional for transactional systems

---

salt/controller/init.sls

With this, we are able to use `ssh -X`/`ssh -Y` on the controller to open Chromium remotely with X11.
Please see also the required test suite changes: https://github.com/uyuni-project/uyuni/pull/9170

Add `xauth` for debugging with a remote Chromium

---

salt/minion/testsuite.sls

Due to killing the Leap 15.5 reposync in the CI, we need those dependencies already fulfilled.
Fixes https://github.com/SUSE/spacewalk/issues/24979
```bash
uyuni-master-podman-min-suse:~/salt # venv-salt-call --local --file-root=. state.sls dom
/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/pycrypto.py:26: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
import crypt
/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/linux_shadow.py:21: DeprecationWarning: 'spwd' is deprecated and slated for removal in Python 3.13
import spwd
local:
----------
ID: suse_minion_mgr_push_requisites
Function: pkg.installed
Result: True
Comment: 9 targeted packages were installed/updated.
Started: 14:19:37.615343
Duration: 35566.602 ms …
```

Leap: Add dependecies for `mgr-push`

---

backend_modules/libvirt/host/combustion

Use different tools for Uyuni and SUSE Manager for SL Micro 6.0.

SL Micro 6.0 tools for SUSE Manager

---

salt/salt_testenv/salt_classic_package.sls

In the context of the `salt_testenv` module, for some OSes, zypper resolves the `docker` symbol to the `podman-docker` package instead of the `docker` package, which causes the docker service not being available. This happens during the application of the `install_salt_testuiste` state (`podman-docker` is resolved as a dependency of `python3-salt-testsuite` for some OSes).
This PR forces the installation of docker beforehand.

Force installation of docker instead of podman-docker in salt_testenv

---

salt/server_containerized/testsuite.sls

Since we cannot confirm anything during the sumaform setup, we need to force the import. Otherwise, sumaform does not succeed because it will wait for confirmation forever.

Force GPG import in containerized server

---

backend_modules/libvirt/host/user_data.yaml
salt/repos/os.sls

`rmt.scc.suse.de` had issues in the past which caused issues in our BV deployments. With this, we remove this dependency.
Fixes https://github.com/SUSE/spacewalk/issues/24567
Bootstrapping the Liberty 9 Minion that was created via sumaform worked without RMT.

Remove RMT registration for Liberty 9

---

salt/repos/proxy_containerized50.sls
salt/repos/proxy_containerizedHead.sls
salt/repos/server_containerized50.sls
salt/repos/server_containerizedHead.sls

This PR avoids this issue:
```
Failed to configure repo 'manager50_repo': Repository 'manager50_repo' already exists
as 'container_tools_repo'.
```
(we did not see this issue in Head because of subtle differences with `/ibs` in the URL or not).

Do not declare container repositories twice

---

salt/server_containerized/testsuite.sls

As the title implies: adding a new dummy modular repository which will be used for testing AppStream features.

Add repository for AppStream tests

---

modules/dhcp_dns/main.tf

dhcp dns host setup is not happening, so we add a trigger to make it run always.

Always force dhcp dns host setup

---

backend_modules/libvirt/host/combustion
salt/repos/proxy_containerizedUyuni.sls
salt/repos/server_containerizedUyuni.sls

The same as https://github.com/uyuni-project/sumaform/pull/1673, but for Uyuni.
Basically, we already have the repos added with Combustion, so we do not want to add them again with Salt. Furthermore, this differentiates between Uyuni Master and Uyuni Stable in Combustion.

Uyuni: Do not declare container repos twice

---

salt/default/minimal.sls

Do not remain blocked on:
```
Resolving package dependencies...
The following package is going to be upgraded:
venv-salt-minion
1 package to upgrade.
Overall download size: 31.1 MiB. Already cached: 0 B. After the operation, additional 48.9 KiB will be used.
Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y):
```

Non-interactive mode for transactional-update

---

backend_modules/libvirt/host/combustion

DHCP and DNS VM has a dependency to proxy and PXE boot VMs, but the latter do not get an IP address until the former is running.
Let DHCP fail after 0 second.

Break chicken and egg issue

---

salt/repos/proxy_containerizedUyuni.sls
salt/repos/server_containerizedUyuni.sls

Leap Micro does not exist in Public Cloud. To run our Uyuni testsuite in the cloud, we need to support standard Leap.

support standard openSUSE Leap 15.5 as server and proxy os

---

salt/server/testsuite.sls

Ideally, we should get rid of the list of products that use the Salt bundle, since now all our products do that by default.
However, Dominik still needs that flag to work on another card.
For now, just add 5.0 to that list.

Add 5.0 to list of products that use the bundle

---

salt/server/testsuite.sls

Adds a Salt state, for the standard server, setting up a local dummy AppStream repository to be used by the testsuite.

Add dummy AppStream repository

---

.github/workflows/ci-validation/salt-client-validation
.github/workflows/ci-validation/salt-controller-validation
.github/workflows/ci-validation/salt-minion-validation
.github/workflows/ci-validation/salt-mirror-validation
modules/controller/main.tf
modules/controller/variables.tf
modules/cucumber_testsuite/main.tf
salt/controller/bashrc
salt/controller/init.sls
salt/repos/init.sls
salt/repos/ruby.sls

Prerequisite for https://github.com/uyuni-project/uyuni/pull/6559 / https://github.com/uyuni-project/uyuni/pull/9181. See also the issue https://github.com/SUSE/spacewalk/issues/17431. I only merge this PR, once everything in Uyuni is ready.
This will
- change the used Ruby version to 3.3 by adding and installing if via the Ruby devel repos (no Ruby > 2.5.9 in Leap 15.5/15.6 :cry: )
- ~build Twopence from source since there is no way we can build it in OBS with Ruby 3 on openSUSE Leap 15.5/15.6~
- adding the `product_version` variable to the controller grain, that we will use, to still be able to use Ruby 2.5 on 4.3
- fix the CI tests by including the checked `product_version` as a variable
Later on, I will also update Ruby in spacewalk for 4.3, but first we need it in master and giving …

Controller: update Ruby to 3.3 for HEAD/Uyuni/Uyuni Podman/5.x

---

salt/repos/init.sls

This PR fixes a regression introduced by https://github.com/uyuni-project/sumaform/pull/1248/ which breaks the deployment of some node types, like the generic `host` or `salt_testenv`, as those don't have a `product_version` defined.

Do not crash when "product_version" is not defined for "host" and "salt_testenv" nodes

---

backend_modules/libvirt/host/user_data.yaml

Don't upgrade packages in the systems deployed in a SUMA/Uyuni test environment.
- Related card: https://github.com/SUSE/spacewalk/issues/25189
The cloud team added the module `package-update-upgrade-install` to SUSE cloud-init configuration. This triggers an not-desired update of packages in some of the systems part of our test environment.
This is triggered due to the usage of the keyword `packages` in our [YAML file](https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/host/user_data.yaml#L91).
---
This PR replace the keyword `packages` by `runcmd zypper in`
Example:
```
packages: ["venv-salt-minion", "avahi", "nss-mdns", "qemu-guest-agent"]
```
```
runcmd:
- zypper in venv-salt-minion avahi nss-mdns qemu-guest-agent
```

Refactor the usage of packages keyword in cloud-init, to avoid auto upgrade of packages

---

salt/controller/init.sls

The ruby version had already been bump in spacewalk 5.0 and so the workaround is not needed anymore.

Remove spacewalk 5.0 product from bundle 3.3 exclusion

---

salt/first_deployment_highstate.sh
salt/highstate.sh

Write down the salt deployment output in var log file to more easily debug when salt states are failing without the need of rerunning it.

Add a file for salt output

---

backend_modules/libvirt/host/user_data.yaml

dnf command not available on centos7 : 
```bash
[root@suma-bv-50-centos7-minion log]# dnf -y install venv-salt-minion avahi nss-mdns qemu-guest-agent
-bash: dnf: command not found
```

dnf command not available on centos7

---

salt/repos/clienttools.sls

For Build Validation, we are deploying opensuse 15X with aarch64 architecture.
Sumaform is by default injecting x86_64 repository to all opensuse minion. 
Change the toolrepo repositories for opensuse to use the correct repository depending on cpuarch. 
This will add the correct repositories to opensuse15Xarm.

Use cpuarch for opensuse tool repositories.

---

salt/minion/init.sls

Don't start venv-salt-minion or salt-minion service when auto_connect_to_master is set to false.
The file master_configuration is only set when auto connect to master is true so it doesn't make sense to start salt minion service when file is not set.

Enable salt service ONLY if auto_connect to master is true.

---

backend_modules/libvirt/host/user_data.yaml

Related to this issue : https://github.com/SUSE/spacewalk/issues/25325
Starting the (venv-)salt-minion service is not supported when selinux is in enforcing mode.
I open a PR to not start the minion service when not needed but this PR is still needed for the case where we want to auto connect centos7 to master.

setenforce 0 for centos7 to support auto connect to master.

---

salt/repos/clienttools.sls

Use devel tools for 24.04 as long as the final tools are not published on SCC

Workaround for unpublished Ubuntu 24.04 tools

---

backend_modules/feilong/base/main.tf

Feilong base is directly call without using base/main.tf.
Update feilong base to support new product_version variable

Update feilong base to support new product_version variable

---

modules/sshminion/variables.tf

In our BV testing, for the sshminion, we don't set `auto_connect_to_master` variable to false so all the sshminion are set to auto connect to master.
**BUT** when we do our test, the sshminion are not visible. Indeed the `server_configuration['hostname']` is not **settable** ( no declare in variables.tf ) for sshminion so the minion run without proper configuration and with that we delete venv-salt-minion before bootstrapping. 
**Because** server_configuration is not an available variable for sshminion, we **can't** configure the auto connect to master.
Set the default variable `auto_connect_to_master` to false for now. We may need to either add `server_configuration` to sshminion or remove `auto_connect_to_master`.

Set auto_connect_to_master to False for sshminion

---

backend_modules/null/base/variables.tf

This avoid getting an error when `product_version` is not set:
failed to render : <template_file>:100,9-24: Unknown variable; There is no variable named "product_version".
on backend_modules/libvirt/host/main.tf line 79, in data "template_file" "combustion":

Use empty string for "product_version" default value on base

---

salt/server_containerized/testsuite.sls

Not only run this cp command when the `download_ubuntu_repo.sh` file change, as sometimes we might have a new container image even if that file did not changed, and so, we will not copy the file inside the container and the next salt state will fail.

Always run test_repo_debian_updates_script_copy salt state

---

salt/repos/clienttools.sls

On Salt minions, client tools should come from shared tools in 5.0 for Ubuntu in 4.3 branch.
This PR solves only our immediate problem, but does not address 20.04 nor 22.04, nor Debian, nor recent RH and clones, etc - for those ones i have created an issue SUSE/spacewalk#25428 .

Salt packages should come from shared tools in 5.0 for Ubuntu

---

modules/minion/main.tf
modules/minion/variables.tf

Make the `server_configuration` variable optional for minions, as it is only required when `auto_connect_to_master` is set to `true`. Removing this mandatory variable will eliminate hundreds of unnecessary lines in BV and CI pipelines, making the configuration cleaner and more efficient. Additionally, it will clarify that this value is not used when auto-connect is disabled.

Make server configuration variable optional for minion.

---

salt/repos/client_tools.sls
salt/repos/init.sls

* Cosmetical changes
* Use 5.0 shared tools even on 4.3 branch (Debian and Ubuntu only, for now)
* 5.0 branch should not point to 4.3
Issue:  https://github.com/SUSE/spacewalk/issues/25428
SLE 15, SLE 12, and RHEL 7 + clones need 2 repos instead of one. This will be addressed in another PR.

Clarify between 43 and 50

---

salt/repos/client_tools.sls

Missing images/ target for SLE 12 devel client tools is being added by Marina, removing the workaround.

Missing images/ target is being added by Marina

---

salt/client/testsuite.sls
salt/minion/testsuite.sls

We had issues on Liberty 9, as we couldn't find `wget` installed or available in the pristine image.
In fact, we don't need it, we only need that package in Debian-like systems for our testsuite minions/clients.
See also that:
https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/step_definitions/navigation_steps.rb#L1107-L1112
```
if (os_family.include? 'debian') || (os_family.include? 'ubuntu')
node.run_until_ok("wget --no-check-certificate -qO- #{protocol}://#{system_name}:#{port}#{path} | grep -i '#{text}'")
else
node.run_until_ok("curl -s -k #{protocol}://#{system_name}:#{port}#{path} | grep -i '#{text}'")
end
```

Only Debian-like minions/clients require wget in our testsuite

---

salt/controller/init.sls

New chrome driver and chromium version are available.
I don't reproduce the late issue.
This PR remove the force versions for those two packages.

Remove chromedriver and chromium force version

---

modules/build_host/main.tf
modules/host/main.tf
modules/server/main.tf
modules/sshminion/main.tf

I've noticed there was a problem where the `product_version` was not set properly on the deployed nodes when not having a `product_version` definition in the "base" module but instead inside each different nodes.
Like in this example:
```
module "base" {
[... no product_version defined here ...]
}
module "suma-43-srv" {
source = "./modules/server"
base_configuration = module.base.configuration
name = "suma-43-srv"
product_version = "4.3-nightly"
}
module "suma-43-min-build" {
source = "./modules/build_host"
base_configuration = module.base.configuration
name = "suma-43-min-build"
product_version = "4.3-released"
server_configuration = module.suma-43-srv.configuration
image = "sles15sp4o"
}
module "suma-43-min-host" {
source = "./modules/host"
base_configuration = module.base.configuration …
```

Fix problem propagating the "product_version" attribute

---

backend_modules/libvirt/host/user_data.yaml

Remove ssl libertylinux 9 workaround.

Remove ssl libertylinux 9 workaround.

---

salt/repos/init.sls
salt/server/init.sls

This is just an attempt to fix the issue explained here:
https://github.com/SUSE/spacewalk/issues/25575#issuecomment-2426285245
---
```
suma-bv-50-server:~ # snapper list
---+--------+-------+----------------------------------+------+------------+---------+-----------------------+--------------
0  | single |       |                                  | root |            |         | current               |
1  | single |       | Sat 28 Sep 2024 05:41:43 AM CEST | root | 768.00 KiB | number  | first root filesystem | important=yes
2  | single |       | Wed 16 Oct 2024 03:29:26 AM CEST | root | 496.00 KiB | number  | Snapshot Update of #1 |
3  | single |       | Wed 16 Oct 2024 03:29:31 AM CEST | root | 436.00 KiB | number  | Snapshot Update of #2 |
4  | single |       | Wed 16 Oct 2024 …
```

Don't trigger repos salt states for a server on a transactional system

---

salt/default/network.sls

This PR fixes an issue with the check of `eth1` . Currently the code uses a `cmd.run_stdout` call which fails if the command returns an error code which translates in a failure of the salt script.  This PR ignores the error code and allows to apply the state correctly when the interface is not present.

Ignore return code when checking if eth1 exists

---

salt/minion/testsuite.sls

Due to killing the Leap 15.5 reposync in the CI, we need those
dependencies already fulfilled.
See SUSE/spacewalk#24979

Leap: add dependency for mgr-push

---

modules/cucumber_testsuite/main.tf
modules/proxy/variables.tf

With the current cucumber_testsuite module, we can't describe additional disks for the server_containerized.
- Add repository_disk_size and database_disk_size options to server_containerized
- Remove database_disk_size option to proxy and proxy_containerized (not supported in salt / proxy module)

Support additionnal disk server containerized cucumber testsuite

---

salt/default/avahi.sls

This patch is extending an existing workaround (for bsc#1163683) to SLE 15 SP6. Found this as I was running into issues creating SP6 clients while using avahi.

Extend an existing workaround to SLE 15 SP6

---

backend_modules/aws/base/ami.tf

The Rocky images got a new name in AWS. Change the regex

Rock Linux 8 ami was renamed

---

backend_modules/aws/host/main.tf

use gp3 as default type for root block device.
gp3 may also be cheaper in some conditions

use gp3 as default type for root block device

---

backend_modules/libvirt/host/user_data.yaml

We had this hidden issue deploying SLES15 SP4, SP5, SP6.
We actually don't need this command to have the VM working properly, so I'm removing it from sumaform.

We don't need to start any special qemu service on sles15 sp4,5,6

---

salt/server_containerized/mgradm.yaml

Currently, the container have a different timezone than server host or controller.
This differences are created some issues (getting the last log not working with the testsuite, using spacewalk is scheduling the event one hour later, etc)
Force the timezone to Berlin timezone.
Related to: https://github.com/SUSE/spacewalk/issues/25607

Add Berlin timezone for container deployment.

---

salt/server_containerized/install_k3s.sls
salt/server_containerized/mgradm.yaml
salt/server_containerized/mirror-pv.yaml

In kubernetes installations we now require the mirror PV to be created before running mgradm and pass the pv name to --volumes-mirror

Adjust mirror handling for k3s

---

salt/server_containerized/install_k3s.sls

The simplified mirror_hostname value doesn't work because the `server_mounted_mirror` is `{}`.

Fix mirror grain extraction in k3s setup

---

salt/server_containerized/install_mgradm.sls
salt/server_containerized/install_podman.sls

K3S hosts don't have podman so `podman login` will fail there.

Only call podman login on podman hosts

---

.github/CODEOWNERS

Adding a .github/CODEOWNERS, everyone member of @uyuni-project/sumaform-developers will receive a notification to review every new Pull Request, for any change in sumaform code.
The exception are GitHub workflows, in such case, the reviewers will be the team @uyuni-project/workflows-reviewers

Add a .github/CODEOWNERS

---

salt/controller/bashrc
salt/controller/init.sls
salt/repos/init.sls

Remove divergence about Ruby version, so 4.3 also use Ruby 3.x

Remove divergence about Ruby version

---

backend_modules/libvirt/base/main.tf
backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/user_data.yaml
modules/proxy_containerized/main.tf
modules/server_containerized/main.tf
salt/repos/additional.sls
salt/repos/proxy_containerizedHead.sls
salt/repos/server_containerizedHead.sls
salt/server_containerized/initial_content.sls
salt/server_containerized/install_k3s.sls
salt/server_containerized/install_mgradm.sls
salt/server_containerized/install_podman.sls
salt/server_containerized/large_deployment.sls
salt/server_containerized/testsuite.sls

For SUSE Multi-Linux Manager 5.1 we need support for SL-Micro 6.1 as host image.
This add support for it to sumaform

add slmicro61o to sumaform

---

salt/salt_testenv/salt_classic_package.sls

The JeOS image we use in sumaform for deploying `SLE-15-SP3` instances contains a very old version of `python3-pyzmq`.  
This version is making the Salt Shaker integration tests for classic Salt package to hang when running on SLE15SP3 instances (see https://ci.suse.de/user/manager/my-views/view/Salt%20Shaker/job/manager-salt-shaker-products-testing-sles15sp3/214/).
There are newer versions of `python3-pyzmq` in the Update and LTSS channels for SLE15SP3 that fixes this issue, so this PR just adds a workaround on Salt Shaker deployments for SLE15SP3 to force the upgrade of `python3-pyzmq` and allow the integration tests to run.

Salt Shaker: Upgrade python3-pyzmq to latest version on SLE15SP3 LTSS

---

backend_modules/feilong/host/main.tf

Use only 10 GiB for disks on a z/VM hypervisor.

Use smaller disks for z/VM

---

backend_modules/aws/host/main.tf

We probably skipped this check during the last refactors and changes.
Not having an instance profile attached to the EC2 instance does not make the deployment fail or the server unable to start, but results in not being able to send metering data to the AWS markeplace.
This ultimately leads to the instance being identified as not PAYG compliant and all functionalities being blocked.

Attach IAM instance profile to containerized server EC2

---

salt/repos/ruby.sls

```
Error building the cache:
11:47:40  module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): [ruby_devel_extensions|http://download.opensuse.org/repositories/devel:/languages:/ruby:/extensions/15.5/] Valid metadata not found at specified URL
[ruby_devel_extensions|http://download.opensuse.org/repositories/devel:/languages:/ruby:/extensions/15.5/] Repository type can't be determined.
```
15.5 repository is not available anymore, changing to: https://download.opensuse.org/repositories/devel:/languages:/ruby:/extensions/15.6/
- 5.0.3 BV: https://github.com/SUSE/spacewalk/issues/24901

Changing ruby_devel_extensions to 15.6 repo

---

backend_modules/libvirt/host/user_data.yaml
salt/server/download_ubuntu_repo.sh
salt/server/testsuite.sls
salt/server_containerized/testsuite.sls

Removes the packages installed in the container image and moves them to the host. This PR has to be merged with https://github.com/uyuni-project/uyuni/pull/9577

Remove packages installed in the server container for testsuite

---

README.md
TROUBLESHOOTING.md
backend_modules/libvirt/base/main.tf
backend_modules/libvirt/base/versions.tf
backend_modules/libvirt/host/main.tf
backend_modules/libvirt/host/versions.tf
main.tf.libvirt-testsuite.example
main.tf.libvirt-testsuite.example.Manager-43
main.tf.libvirt.example
main.tf.libvirt.example.Manager-43
modules/dhcp_dns/README.md

Update the terraform-provider-libvirt to the latest available version: 0.8.1

Libvirt provider v0.8.1

---

main.tf.libvirt.example

Updates the base example using a libvirt backend.
When using Uyuni, the default OS for a containerized server is Leap micro 5.5 and that should be available as VM image.

Update images list in example main.tf for libvirt

---

backend_modules/libvirt/host/user_data.yaml

Add SLES 15 SP6 as base OS for SUSE Manager 5.0
See https://github.com/SUSE/spacewalk/pull/26622

Add SLES 15 SP6 as base OS for SUSE Manager 5.0

---

backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/user_data.yaml

The products were renamed from "SUSE-Multi-Linux-Manager-*" into "Multi-Linux-Manager-*".
This effect also the repository URLs

fix Multi-Linux-Manager repository URLs after product rename

---

backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/user_data.yaml

For released versions, we also need the updates to the container utils
Also align name of container utils / container tools repo

For released versions, we also need the updates to the container utils

---

README_ADVANCED.md
modules/cucumber_testsuite/main.tf
modules/cucumber_testsuite/variables.tf
salt/server_containerized/init.sls
salt/server_containerized/rhn.sls

Card: https://github.com/SUSE/spacewalk/issues/26373
Fix `beta_enabled` variable on cucumber_testsuite module.
With those changes, the aim is to provide `beta_enabled` variable at cucumber_testsuite module, so you don't need to define it twice in `controller` and `server_containerized` submodules.
Additionally, we fixed the rhn.sls that was previously NOT triggered, refactoring it so it use mgrctl to run some `sed` commands to modify RHN configuration file.
Note for MLM team:
This PR must be follow up by a PR to adapt our internal terraform files in susemanager-ci repository.
Add this variable at cucumber_testsuite level.

Fix beta_enabled variable on cucumber_testsuite module + Refactor rhn.sls on server_containerized

---

backend_modules/aws/base/ami.tf

Update the RegEx we use to search for RHEL 8 and 9 images in the AWS marketplace to the latest version numbers.

Bump RHEL AWS images version number

---

salt/default/network.sls
salt/server_containerized/init.sls
salt/server_containerized/initial_content.sls
salt/server_containerized/install_common.sls
salt/server_containerized/install_mgradm.sls
salt/server_containerized/large_deployment.sls
salt/server_containerized/rhn.sls
salt/server_containerized/testsuite.sls

Some of our salt states in Sumaform requires to have previously installed `mgrctl` or `mgradm`.
But if we are under a transactional-system, we install these packages during the cloud-init/combustion phase.
And if we are under a non transactional-system, we have a salt state called `uyuni-tools` taking care of that installation.
Before this PR, we had an `if` statement and we only required `uyuni-tools` if we were under a non-transactional system, and just don't check it if we are under a transactional-system.
This approach could potentially miss issues, so the PR aims to improve it, by directly check if `mgrctl` and `mgradm` are present when we are on a transactional-system.

Refactor how we require mgrctl and mgradm packages

---

salt/server_containerized/mgradm.yaml

* postgresql container uses `reportdb` hostname which is also default so do not set it in the mgradm.yaml

Changes needed for separate database container

---

modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server_containerized/mgradm.yaml

Add the possibility to define an image name if we don't want to use the default image from mgradm. Can be usefull in situation we have an image available for the server but the path is not supported yet.

Add support container image for server

---

.github/workflows/ci-validation.yml
.github/workflows/mirror-update-warning.yml

One of the recommendations of the [Good security practices for using GitHub Actions features](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions?learn=getting_started).
For each action I went to the repository and used the last released version for the major version we were using, and specified the exact version with a comment.
If we were using `latest`, I pinned to the latest commit for the most recent version released.

Pin all GitHub actions to a commit

---

TROUBLESHOOTING.md
backend_modules/libvirt/host/combustion
salt/minion/testsuite.sls
salt/mirror/etc/minima.yaml
salt/repos/proxy_containerizedUyuni.sls
salt/repos/server_containerizedUyuni.sls

This PR replaces Leap 15.5 with Leap 15.6 on server, proxy, and minion
controller, dhcp-dns, and monitoring are not affected.

Remove Leap 15.5

---

salt/repos/os.sls

The path to LTSS repo in mirror is incorrect.
```
minima-mirror-ci-bv:/srv/mirror/SUSE/Updates/SLE-Product-SLES # pwd
/srv/mirror/SUSE/Updates/SLE-Product-SLES
minima-mirror-ci-bv:/srv/mirror/SUSE/Updates/SLE-Product-SLES # ls -lrt
total 0
drwxr-xr-x 4 root root 47 Aug 15  2023 15-SP4
drwxr-xr-x 3 root root 28 Jan  2  2024 15-SP4-LTSS
drwxr-xr-x 4 root root 45 Jan  8  2024 15-SP5
drwxr-xr-x 4 root root 47 Jan  8  2024 15-SP3
drwxr-xr-x 5 root root 64 Jul 10  2024 15-SP6
drwxr-xr-x 4 root root 47 Aug 22  2024 15-SP3-LTSS
drwxr-xr-x 4 root root 45 Mar 19 11:05 15-SP7
drwxr-xr-x 3 root root 28 Mar 22 22:15 15
drwxr-xr-x 3 root root 28 Mar 22 22:26 15-SP1
drwxr-xr-x 3 root root 28 Mar 23 21:39 15-SP2
drwxr-xr-x 3 root root 28 Mar 23 23:36 15-LTSS
drwxr-xr-x 3 root root 28 Mar 24 00:16 …
```

Fix LTSS path in mirror

---

salt/repos/ruby.sls

http://download.opensuse.org/repositories/devel:/languages:/ruby/15.5/ has been removed. Bump to 15.6.

Fix path ruby devel

---

modules/controller/main.tf
salt/repos/ruby.sls

Leap 15.5 is EOL and the ruby repo was already removed

change controller default image to Leap 15.6

---

backend_modules/aws/host/user_data.yaml

Leftover of the switch from Leap 15.5 to 15.6

Switch from Leap 15.5 to 15.6 on AWS hosts

---

backend_modules/libvirt/host/combustion

This PR disable the automatic daily system updates and its reboot, in all images initialized with Combustion.
- `ln -sf /dev/null` reliably disables the service even without `systemctl`.
- Compatible with early boot stages of MicroOS / Leap Micro.
- No dependency on D-Bus or systemd being fully available.

Disabling automatic daily system updates

---

salt/default/ids.sls

If the folder in `/var/log/journal` doesn't match the `/etc/machine-id` `journalctl` cannot log anything... and `podman logs` uses `journald` as its backend so we would also get no container logs.

The journal folder has to match the machine-id

---

salt/default/ids.sls

Copying the journal log into the new journal log folder is failing for rocky8, leap 15.6, server and deblike minion.
There are two causes:
- folder /var/log/journal doesn't exist
- cannot copy a folder in itself
```
Moving logs to /var/log/journal/5fb2f6d9f0af9f07dab8756f6806eca3
mv: cannot move '/var/log/journal/5fb2f6d9f0af9f07dab8756f6806eca3' to a subdirectory of itself, '/var/log/journal/5fb2f6d9f0af9f07dab8756f6806eca3/5fb2f6d9f0af9f07dab8756f6806eca3'
```
Fix this issue with checking the folder journal

Fix systemd machine id journal not present

---

salt/repos/client_tools.sls

The EL7 beta repo has a different name

MLMTools repo for EL7 has a different name

---

backend_modules/libvirt/host/combustion

Re-organize how we add repositories and how we install packages in Combustion.
So we first install all what we need for the product, and then we install all what we need for the tests.

Organize Combustion by product and test scopes

---

salt/server_containerized/rhn.sls

Increase presence ping timeout on testsuite envs.
This will affect all the presence pings made by MLM server to our minions, we are tweaking this to mitigate some flaky issues. In particular, the issues we found are during the registration of a minion, but for now, we don't have a parameter to tweak only the timeout on such case.

Increase presence ping timeout on testsuite envs

---

backend_modules/libvirt/base/main.tf

This PR fixes a broken URL to the SLE15SP7 image:
```console
╷
│ Error: error while determining image type for http://dist.nue.suse.com/install/SLE-15-SP7-Minimal-RC1-202503/SLES15-SP7-Minimal-VM.x86_64-Cloud-RC1-202503.qcow2: can't retrieve partial header of resource to determine file type: http://dist.nue.suse.com/install/SLE-15-SP7-Minimal-RC1-202503/SLES15-SP7-Minimal-VM.x86_64-Cloud-RC1-202503.qcow2 - 404 Not Found
│ 
│   with module.base.module.base_backend.libvirt_volume.volumes["sles15sp7o"],
│   on backend_modules/libvirt/base/main.tf line 50, in resource "libvirt_volume" "volumes":
│   50: resource "libvirt_volume" "volumes" {
│ 
```

Fix broken URL for SLE15SP7 image

---

salt/salt_testenv/salt_classic_package.sls

Some OSes enable Python 3.11. When we first install `python3-salt`, this defaults to `python311-salt`. In such case, if we try to install `python3-salt` later again, this causes conflicts with the already installed python311-salt.
Related to: https://github.com/SUSE/spacewalk/issues/27141

[salt-shaker] Specify python version for classic salt

---

backend_modules/libvirt/host/user_data.yaml

During bootstrapping, we create the `tools_pool_repo.list` on deb-based systems. However, we also define the client repo later with https://github.com/uyuni-project/sumaform/commit/5c1b1ad7ca615ee4a7919a1dac5560761d8b172e
This causes two repofiles with the same repo definition:
```
root@salt-shaker-products-testing-ubuntu2004-bundle:~# cat /etc/apt/sources.list.d/tools_pool_repo.list /etc/apt/sources.list.d/tools_update_repo.list 
deb http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/ /
deb http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04 /
```
In this PR, I clean up the bootstrap repository after bootstrap's done.

Remove tools_pool_repo.list after bootstrap

---

backend_modules/libvirt/host/combustion

The head pipeline is not reaching secondary because the package suse-build-key is outdated

QE: Updating the package suse-build-key in slemicro60 and slemicro61

---

backend_modules/libvirt/host/combustion
backend_modules/libvirt/host/user_data.yaml

microos-tools vs. aaa_base-extras from "Leap_pool" cause a file conflict.
Let's try to not install aaa_base-extras

remove aaa_base-extras from packages to be installed due to file conflicts

---

backend_modules/aws/README.md
backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
main.tf.aws-testsuite.example

AWS AMIs for Leap 15.5 are no longer available and will cause our pipeline to fail when attempting to compute a value for the most recent of them.
```
15:44:27  │ Error: Your query returned no results. Please change your search criteria and try again.
15:44:27  │ 
15:44:27  │   with cucumber_testsuite.base.aws_ami.opensuse155o,
15:44:27  │   on /home/jenkins/workspace/uyuni-master-dev-acceptance-tests-AWS/results/sumaform/backend_modules/aws/base/ami.tf line 1, in data "aws_ami" "opensuse155o":
15:44:27  │    1: data "aws_ami" "opensuse155o" {
15:44:27  │ 
15:44:27  ╵
```
We already switched to Leap 15.6 on our AWS CI , so it should be safe to just remove the entry.

Remove AWS AMI for Leap 15.5

---

backend_modules/libvirt/base/main.tf

Adds a null resource using local-exec to decompress .xz images before they are used to create libvirt volumes.
The set of `compressed_images` can be retrieved dinamically, but TBH I think it's more readable to have it hardcoded and keep it up to date when more are added.

Decompress xz images before volumes creation

---

salt/salt_testenv/salt_classic_package.sls

This PR prevents an error we see when running Salt Shaker tests for classic Salt package in SLE 15.3 and 15.4 caused by an outdated version of `python3-M2Crypto` package (from 2020):
```
tests/pytests/functional/channel/test_req_channel.py::test_req_channel_v2_invalid_token
[...]
def public_decrypt(self, data, padding):
assert self.check_key(), 'key is not initialised'
>       return m2.rsa_public_decrypt(self.rsa, data, padding)
E       M2Crypto.RSA.RSAError: invalid header
/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py:72: RSAError
```
Upgrading the `python3-M2Crypto` version fixes this issue, so we take here the same approach we did for `python3-pyzmq` in SLE 15.3.

Salt Shaker: Upgrade to latest "python3-M2Crypto" version on 15.3 and 15.4

---

salt/server/initial_content.sls
salt/server_containerized/initial_content.sls

Lately, we've noticed failures in 5.0 BV-like pipelines when waiting  to retrieve the initial product list.
That seems connected to our setup for large deployments - specifically the fact that we restart PostgreSQL to apply changes to its configuration, the values themselves do not matter.
Making so that we always wait for the initial, automated, product refresh to complete before applying such changes seems to solve this issue.

Always wait for SCC data refresh

---

backend_modules/aws/base/ami.tf

With the release of new arm64 images, it seems the previous regex is no longer matching any available image
```
17:18:47  │ Error: Your query returned no results. Please change your search criteria and try again.
17:18:47  │ 
17:18:47  │   with cucumber_testsuite.base.aws_ami.suma-server-50-arm64-ltd-paygo,
17:18:47  │   on /home/jenkins/workspace/uyuni-master-dev-acceptance-tests-AWS/results/sumaform/backend_modules/aws/base/ami.tf line 241, in data "aws_ami" "suma-server-50-arm64-ltd-paygo":
17:18:47  │  241: data "aws_ami" "suma-server-50-arm64-ltd-paygo" {
17:18:47  │ 
17:18:47  ╵
```
This PR replaces that regex filter for both x86 and arm64 with a stricter, working, one.

Update AWS AMI regex filters for SUMA 5.0 Server

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/user_data.yaml

```
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.base.module.base_backend.data.aws_ami.sles15sp3o,
│   on /home/jenkins/workspace/manager-5.0-qe-build-validation-paygo-aws/results/sumaform-aws/backend_modules/aws/base/ami.tf line 22, in data "aws_ami" "sles15sp3o":
│   22: data "aws_ami" "sles15sp3o" {
```
I've manually checked and It seems SLES 15 SP3 BYOS images are no longer available in the AWS marketplace, the similar regex for SLES 15 SP4 BYOS does work
This breaks pipelines as the data section for them returns no result now.
Considering we are not using them anyway in our PAYG pipeline, it would still be useful to remove these sections.

AWS: Remove SLES 15 SP3 BYOS

---

backend_modules/aws/host/user_data.yaml
backend_modules/azure/host/user_data.yaml
backend_modules/libvirt/host/user_data.yaml
salt/repos/disable_local.sls
salt/salt_testenv/init.sls
salt/salt_testenv/lib.sls
salt/salt_testenv/salt_classic_package.sls

This pull request enables `salt_testenv` Tumbleweed deployments by fixing the password-based root login over SSH (used by terraform to run `salt` on the target) and using `venv-salt-minion` during provisioning, which allows the removal of Salt packages without interfering with the provisioning itself.
In a secondary step I did a bit of clean-up. I used a bit of Jinja to remove repetition from our salt_classic_package.sls. This serves as an example, we can do the same for more if we like it.

`salt_testenv`: Enable Tumbleweed deployments and clean up

---

backend_modules/aws/base/ami.tf
backend_modules/aws/base/main.tf
backend_modules/aws/host/combustion
backend_modules/aws/host/main.tf
salt/server_containerized/install_podman.sls

Includes:
- (currently placeholders) AMIs for 5.1 PAYG Server and 5.1 BYOS Proxy images
- combustion template changes:
- remove all the currently unused variables
- rely on product_version instead of image to determine  whether we are using combustion for SLE micro 5.5 or SL  micro 6.1. We cannot rely on the image name because when we test new images we'll provide the AMI itself, since they're not released and cannot be found through "normal" marketplace search.
-  adds a conditional 3 minutes wait if combustion has been used by the instance. This is to address the need to reboot after installing pkgs on transactional systems, which will break other scripts running due to the SSH connection cut (e.g. wait_for_salt.sh).

AWS payg-related updates

---

modules/dhcp_dns/main.tf

Even 8 minutes are not enough on SLC 1 for DHCP and DNS VM. Increasing to 15 minutes.

Even 8 minutes are not enough on SLC 1

---

salt/salt_testenv/salt_classic_package.sls

Since we have an `Obsoletes: python3-salt` set for `python311-salt` in 15SP7, we need to explicitely call for `python311-*` to be installed.

Salt Shaker: Install all available Python flavors for Salt

---

salt/repos/os.sls
salt/salt_testenv/salt_classic_package.sls

This PR rearrange the channels assigned to SLE15SP4+ instances in order to fix the issues installing `python311-salt` due missing dependencies:
- Add LTSS channel for SLE15SP5
- Include `SLE-Module-Python3` in SP4 and SP5

Salt Shaker: Rearrange channels on SLE15 instances to fix issues with "python311-salt"

---

modules/cucumber_testsuite/main.tf
modules/server_containerized/main.tf
modules/server_containerized/variables.tf
salt/server_containerized/init.sls
salt/server_containerized/oval_metadata.sls

Creates a new variable and related Salt state to allow syncing of OVAL data.
The feature is a 5.1 tech preview and disabled by default.
See https://documentation.suse.com/multi-linux-manager/5.1/en/docs/administration/auditing.html#_oval

Add optional OVAL data sync setup variables and Salt state

---

backend_modules/libvirt/host/combustion

Remove the build key installation for slmicro61.

Remove suse build key install for slmicro6.1

---

salt/server_containerized/init.sls
salt/server_containerized/install_mgradm.sls

For MLM 5.1 on sles15sp7, the salt state `server_containerized.additional_disks` is failing because `mgr-storage-server` is not yet installed (done during combustion for slmicro61).
Move the uyuni tools installation outside mgradm installation state and call it before configuring the additional storages.

Install mgradm before configuring the additional_disks

---

modules/cucumber_testsuite/main.tf
salt/proxy_containerized/init.sls

We have those option available for the standalone server_containerized module but the cucumber_testsuite one does not properly forwards them when it's used to deploy a containerized server among its hosts.

Add wiring for custom containers repositories, images and tags

---

modules/build_host/main.tf
modules/client/main.tf
modules/controller/main.tf
modules/minion/main.tf
modules/proxy/main.tf
modules/proxy_containerized/main.tf
modules/server/main.tf
modules/server_containerized/main.tf
modules/sshminion/main.tf
modules/virthost/main.tf
salt/default/avahi.sls
salt/server_containerized/large_deployment.sls

This PR fixes two issues detected when deploying Uyuni released version:
- Fix state to configure DB in `uyuni-released`
- Fix some issues related to `avahi` (avahi-lang not existing in some cases - not really required for avahi functionality)
- Fix issue propagating `product_version` when defined for single modules [0]
[0] if the `product_version` is not set at `modules/xxxx/main.tf` then it won't be available here: https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/host/main.tf#L18 meaning, it will always fetch the `product_version` defined in "base", not allowing defining it for individual nodes.

Fix some issues deploying Uyuni released
